"""Render controlled layer ablations only on newly opened immutable copies.
Current saved context stays fixed; isolate the old versus new lunar RGB and
the context without the lunar source. Originals and their live state untouched.
"""
from reveal_common import *
info=json.loads((OUT/'A0_reference.json').read_text());assert sha(SOURCE)==sha(SNAP)==info['sha256']
state=jsx('var r=["ACTIVE|"+app.activeDocument.id+"|"+app.displayDialogs.toString()];for(var i=0;i<app.documents.length;i++){var d=app.documents[i];var f="";try{f=d.fullName.fsName;}catch(e){}r.push(d.id+"|"+d.name+"|"+d.saved+"|"+f);}r.join("\\n");');save('A1_documents_before.json',dict(state=state))
paths={k:str(OUT/f'A1_{k}.tif') for k in ['Pere_actual','sense_font_lunar','font_anterior_context_actual']}
assert all(not Path(p).exists() for p in paths.values())
js=r'''var original=app.activeDocument;var dialog=app.displayDialogs;var ids=[];for(var i=0;i<app.documents.length;i++)ids.push(app.documents[i].id);var d=null,o=null,t=null;function assertNew(doc){for(var i=0;i<ids.length;i++)if(doc.id===ids[i])throw new Error("Attempt to operate on original document");}function render(label,path){app.activeDocument=d;app.refresh();t=d.duplicate(label,true);var opt=new TiffSaveOptions();opt.imageCompression=TIFFEncoding.TIFFZIP;opt.layers=false;opt.alphaChannels=true;opt.transparency=true;opt.embedColorProfile=true;t.saveAs(new File(path),opt,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);t=null;}try{app.displayDialogs=DialogModes.NO;d=app.open(new File(__SNAP__));assertNew(d);var moon=d.artLayers.getByName(__NAME__);moon.visible=false;moon.visible=true;render("PERE_V49_REFERENCE",__ACTUAL__);moon.visible=false;render("PERE_V49_WITHOUT_MOON_SOURCE",__WITHOUT__);o=app.open(new File(__OLD__));assertNew(o);var oldMoon=o.artLayers.getByName(__NAME__);var imported=oldMoon.duplicate(d,ElementPlacement.PLACEATBEGINNING);app.activeDocument=d;imported.visible=true;render("PERE_V49_OLD_SOURCE_SAME_CONTEXT",__PREVIOUS__);}finally{if(t)t.close(SaveOptions.DONOTSAVECHANGES);if(o){assertNew(o);o.close(SaveOptions.DONOTSAVECHANGES);}if(d){assertNew(d);d.close(SaveOptions.DONOTSAVECHANGES);}app.displayDialogs=dialog;app.activeDocument=original;}"ABLATIONS_RENDERED_ORIGINAL_RESTORED";'''
for key,value in [('__SNAP__',SNAP),('__OLD__',OLD),('__NAME__',NAME),('__ACTUAL__',paths['Pere_actual']),('__WITHOUT__',paths['sense_font_lunar']),('__PREVIOUS__',paths['font_anterior_context_actual'])]:js=js.replace(key,json.dumps(str(value),ensure_ascii=False))
result=jsx(js);after=jsx('var r=["ACTIVE|"+app.activeDocument.id+"|"+app.displayDialogs.toString()];for(var i=0;i<app.documents.length;i++){var d=app.documents[i];var f="";try{f=d.fullName.fsName;}catch(e){}r.push(d.id+"|"+d.name+"|"+d.saved+"|"+f);}r.join("\\n");');assert after==state
assert sha(SOURCE)==info['sha256']
save('A1_native_ablation.json',dict(method=__doc__,result=result,files=paths,original_state_unchanged=True,original_sha256_unchanged=True,original_state=after,scope='Diagnostic exports only; no source/PSB changes. The old and current sources use exactly equal decoded alpha/mask, same placement and same current corona context.'))
print(result,flush=True)
