from a4_sources import *

def main():
 p=O/'analytic_local';r=json.loads((p/'COMPLETE.json').read_text());save(p/'METADATA_CORRIGENDUM.json',{'preserve_original':'FROZEN_TEST.json retained unchanged. Copied a20 case list is superseded by actual COMPLETE.json products and SCOPE.json.','actual_cases':sorted({v['case'] for v in r['products']}),'outputs':len(r['products']),'source_sha256_interpretation':'current_lunar_support.npz hash, not synthetic scene hash','authoritative_scope':'SCOPE.json','E3':'Pre-display median normalized detail d before tanh, SN and H1; original contrast profiles. This does not test full final E3 display transfer.','MGN':'Exact local operator on 2800 square ROI with >400 pixel protected halo for evaluated distance bands','retention_interval_authority':'QA_FROZEN.json: gain 0.9 to 1.1','development_not_blind_confirmation':True})
 save(O/'filters_biharmonic_E3/NOT_PROMOTED.json',{'status':'REJECTED','reason':'Unclipped biharmonic padding of chromatic log residual overshoots and induces broad gray ring in E3; loss in frozen-registration Brno morphology corroborates visible regression.','max_log_residual':[20.18,27.84],'exterior_max_log_residual':[3.43,3.12],'evidence':'E3_C_D.png; see BRNO_REVIEW.md','selected_replacement':'filters_screened_E3, L squared + L, unit grid tension 1; still bounded by declared near-limb transfer failures'})
 boundary=json.loads((O/'BOUNDARY_QA.json').read_text());local=json.loads((O/'LOCAL_BOUNDARY_QA.json').read_text())
 # Store verbatim QA references and explicit bounded-delivery decision.
 save(O/'SCIENTIFIC_DECISION.json',{'status':'BOUNDED_IMPROVEMENT_FOR_REVIEW','universal_scientific_PASS':False,'all_artifacts_resolved':False,'physical_radiance_correction_promoted':False,'operator_domain':'physical support AND NOT exact final lunar-photo support, applied also to Vixen/Sony/S4 auxiliary supports','selection':'filters_selected/MANIFEST.json','selection_history':'Development choices used analytical controls; not all variants preregistered. No post-hoc universal retention claim.','transfer_gate':[.9,1.1],'transfer_failed_cells_out_of_69':{'WOW_A_D':13,'WOW_bilateral_A_D':23,'MGN_B_D':28,'ACHF_01_T':15,'ACHF_04_T':19,'ACHF_05_T':14,'ACHF_06_T':20},'limits':['Near-boundary transfer fails predefined bounds: E3 below16px; WOW standard mostly below8px with exceptions to32px; bilateral also one128-256px case; MGN exceptions to64px.','Known-truth controls are development tests, not blind independent confirmation. E3 tests pre-display detail.','Brno assesses normalized angular morphology 1.15-2.4 R, not the immediate limb, color, or radial pedestal. No measured optical PSF.','Four Brno products share one team and are correlated references.','No measurement of occulted corona or exact restoration of moving-limb photometry.','Native Moon preservation and integrity are separate PASS scopes.'],'rejected':['limb_confidence_q16/NOT_PROMOTED.json','filters_biharmonic_E3/NOT_PROMOTED.json','analytic_boundary_attempt1_nonsmooth_center/NOT_PROMOTED.json'],'qa':['BOUNDARY_QA.json','LOCAL_BOUNDARY_QA.json','FINAL_NATIVE_VISUAL_QA.json','NATIVE_INTEGRITY.json'],'conditional_replay':'RAW calibration and documented baseline intermediate/filter outputs exact, conditional on frozen registration, display and manual assembly inputs; not end-to-end RAW-to-PSB determinism'})
 ref=R/'.claude/skills/corregeix-artefactes/references/lunar_boundary_and_display.md';text=ref.read_text();text=text.replace('P04 utilitza perfil B; P05 bilateral, A.','P04 històric utilitza perfil B; P05 bilateral, A. V85 prova explícitament P04 amb A i en declara la desviació del productor històric.')
 text+='''\n## Selecció V85 i límits que s’han de conservar\n\nEl farciment biharmònic sense límits va funcionar millor en alguns operadors\nescalars, però va sobrepassar fortament el rang del residu logarítmic RGB\ni va crear un anell gris ampli en ACHF. Aquesta variant E3 es va rebutjar.\nLa versió seleccionada usa L²+L, tensió unitària a la graella, dins la màscara;\nno és una recepta universal ni s’ha d’exportar a altres resolucions sense proves.\nWOW estàndard i bilateral seleccionen perfil A amb biharmònic; MGN, perfil B.\n\nEls controls de V85 milloren error contra veritat coneguda, però fallen\nl’interval de transferència 0,9–1,1 en 13/69 casos de WOW, 23/69 bilateral,\n28/69 MGN i 14–20/69 ACHF segons escala. Predominen els primers píxels\ndel contorn; hi ha excepcions més llunyanes. No convertir RMS menor,\nconvergència del solver o correlació Brno millor en «tot el limbe recuperat».\nE3 es va provar abans del display; Brno comença a 1,15 R i no avala color\nni pedestal radial. El lliurament és una millora amb límits per revisar.\n\nUna placa petita de preservació del compost natiu original pot ser necessària\nsi ajustos espacials de presentació alteren indirectament la Lluna. Cal\nmascara binària al suport estrictament afectat, mateixa geometria/ICC,\ni igualtat del compost de **tota** la Lluna. És preservació d’una aparença\nmanual, no recuperació científica ni excusa per tapar corona exterior.\n'''
 ref.write_text(text)
 dst=Path('/Users/USUARI/.codex/skills/corregeix-artefactes/references/lunar_boundary_and_display.md');dst.write_bytes(ref.read_bytes())
 print('DECISIONS_AND_REFERENCE_WRITTEN')
if __name__=='__main__':guard();main()
