from a4_sources import *
import shutil,yaml
from datetime import datetime,timezone

def main():
 gate=json.loads((O/'PHOTOSHOP_GATE.json').read_text());assert gate['PASS'];integrity=json.loads((O/'NATIVE_INTEGRITY.json').read_text());visual=json.loads((O/'FINAL_NATIVE_VISUAL_QA.json').read_text());decision=json.loads((O/'SCIENTIFIC_DECISION.json').read_text());utc=datetime.now(timezone.utc).isoformat();back=O/'docs_before_final';back.mkdir(exist_ok=True)
 paths=['IA/ACTIVE.json','IA/ESTAT_ACTUAL.md','IA/Coordinació/HANDOFF_VIGENT.md','IA/Skills/README.md']
 for path in paths:
  dst=back/Path(path).name;assert not dst.exists();shutil.copy2(R/path,dst)
 record={'utc':utc,'status':'DELIVERED_BOUNDED_IMPROVEMENT_NOT_ALL_LIMB_ARTIFACTS_VALIDATED','path':'1-PHOTOSHOP/V85.psb','sha256':gate['sha256'],'bytes':gate['bytes'],'canvas':[10551,7506],'depth':16,'layers':42,'photoshop_gate':gate['result'],'source':'1-PHOTOSHOP/V84.psb','source_sha256':integrity['input_sha256'],'source_unchanged':True,'regenerated_filter_layers':17,'regenerated_distinct_mounted_rasters':16,'moon_composite_exact':True,'green_mark_red_clipping_percent_before_after':[visual['original_unfiltered_red_clip_percent'],visual['final_red_clip_percent']],'all_artifacts_resolved':False,'universal_scientific_PASS':False,'full_RAW_to_PSB_deterministic':False,'report':'4-RESULTATS/v85_regeneracio_20260922/RESULTAT.md','receipt':'1-PHOTOSHOP/V85_REBUT.md','scientific_decision':'4-RESULTATS/v85_regeneracio_20260922/SCIENTIFIC_DECISION.json','code':'3-RECERCA/tools/v85_regeneracio_20260922','handoff':'.coordination/HANDOFF_2026-09-22_V85.md','limits':'Near-limb injected-detail transfer remains outside predefined bounds; no complete artifact-free limb claim. WOW bilateral angular broad-band Brno morphology slightly regresses.'}
 save(O/'REBUT.json',record)
 (R/'1-PHOTOSHOP/V85_REBUT.md').write_text(f'''# V85 — 22-09-2026\n\n**Tots els filtres de corona regenerats, verd marcat corregit i aparença lunar conservada.** La V84 de Pere queda intacta. La V85 és una millora per revisar: les proves encara no acrediten que tot el detall immediat al limbe estigui resolt.\n\n- 17 capes de filtres, 16 ràsters diferents; exclusió lunar abans de calcular i a les màscares finals.\n- 653.168 píxels lunars idèntics al compost original: diferència màxima 0 DN16.\n- Retall del vermell a la zona marcada: 71,82% → 0%. La causa diagnosticada és de presentació; no s’ha alterat el canal verd dels RAW.\n- 10551 × 7506, RGB de 16 bits, 42 capes. Photoshop: **{gate['result']}**.\n\nEls errors de contorn han disminuït, però alguns controls de detall fallen prop de la vora. WOW bilateral també perd una mica de correlació angular ampla amb Brno. No es declara «tot arreglat» ni corona oculta recuperada.\n\nLa capa «Aparença lunar V84 · compost natiu preservat» manté l’aparença de Pere davant dels efectes indirectes dels ajustos. PixInsight conserva la seva aportació lunar; la corona es mostra amb els filtres nous. Marques i referències queden conservades, ocultes.\n\nInforme i proves: `4-RESULTATS/v85_regeneracio_20260922/RESULTAT.md`. Skills `corregeix-artefactes` i `postprocessat-corona` i estat del projecte actualitzats.\n\nSHA-256 V85: `{gate['sha256']}`.\nSHA-256 V84 original: `{integrity['input_sha256']}`.\n''')
 active_path=R/'IA/ACTIVE.json';active=json.loads(active_path.read_text());active['updated']=utc;active['paths']['photoshop_current']='1-PHOTOSHOP/V85.psb';active['paths']['photoshop_previous_user']='1-PHOTOSHOP/V84.psb';active['paths']['v85_regeneration_report']=record['report'];active['v85_regenerated_filters']=record;active['latest_user_psb']={'path':'1-PHOTOSHOP/V84.psb','status':'Última V84 desada per Pere amb marques; entrada intacta de V85. La V85 és una versió regenerada amb límits pendents de revisió.','sha256':integrity['input_sha256'],'bytes':(R/'1-PHOTOSHOP/V84.psb').stat().st_size};save(active_path,active)
 state=R/'IA/ESTAT_ACTUAL.md';state.write_text('''# Estat actual — 22-09-2026 · V85\n\n`1-PHOTOSHOP/V85.psb`: tots els filtres regenerats; verd de presentació corregit; compost lunar exacte respecte de l’última V84 de Pere. Photoshop OBRE, 42 capes, 10551×7506 RGB16. V84 intacta.\n\n**Millora amb límits, no absència global d’artefactes.** Fallen controls de transferència prop del contorn; WOW bilateral té una petita regressió angular ampla. La correcció q16 de radiància i el biharmònic RGB sense tensió s’han rebutjat. Cap recuperació de corona oculta ni reconstrucció completa RAW→PSB declarada.\n\nRebut: `1-PHOTOSHOP/V85_REBUT.md`; informe: `4-RESULTATS/v85_regeneracio_20260922/RESULTAT.md`; traspàs: `.coordination/HANDOFF_2026-09-22_V85.md`. Skills i còpies de consum actualitzades. Els estats antics següents són històrics.\n\n'''+state.read_text())
 handoff='''# Traspàs V85 — 22-09-2026\n\nProducte lliurat: `1-PHOTOSHOP/V85.psb`; rebut al costat. Original protegit: última `1-PHOTOSHOP/V84.psb` de Pere, 41 capes, SHA33cdad0c452dc0afdf18d3e8b31e4d17700f3de5c34654cbd65eeac9c3a5a48b. Nou: 42 capes, mateixa geometria, compost lunar exacte.\n\nEntrada: `4-RESULTATS/v85_regeneracio_20260922/RESULTAT.md`, `REBUT.json`, `SCIENTIFIC_DECISION.json`. Codi `3-RECERCA/tools/v85_regeneracio_20260922/`. L’última selecció és `filters_selected/MANIFEST.json`; no el candidat biharmònic E3 rebutjat.\n\nS’han reexecutat calibració, intermedis i tots els filtres. El verd s’ha diagnosticat al revelat de presentació: no correcció G dels RAW. Domini dels filtres = suport físic menys foto lunar final, amb suports auxiliars també exclosos. Padding escalar biharmònic, ACHF RGB amb L²+L. Màscares i placa mínima conserven la Lluna exactament.\n\nObert: la petició «tot arreglat» no queda acreditada perquè la transferència injectada falla prop del disc; bilateral també regressa lleument en morfologia ampla Brno. Cal una nova hipòtesi si es continua, mantenint congelats controls, originals i geometria. No declarar PASS global ni ampliar el disc per ocultar el problema.\n\nConservar negatius: q16 crea quatre G negatius i té jutges mixtos; biharmònic E3 crea anell gris; metadades copiades tenen corrigenda explícits. Els 1505 RAW i les decisions editorials no s’han alterat. No atribuir determinisme complet RAW→PSB als replays condicionals.\n\nLes tasques APOD/whitepaper anteriors continuen amb els seus propis documents; no s’ha enviat ni publicat res.\n'''
 (R/record['handoff']).write_text(handoff);hp=R/'IA/Coordinació/HANDOFF_VIGENT.md';hp.write_text('# Handoff vigent — V85, 22-09-2026\n\nDocument: `.coordination/HANDOFF_2026-09-22_V85.md`. V85 lliurada amb tots els filtres regenerats i verd corregit; conservació lunar exacta. Límit pendent: fidelitat del detall immediat al limbe.\n\n## Històric anterior\n\n'+hp.read_text())
 skillrows=[]
 for name in ['apilatge-imatges-eclipsi','postprocessat-corona','corregeix-artefactes']:
  path=R/'.claude/skills'/name/'SKILL.md';meta=yaml.safe_load(path.read_text().split('---',2)[1]);assert meta['name']==name;row={'name':name,'canonical':str(path.relative_to(R)),'sha256':sha(path),'yaml_valid':True}
  if name!='apilatge-imatges-eclipsi':assert path.read_bytes()==(Path('/Users/USUARI/.codex/skills')/name/'SKILL.md').read_bytes();row['codex_entrypoint_exact']=True
  skillrows.append(row)
 ref=R/'.claude/skills/corregeix-artefactes/references/lunar_boundary_and_display.md';assert ref.read_bytes()==Path('/Users/USUARI/.codex/skills/corregeix-artefactes/references/lunar_boundary_and_display.md').read_bytes();save(O/'SKILL_FINAL_QA.json',{'skills':skillrows,'lunar_reference_sha256':sha(ref),'reference_codex_exact':True,'scope':'two modified entrypoints and the new reference synchronized; other skill assets not claimed synchronized'})
 index='''# Índex de skills del projecte\n\nActualitzat el 22-09-2026 per V85. La còpia canònica és `.claude/skills/` dins l’arrel del projecte Desktop; no hi ha repositori Git actual. Les instal·lacions globals són còpies de consum.\n\n'''
 for row in skillrows:index+=f"- `{row['name']}`: `{row['canonical']}`; SHA-256 `{row['sha256']}`.\n"
 index+='''\nLes entrades de `corregeix-artefactes` i `postprocessat-corona` i la referència nova `corregeix-artefactes/references/lunar_boundary_and_display.md` coincideixen amb les còpies de Codex. La resta d’actius no s’ha resincronitzat en bloc.\n\nV85 documenta diagnosi de color de presentació, separació dels suports físic/de càlcul/de sortida, risc d’OR amb S4, preservació del compost lunar, pèrdua de mostres E6 i límits de transferència al limbe. No prescriu un farciment universal ni afirma absència total d’artefactes.\n\nRebut: `4-RESULTATS/v85_regeneracio_20260922/SKILL_FINAL_QA.json`. Originals previs a `skill_before/` i índex anterior a `docs_before_final/`, dins del mateix paquet. Abans d’usar una skill, llegir-ne l’entrada i les referències obligatòries.\n\n`IA/Skills/` indexa les skills; els nous JPEG d’IA van a `IA/output/`, segons `IA/NORMES_I_AUTORITAT.md`.\n'''
 (R/'IA/Skills/README.md').write_text(index)
 save(O/'WORKING_STATE.json',{'utc':utc,'status':record['status'],'delivery':record['path'],'report':record['report'],'pending':'No complete near-limb transfer acceptance; see SCIENTIFIC_DECISION.json','claim':'release after zero active own processes','goal':'not marked complete because full requested artifact resolution remains unproven'})
 note=Path('/Users/USUARI/.codex/memories/extensions/ad_hoc/notes')/(datetime.now(timezone.utc).strftime('%Y-%m-%dT%H-%M-%SZ')+'-eclipse-v85-lunar-boundary.md');note.parent.mkdir(parents=True,exist_ok=True)
 note.write_text('''# Eclipse V85 — actualització demanada explícitament per Pere\n\nproject_id: Eclipse 2026\ncanonical_cwd: /Users/USUARI/Desktop/Eclipse 2026\n\nV85.psb lliurada el22-09-2026 amb17 capes de filtres regenerades (16ràsters), mateix llenç10551×7506RGB16,42capes, Photoshop OBRE. V84 original de Pere intacta. SHA V85: '''+gate['sha256']+'''. Rebut canònic: `4-RESULTATS/v85_regeneracio_20260922/RESULTAT.md`, JSON al costat; traspàs `.coordination/HANDOFF_2026-09-22_V85.md`.\n\nEl verd marcat prové de presentació/retall del vermell (71,82%→0% a la mostra), no s’ha demostrat G verd als RAW. Compressió RGB comuna abans d’ajustos. Regeneració condicional des de RAW/calibració i intermedis exactes, no prova completa RAW→PSB autònoma.\n\nExclusió lunar necessària abans de perfils/farciment/convolució i en tots els suports auxiliars (S4 no pot readmetre-la). Distingir suport físic, domini del filtre i sortida vàlida. Els filtres de sortida sols emmascarats encara poden estar contaminats. No ampliar el disc ni eliminar corona observada per tapar errors.\n\nV85 preserva exactament653168píxels del compost lunar, amb placa mínima nativa13903píxels interior a la Lluna. PixInsight234 només aporta Lluna perquè la seva corona antiga tapava filtres nous;225restringida al disc. E6exclou17/21sortides novament indefinides;0,5sotaMultiply no és neutre.\n\nLímit actual: no «tot arreglat». Controls de transferència fallen prop del contorn, i WOWbilateral regressa lleument en morfologia ampla Brno. Brno només1,15–2,4R, no color/pedestal/PSFmesurada. q16 crea4Gnegatius i es rebutja; biharmònic RGB sense tensió crea anellgris i es rebutja. Selecciódocumentada: WOWperfilA/MGNperfilB biharmònics, ACHFRGB L²+L; no receptauniversal. Skillsprojecte/còpiesd’entradaCodex actualitzades, referèncialunar_boundary_and_display.md. Preservarcontrols,negatius,manuals i originals.\n''')
 print('DOCS_SKILLS_MEMORY_UPDATED',utc,str(note))
if __name__=='__main__':guard();main()
