"""Frozen projected-solar-disk input ablation; no arbitrary radial margin."""
from a15_lunar_domain import *

def main():
 base=O/'d4_baseline/products/sources';out=O/'domain_solar_R02';out.mkdir();(out/'sources').mkdir();(out/'s4').mkdir();(out/'train_supports').mkdir();lunar=np.load(O/'current_lunar_support.npz');x0,y0,x1,y1=lunar['box'];sl=(slice(y0,y1),slice(x0,x1));y,x=np.mgrid[y0:y1,x0:x1];rs=440.60304883027544;r=np.hypot(y-3775.747534140857,x-5361.768111973117);m=r<rs;assert not np.any(m&~lunar['support']);np.savez(out/'EXCLUDED_SOLAR_DISK.npz',box=lunar['box'],mask=m,radius=rs);rows={}
 save(out/'FROZEN_ABLATION.json',{'geometry':{'cx':5361.768111973117,'cy':3775.747534140857,'R_solar':rs},'rule':'unchanged physical support AND projected r>=Rsolar, zero extra margin','reason':'train-only trace of bright S4-only final-frame samples at/in solar photospheric limb; physical support is not synonymous with coronal validity','caveat':'PSF/chromospheric/bead signal outside geometric disk remains possible; max11.7M persists0.68px outsideR','operator':'same unit-tension screened boundary L^2+L as physical_T_R02; profilesA forWOW, B forMGN; E3 unchanged','output':'existing finalMoon exclusion unchanged; no newly excluded visible pixel','MGN_normalization':'report actual domain extrema; assess separately from numerical boundary; displayLUT frozen','acceptance':'no radius fitting and no automaticPASS; compare existing marks, morphology and known-truth controls'})
 for name in ['base_G.npy','fusion_starless.npy','vixen_starless.npy','sony_starless.npy']:
  clone(base/name,out/'sources'/name);rows[name]={'sha256':sha(out/'sources'/name),'unchanged_photometric_source':True};assert rows[name]['sha256']==sha(base/name)
 for name,src,dst in [('physical',base/'support.npy',out/'sources/support.npy'),('vixen',O/'sources_v29/vixen_support.npy',out/'train_supports/vixen_support.npy'),('sony',O/'sources_v29/sony_support.npy',out/'train_supports/sony_support.npy')]:
  old=np.load(src);new=old.copy();new[sl]&=~m;assert np.array_equal(new[sl][~m],old[sl][~m]);np.save(dst,new);rows[name]={'physical_source':str(src.relative_to(R)),'physical_sha256':sha(src),'operator_sha256':sha(dst),'excluded_projected_solar_pixels':int(np.count_nonzero(old^new))};del old,new
 npz=O/'s4_baseline/cau/s4_recomposicio_box.npz';clone(npz,out/'s4'/npz.name);z=np.load(npz);sy0,sy1,sx0,sx1=z['box'];sm=np.load(O/'s4_baseline/cau/s4_support_new_box.npy');sm&=~m[sy0-y0:sy1-y0,sx0-x0:sx1-x0];np.save(out/'s4/s4_support_new_box.npy',sm)
 save(out/'MANIFEST.json',{'purpose':'controlled input-only projected solar disk exclusion; final photoMoon unchanged','physical_support':str((base/'support.npy').relative_to(R)),'physical_radiance_arrays_unchanged':True,'new_output_radius_or_margin':False,'solar_mask_source':'frozen common.py solar center/radius; exact radius no extra margin','mask_pixels':int(m.sum()),'sources':rows,'status':'controlled candidate; not promoted','scientific_limit':'physical support and r>=Rsolar do not prove uncontaminated corona; PSF and transients can spill outside'})
 print('SOLAR_DOMAIN_READY',rows['physical']['excluded_projected_solar_pixels'],flush=True)
if __name__=='__main__':guard();main()
