"""Reproduce train-only peak trace, no heldout numerator reads or source mutation."""
from a4_sources import *

def main():
 meta=json.loads((O/'limb_frames/METADATA.json').read_text());N=np.load(O/'limb_frames/numerator.npy',mmap_mode='r');W=np.load(O/'limb_frames/weight.npy',mmap_mode='r');D=np.load(O/'limb_frames/distance_model.npy',mmap_mode='r');G=np.load(O/'d4_baseline/products/sources/base_G.npy',mmap_mode='r');BG=np.load(O/'b3_baseline/cau/base_G_v42.npy',mmap_mode='r');P=np.load(O/'b3_baseline/cau/support_v42.npy',mmap_mode='r');matrix=np.asarray(meta['matrix'],dtype='f8');gain=np.asarray(meta['gain'],dtype='f8');y0,y1,x0,x1=meta['box_y0y1x0x1'];tb=json.loads((H/'v38_limb_round1/cau/correccio_vora_lunar.json').read_text())['taula'];a1=json.loads((H/'v38_limb_round1/receipts/A1_franja_font.json').read_text())['perfil_biaix_vs_distancia_vora'];cls={'curts':'curts (≤1/800)','mitjans':'mitjans (1/800–1/50)','llargs':'llargs (>1/50)'};results=[]
 for x,y in [(5725,4019),(5755,3967),(5758,3970),(5783,3905),(4924,3708)]:
  rows=[];held=0.;allweight=0.;nheld=0
  for j,f in enumerate(meta['frames']):
   d=float(D[j,y-y0,x-x0]);w=np.array(W[j,y-y0,x-x0],dtype='f8');e=f['exposure'];c='curts' if e<=1/800 else ('mitjans' if e<=1/50 else 'llargs');t=tb[c];pr=a1[cls[c]]['perfil'];dd=np.array([v['d'] for v in pr]);bl=np.array([v['mediana_ln'] for v in pr]);lo=dd<t['d_px'][0];nodes=np.r_[dd[lo],t['d_px']];bias=np.r_[bl[lo],t['B_ln']];corr=float(np.exp(-np.interp(d,nodes,bias,left=bias[0],right=0)));co=float(np.exp(-np.interp(d,t['d_px'],t['B_ln'],left=t['B_ln'][0],right=0)));old=np.clip((d-2)/2,0,1);ds={'curts':[0,-2,-4],'mitjans':[.5,-.5,None],'llargs':[1.5,None,None]}[c];tier=sum(gt*np.clip(d-d0,0,1)/corr**2 for gt,d0 in zip([.02,.0004,.000008],ds) if d0 is not None);eff=w[1]*(old+tier);allweight+=eff
   if not eff>0:continue
   if f['holdout']:held+=eff;nheld+=1;continue
   n=np.array(N[j,y-y0,x-x0],dtype='f8');cam=n/np.maximum(w,1e-30);rgb=(matrix@cam)*gain;rows.append({'name':f['name'],'time':f['time'],'exp':e,'D':d,'WG':float(w[1]),'effG':float(eff),'old_fl':float(old),'tier_mult':float(tier),'corrN':corr,'corrOld':co,'G_pre_bias':float(rgb[1]),'G_post_bias_tiers_only':float(rgb[1]*corr),'mixed_scalar_bias':float((old*co+tier*corr)/(old+tier))})
  rows.sort(key=lambda v:v['effG'],reverse=True);results.append({'xy':[x,y],'r':float(np.hypot(x-5361.768111973117,y-3775.747534140857)),'G_d4':float(G[y,x]),'B3_support':bool(P[y,x]),'G_B3':float(BG[y,x]),'heldout_weight_fraction':held/allweight if allweight else None,'heldout_n':nheld,'accepted_train_n':len(rows),'top_train':rows[:5]})
 out=O/'solar_peak_trace_R02';out.mkdir();save(out/'TRACE.json',{'scope':'float64 diagnostic reproducing peer train-only N/W trace, not float32 S4 replay','rows':results,'geometry_frozen':{'Rsolar':440.60304883027544,'cx':5361.768111973117,'cy':3775.747534140857},'interpretation':['support denominator positivity is not coronal-confidence evidence','tiny GT cancels in N/W for sole available tier','below projected solar radius does not prove direct photosphere: model says totality','3025 model-only registration has n_banda0; t117.51 is1.653s before calculated C3','remaining bright sample0.68px outsideRs shows geometric cut cannot certify uncontaminated corona','effG is CFA-G weight, not exact AdobeRGB-G contribution when CFA channel weights differ'],'holdout_numerator_read':False});assert results[0]['G_d4']==45148852.;assert results[0]['top_train'][0]['name']=='572A3025.CR3';print('SOLAR_PEAK_TRACE_REPRODUCED')
if __name__=='__main__':guard();main()
