from common58 import *
import datetime,os
IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');claim();pub=json.loads((O/'J0_publish.json').read_text());qa=json.loads((O/'I4_final_QA.json').read_text());opened=(O/'J1_open_final.txt').read_text().strip();assert 'V58.psb | 30 layers | saved=' in opened;now=datetime.datetime.now(datetime.timezone.utc).isoformat();handoff=R/'.coordination/HANDOFF_2026-09-13_CODEX_CAPES_TOTALS_V58.md';report=O/'RESULTAT.md';manifest=T/'delivery_manifest.json';body=(T/'RESULTAT_template.md').read_text()
repls={'PRODUCT':pub['path'],'SHA':pub['sha256'],'BYTES':str(pub['bytes']),'MASKMAX':'0','GATE':qa['Photoshop'],'READER':qa['independent_reader'],'CHANNELS':str(qa['n_edited_channels_verified']),'READBACK':str(qa['native_readback_max_DN16']),'MANIFEST':str(manifest),'HANDOFF':str(handoff)}
for k,v in repls.items():body=body.replace('@'+k+'@',v)
assert '@PRODUCT@' not in body
for p in (report,handoff):assert not p.exists();p.write_text(body)
preview=str(O/'vistes/V58_luna_1a1.png');m={**pub,'Photoshop':qa['Photoshop'],'native_readback_max_DN16':qa['native_readback_max_DN16'],'source_files_unchanged':qa['sources_unchanged'],'report':str(report),'handoff':str(handoff),'artifact_free':False,'PASS_scope':'Layer registration with held-out regions; causal localRHEF ring correction and conditional injections; 52 corroborated stellar components excluded before16filters; mask11 repaired; native mask activation/protection, Photoshop and pixel readback. Pere visual review remains pending.','open_document':opened,'all_filter_masks_enabled':True,'stellar_components_removed':52,'ambiguous_stellar_candidate':'TYC825-5-1 Vmag12.43 near(7783,6383), not suppressed','lunar_RGB_alpha_mask_geometry_exact':True,'original_count':30,'output_count':30,'unchanged_layers':qa['unchanged_layers'],'display_protection':'4px beyond actualV56feather;fullstrength12px;photometricprominence protection for4RHEF+2NRGF','alignment_receipt':str(O/'B10_alignment_readback.json'),'ring_receipt':str(O/'C5_real_period8.json'),'qa':str(O/'I4_final_QA.json'),'preview':preview,'limits':['photographic bright limb line retained','no all-pixel zero-registration guarantee between different instants','ambiguous stellar candidate remains','no new lunar resolution or DHS equivalence','localRHEF absolute correlation with unfilteredSony lower; claim limited to causal rings and injection retention'],'source_V57_Pere':{k:v for k,v in json.loads((O/'A0_freeze.json').read_text()).items() if k!='layers'}}
assert not manifest.exists();manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
prefix=f"> **13-09-2026 · Capes Totals V58: revisió dels sis punts de Pere.** V57 desada per Pere (30 capes) preservada; nova V58 de30capes,10551×7506RGB16. LROC i capes06–11 alineades amb controls reservats;12/perles exacta, compost solar reconstruït. EarthshineV56 RGB/alfa/màscara/geometria exactes.16filtres regenerats després de separar52fonts estel·lars corroborades;1candidat ambigu conservat. RHEF locals curats a l'operador (pic8px989→1,339 i1146→0,823); injeccions16/16. Màscares dels16filtres estaven desactivades: actives ara; protecció editable del limbe/perles als4RHEF+2NRGF, contribució0DN16 dins la franja protegida. Màscara11: illa i forat excessiu corregits sense ampliar la Lluna. PhotoshopOBRE, readback{qa['native_readback_max_DN16']}DN16, fontsV57/V56 exactes. Línia lluminosa de la base i judici visual dePere oberts; cap nova resolució/DHS. Producte `{pub['path']}`, SHA `{pub['sha256']}`. Represa `{handoff}`; informe `{report}`. Projecte general vigentV58; earthshine independentV56. Les entrades següents són història.\n\n"
rec=O/'receipts';rec.mkdir(exist_ok=True);rows=[]
for i,p in enumerate([R/'AGENTS.md',R/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md']):
 assert not p.is_symlink();old=p.read_bytes();snap=rec/f'J2_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(old);tmp=p.with_name(p.name+'.V58.tmp');assert not tmp.exists();tmp.write_bytes(prefix.encode()+old);assert p.read_bytes()==old;os.replace(tmp,p);assert p.read_bytes().endswith(old);rows.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),old_content_exact_suffix=True))
p=IA/'ACTIVE.json';old=p.read_bytes();snap=rec/'J2_before_ACTIVE.json';assert not snap.exists();snap.write_bytes(old);a=json.loads(old);earth=json.dumps(a['current_earthshine_product'],sort_keys=True);prior=a['current_product'];a['previous_general_product_V57_delivery']=prior;a['previous_general_product_V57_user_saved']=m['source_V57_Pere'];a['current_product']=m;a['updated']=now;a['phase']='post-eclipse-general-V58-six-corrections-delivered';a['formal_worktree_handoff']=str(handoff);a['paths']['current_technical_editable']=pub['path'];a['paths']['current_delivery_manifest']=str(manifest);a['paths']['current_visual_output']=str(O/'vistes');a['general_integration_task']={'status':'V58_DELIVERED_OPEN_IN_PHOTOSHOP','handoff':str(handoff),'report':str(report),'pending':'Pere visual review; photographic bright limb line and one ambiguous stellar candidate retained'};assert json.dumps(a['current_earthshine_product'],sort_keys=True)==earth
tmp=p.with_name(p.name+'.V58.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==old;os.replace(tmp,p);rows.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
save('J2_authorities.json',dict(time=now,rows=rows,CLAUDE_STATUS_untouched=True,earthshine_authority_exact=True))
with (R/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f'\n\n## {now} · CAPES TOTALS V58 LLIURADA · CLAIM HELD\n\n30 capes de la V57 de Pere; controls reservats d’alineament, anells RHEF curats a l’operador,52fonts corroborades separades abans dels16filtres, màscara11 reparada. Màscares16filtres activades; protecció editable del limbe/perles4RHEF+2NRGF efectiva amb0DN16 a la zona protegida. EarthshineV56 exacta; fontsV57/V56 exactes. PhotoshopOBRE i readback{qa["native_readback_max_DN16"]}DN16. Línia lluminosa fotogràfica i1candidat estel·lar ambigu oberts. Producte SHA {pub["sha256"]}. {opened}. Informe {report}; handoff {handoff}. Alliberament després de comprovar processos.\n')
print('DOCUMENTED',handoff,flush=True)
