var root='/Users/USUARI/Downloads/Eclipse 2026/output/v68_artefactes_20260914/',old=app.displayDialogs,own=[],oldDoc=app.activeDocument;
function log(s){var f=new File(root+'A2_native.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function L(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id===id)return d.layers[i];throw new Error('missing '+id);}
function only(d,ids){for(var i=0;i<d.layers.length;i++){var on=false;for(var j=0;j<ids.length;j++)if(d.layers[i].id===ids[j])on=true;d.layers[i].visible=on;}}
function mask(l,on){app.activeDocument.activeLayer=l;var d=new ActionDescriptor(),r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);d.putReference(charIDToTypeID('null'),r);var x=new ActionDescriptor();x.putBoolean(stringIDToTypeID('userMaskEnabled'),on);d.putObject(charIDToTypeID('T   '),charIDToTypeID('Lyr '),x);executeAction(charIDToTypeID('setd'),d,DialogModes.NO);}
function exp(d,n,full){var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber '+n);var t=d.duplicate('V68_QA_'+n,true);own.push(t);if(!full)t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
try{app.displayDialogs=DialogModes.NO;var d=app.open(new File(root+'V67_Pere_input.psb'));own.push(d);log('SOURCE '+d.id+' '+d.name+' '+d.saved+' '+d.layers.length);exp(d,'A2_marked_full',true);exp(d,'A2_marked_ROI',false);L(d,205).visible=false;exp(d,'A2_clean_full',true);exp(d,'A2_clean_ROI',false);
var cumulative=[[3],[3,41,42,45],[3,41,42,45,47,49,51,52,53,56],[3,41,42,45,47,49,51,52,53,56,30],[3,41,42,45,47,49,51,52,53,56,30,76],[3,41,42,45,47,49,51,52,53,56,30,76,96]];
for(var i=0;i<cumulative.length;i++){only(d,cumulative[i]);exp(d,'A2_c0'+i);}
var sources=[3,30,76,96];for(var i=0;i<sources.length;i++){var id=sources[i];only(d,[id]);exp(d,'A2_L'+id+'_masked');mask(L(d,id),false);exp(d,'A2_L'+id+'_unmasked');mask(L(d,id),true);}log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}try{app.activeDocument=oldDoc;}catch(e){}app.displayDialogs=old;}
