from pathlib import Path
import json,hashlib,datetime,os,re,subprocess
R=Path.cwd();T=R/'research/tools/v68_artefactes_20260914';O=R/'output/v68_artefactes_20260914';IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');claim='CODEX_V68_V67_ARTIFACTS_20260914'
def sha(p):
 with Path(p).open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def new(p,v):
 assert not p.exists(),p;p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
cp=R/'.coordination/claim.lock/owner.json';owner=json.loads(cp.read_text());assert owner['claim_id']==claim
pub=json.loads((O/'E2_publish.json').read_text());qa=json.loads((O/'D6_integrity.json').read_text());rb=json.loads((O/'E4_readback.json').read_text());gate=(O/'E2_photoshop_gate.txt').read_text().strip();opened=(O/'E3_final_open.log').read_text()
assert qa['PASS'] and rb['PASS'] and gate.startswith('OBRE ') and 'FINAL_OPEN_COMPLETE' in opened and 'name=V68.psb saved=true' in opened and 'DOC 59 name=V67.psb saved=false' in opened
assert 'PSB 10551x7506 16-bit' in (O/'E2_magick_reader.txt').read_text()
assert sha(pub['path'])==pub['sha256']
dest=Path(pub['path']).with_name('V68_dades');assert not dest.exists();dest.mkdir()
files={'vistes/V68_previsualitzacio.png':'V68_previsualitzacio.png','vistes/V68_lluna_i_limbe.png':'V68_lluna_i_limbe.png','vistes/D3_top.png':'V67_V68_llimb_superior.png','vistes/D3_SW.png':'V67_V68_punts_sud_oest.png','vistes/D3_east.png':'V67_V68_punt_est.png','vistes/D3_inside.png':'V67_V68_trama_lunar_x4.png','vistes/D3_whole.png':'V67_V68_comparacio.png','D6_integrity.json':'integritat.json','E1_all_five_marks.json':'marques_V67_i_resultat.json','E4_readback.json':'reobertura.json'};copied=[]
for a,b in files.items():
 src=O/a;dst=dest/b;subprocess.run(['/bin/cp','-c',str(src),str(dst)],check=True);assert sha(src)==sha(dst);copied.append(dict(path=str(dst),sha256=sha(dst)))
new(O/'E5_assets.json',dict(folder=str(dest),files=copied))
now=datetime.datetime.now(datetime.timezone.utc).isoformat();handoff=R/'.coordination/HANDOFF_2026-09-14_CODEX_CAPES_TOTALS_V68.md';report=O/'RESULTAT.md';manifest=T/'delivery_manifest.json'
body=(T/'RESULTAT_template.md').read_text()
for k,v in dict(NAME='V68.psb',PRODUCT=pub['path'],SHA=pub['sha256'],CHANNELS=len(qa['channel_checks']),GATE=gate,READBACK=rb['max_DN16'],PILOTMAX=qa['pilot_to_full_max_DN16']).items():body=body.replace('@'+k+'@',str(v))
assert not re.search(r'@[A-Z]+@',body)
for p in [report,handoff,dest/'LLEGEIX-ME_V68.md']:assert not p.exists();p.write_text(body)
m={**pub,'status':'V68_DELIVERED_MARKED_ARTIFACTS_REDUCED','time':now,'source_V67_sha256':qa['source_sha256'],'source_snapshot':str(O/'V67_Pere_input.psb'),'canvas':[10551,7506],'depth':16,'profile':'Adobe RGB (1998)','top_level_items':31,'report':str(report),'handoff':str(handoff),'manifest':str(manifest),'assets':str(dest),'preview':str(dest/'V68_previsualitzacio.png'),'qa':str(O/'D6_integrity.json'),'readback':rb,'modified_RGB_layers':[3,30],'blend_change':{'layer':30,'from':'HARD_LIGHT','to':'NORMAL'},'manual_Pere_geometry_preserved_exact':True,'all_original_masks_exact':True,'all_original_alpha_exact':True,'Pere_photo96_all_channels_exact':True,'stars_all_channels_exact':True,'Earthshine_RGB_exact':False,'independent_Earthshine_V56_unchanged':True,'artifact_free':False,'absolute_registration_resolved':False,'limits':['Fine exterior bright transition at upper limb remains.','Fine detector-pattern reduction is partial; broad corroborated lunar forms preserved.','No new optical resolution or universal absence of artifacts claimed.','No clean RAW-to-PSB end-to-end reproducibility claim.'],'open_document':opened,'UI_observation':'Native Photoshop states and complete exports verified; direct GUI capture unavailable.'}
new(manifest,m)
prefix=f'> **14-09-2026 · V68 lliurada des de V67 de Pere.** Encaix manual, totes les geometries, màscares i alfa exactes; perles96, interiors i estrelles exactes. RGB només3/30:25.658píxels de color completen les llums altes que havia exclòs la protecció de protuberàncies; patró fi lunar repetible estimat de12fontsVixen,630.705píxels amb resta igual als3canals.93/93retencions i12injeccions condicionals; fontVixen8–16 millora davantSony. Earthshine passaLuzfuerte→Normal per reduir la doblevora fosca. Resta transició clara exterior fina; trama reduïda parcialment,formes fosques amples corroborades preservades. **No moure ni reaplicar matrius.**31capes,{len(qa["channel_checks"])}comprovacions,PhotoshopOBRE,readbackcomplet{rb["max_DN16"]}DN16; foraROI0DN16. V67original i document59no desat intactes; V68oberta/desada. Producte `{pub["path"]}`,SHA `{pub["sha256"]}`; dades `{dest}`. Represa `{handoff}`; informe `{report}`. EarthshineV56independent intacta. Cap absència global d’artefactes ni nova resolució declarada. Les entrades següents són història.\n\n'
paths=[R/'AGENTS.md',R/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md',IA/'ACTIVE.json'];history={q['path']:q['after_sha256'] for q in json.loads((R/'output/v65_pere_estrelles_20260914/E5_authorities.json').read_text())['rows']};old={str(p):p.read_bytes() for p in paths}
for p in paths:assert hashlib.sha256(old[str(p)]).hexdigest()==history[str(p)],p
owner['scope'].append('V68 delivery receipts and canonical project authority pointers');cp.write_text(json.dumps(owner,indent=2)+'\n')
cs=sha(R/'.coordination/CLAUDE_STATUS.md');rows=[]
for i,p in enumerate(paths[:-1]):
 b=old[str(p)];snap=O/'receipts'/f'E5_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(b);tmp=p.with_name(p.name+'.V68.tmp');assert not tmp.exists();tmp.write_bytes(prefix.encode()+b);assert p.read_bytes()==b;os.replace(tmp,p);rows.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(b).hexdigest(),after_sha256=sha(p),old_content_exact_suffix=p.read_bytes().endswith(b)))
p=paths[-1];b=old[str(p)];snap=O/'receipts/E5_before_ACTIVE.json';snap.write_bytes(b);a=json.loads(b);earth={k:json.dumps(v,sort_keys=True) for k,v in a.items() if 'earthshine' in k and k!='general_earthshine_mask_override'}
a['previous_general_product_V65_delivery']=a['current_product'];a['current_product']=m;a['updated']=now;a['phase']='post-eclipse-general-V68-Pere-V67-artifacts';a['formal_worktree_handoff']=str(handoff);a['paths']['current_technical_editable']=pub['path'];a['paths']['current_delivery_manifest']=str(manifest);a['paths']['current_visual_output']=str(dest);a['general_integration_task']=dict(status=m['status'],handoff=str(handoff),report=str(report),pending='Pere visual review; fine exterior bright transition and residual fine pattern qualified in report.');a['historical_visual_task_before_V68']=a['visual_task'];a['visual_task']=dict(status=m['status'],target=pub['path'],next_action='Review five V67 marked regions in V68; preserve exact manual geometry and masks. Fine exterior transition remains qualified.');a['general_earthshine_mask_override']=dict(product=pub['path'],method='V67 geometry, mask and alpha exact. RGB fine detector correction, blend HARD_LIGHT to NORMAL. No added normalization layer.',independent_Earthshine_V56_unchanged=True)
assert all(json.dumps(a[k],sort_keys=True)==v for k,v in earth.items());tmp=p.with_name(p.name+'.V68.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==b;os.replace(tmp,p);rows.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(b).hexdigest(),after_sha256=sha(p)));assert sha(R/'.coordination/CLAUDE_STATUS.md')==cs
new(O/'E5_authorities.json',dict(time=now,rows=rows,CLAUDE_STATUS_sha256=cs,CLAUDE_STATUS_untouched=True))
with (R/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f'\n## {now} · V68 DELIVERED · CLAIM HELD\nSource V67 saved by Pere preserved; source document59 unsaved state unchanged. Exact all geometry/masks/alpha, interiors/perles96/stars; RGB3/30 and Moon blend only.31layers;{len(qa["channel_checks"])}channel checks; full forced readback{rb["max_DN16"]}DN16; outsideROI0DN16. White points corrected, double dark contour reduced, fine detector pattern partly reduced. Fine exterior bright transition remains qualified; broad lunar forms preserved. Product {pub["path"]}; SHA {pub["sha256"]}. Handoff {handoff}.\n')
print('DOCUMENTED',handoff,flush=True)
