var root='/Users/USUARI/Downloads/Eclipse 2026/output/v63_encaix_contorn_20260913/',own=[],old=app.displayDialogs;
function log(s){var f=new File(root+'A1_native.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function layer(d,id){for(var j=0;j<d.layers.length;j++)if(d.layers[j].id==id)return d.layers[j];throw new Error('layer '+id);}
function exp(d,n){var f=new File(root+n+'.tif');if(f.exists)throw new Error('no-clobber '+n);var t=d.duplicate('V63_QA_'+n,true);own.push(t);t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
function maskEnabled(l,on){app.activeDocument.activeLayer=l;var d=new ActionDescriptor(),r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);d.putReference(charIDToTypeID('null'),r);var x=new ActionDescriptor();x.putBoolean(stringIDToTypeID('userMaskEnabled'),on);d.putObject(charIDToTypeID('T   '),charIDToTypeID('Lyr '),x);executeAction(charIDToTypeID('setd'),d,DialogModes.NO);}
try{app.displayDialogs=DialogModes.NO;var src=null;for(var i=0;i<app.documents.length;i++)if(app.documents[i].name==='V62.psb')src=app.documents[i];if(!src||!src.saved)throw new Error('Expected saved V62');var d=src.duplicate('V63_DIAGNOSTIC',false);own.push(d);
exp(d,'A1_default');layer(d,76).visible=false;exp(d,'A1_no_interiors');for(var i=0;i<d.layers.length;i++)if(d.layers[i].id>=41&&d.layers[i].id<=56)d.layers[i].visible=false;exp(d,'A1_base_moon');layer(d,30).visible=false;exp(d,'A1_base');
layer(d,30).visible=true;for(var id=41;id<=47;id++){layer(d,id).visible=true;exp(d,'A1_base_moon_plus_'+id);}
for(var i=0;i<d.layers.length;i++)d.layers[i].visible=false;layer(d,76).visible=true;exp(d,'A1_interiors_masked');maskEnabled(layer(d,76),false);exp(d,'A1_interiors_unmasked');
for(var i=0;i<d.layers.length;i++)d.layers[i].visible=false;layer(d,30).visible=true;exp(d,'A1_moon');log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}app.displayDialogs=old;}
