var root='/Users/USUARI/Downloads/Eclipse 2026/output/v63_encaix_contorn_20260913/',old=app.displayDialogs,own=[];
function log(s){var f=new File(root+'D0_native.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function layer(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id==id)return d.layers[i];throw new Error('missing '+id);}
function exp(d,n,crop){var t=d.duplicate('V63_QA_'+n,true);own.push(t);if(crop)t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber');var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
function maskEnabled(l,on){app.activeDocument.activeLayer=l;var d=new ActionDescriptor(),r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);d.putReference(charIDToTypeID('null'),r);var x=new ActionDescriptor();x.putBoolean(stringIDToTypeID('userMaskEnabled'),on);d.putObject(charIDToTypeID('T   '),charIDToTypeID('Lyr '),x);executeAction(charIDToTypeID('setd'),d,DialogModes.NO);}
try{app.displayDialogs=DialogModes.NO;var d=null;for(var i=0;i<app.documents.length;i++)if(app.documents[i].name==='V63_pilot.psb')d=app.documents[i];if(!d||d.layers.length!==24)throw new Error('expected pilot');app.activeDocument=d;
var states=[];for(var i=0;i<d.layers.length;i++)states.push(d.layers[i].visible);
for(var i=0;i<d.layers.length;i++)d.layers[i].visible=false;layer(d,76).visible=true;maskEnabled(layer(d,76),false);exp(d,'D0_foreground_unmasked',true);maskEnabled(layer(d,76),true);for(var i=0;i<d.layers.length;i++)d.layers[i].visible=states[i];
layer(d,3).name='00 Base corba · color V62 · cobertura del limbe V63';for(var id=41;id<=46;id++)layer(d,id).name=layer(d,id).name.replace('· V61 ·','· V63 ·');layer(d,30).name='Earthshine V56 · revelat de Pere · cobertura revisada V63';layer(d,76).name='Interiors 06–12 · perles i protuberàncies · V63';d.activeLayer=layer(d,76);
exp(d,'V63_candidate',false);d.save();log('SAVED '+d.saved+' '+d.layers.length+' layers');exp(d,'V63_saved_ROI',true);app.runMenuItem(stringIDToTypeID('actualPixels'));log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}app.displayDialogs=old;}
