var root='/Users/USUARI/Downloads/Eclipse 2026/output/v62_prominencies_20260913/';var old=app.displayDialogs,own=[];var target=null;
function log(s){var f=new File(root+'D2_native.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function corners(l){var r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);var a=executeActionGet(r).getObjectValue(stringIDToTypeID('smartObjectMore')).getList(stringIDToTypeID('transform'));var q=[];for(var i=0;i<a.count;i++)q.push(a.getDouble(i));return q;}
function exp(d,n,bb){var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber');var t=d.duplicate('V62_QA_'+n,true);own.push(t);if(bb)t.crop([UnitValue(bb[0],'px'),UnitValue(bb[1],'px'),UnitValue(bb[2],'px'),UnitValue(bb[3],'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
function get(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id==id)return d.layers[i];throw new Error('missing '+id);}
try{app.displayDialogs=DialogModes.NO;log('BEGIN');var e=app.open(new File(root+'Interiors_V62_editables.psb'));own.push(e);if(e.layerSets.length!=1||e.layerSets[0].layers.length!=8)throw new Error('expected 7 originals + divide');exp(e,'V62_embedded_dematte',[3480,2365,5480,4365]);e.save();log('EMBEDDED SAVED');e.close(SaveOptions.DONOTSAVECHANGES);own.pop();
var d=app.open(new File(root+'V62_work.psb'));target=d;var l=get(d,76);var before=corners(l);d.activeLayer=l;var q=new ActionDescriptor();q.putPath(charIDToTypeID('null'),new File(root+'Interiors_V62_editables.psb'));executeAction(stringIDToTypeID('placedLayerReplaceContents'),q,DialogModes.NO);l=get(d,76);var after=corners(l),err=0;for(var i=0;i<8;i++)err=Math.max(err,Math.abs(after[i]-before[i]));log('TRANSFORM '+after.join(','));log('CORNER_ERROR '+err);if(err>1e-7)throw new Error('changed geometry');
exp(d,'V62_candidate',null);exp(d,'V62_candidate_ROI',[4377,2777,6377,4777]);var vis=[];for(var i=0;i<d.layers.length;i++){vis.push(d.layers[i].visible);d.layers[i].visible=false;}get(d,76).visible=true;exp(d,'V62_interiors_only',[4377,2777,6377,4777]);for(var i=0;i<d.layers.length;i++)d.layers[i].visible=vis[i];
d.activeLayer=get(d,76);d.save();log('ROOT SAVED '+d.saved+' layers='+d.layers.length);exp(d,'V62_saved_readback',[4377,2777,6377,4777]);log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}app.displayDialogs=old;}
