var root='/Users/USUARI/Downloads/Eclipse 2026/output/v62_prominencies_20260913/';var old=app.displayDialogs,own=[];var target=null;
function log(s){var f=new File(root+'D7_pilots.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function corners(l){var r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);var a=executeActionGet(r).getObjectValue(stringIDToTypeID('smartObjectMore')).getList(stringIDToTypeID('transform'));var q=[];for(var i=0;i<a.count;i++)q.push(a.getDouble(i));return q;}
function exp(d,n,bb){var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber');var t=d.duplicate('V62_QA_'+n,true);own.push(t);if(bb)t.crop([UnitValue(bb[0],'px'),UnitValue(bb[1],'px'),UnitValue(bb[2],'px'),UnitValue(bb[3],'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
function get(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id==id)return d.layers[i];throw new Error('missing '+id);}
function maskEnabled(l,on){app.activeDocument.activeLayer=l;var d=new ActionDescriptor(),r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);d.putReference(charIDToTypeID('null'),r);var x=new ActionDescriptor();x.putBoolean(stringIDToTypeID('userMaskEnabled'),on);d.putObject(charIDToTypeID('T   '),charIDToTypeID('Lyr '),x);executeAction(charIDToTypeID('setd'),d,DialogModes.NO);}
try{app.displayDialogs=DialogModes.NO;var src=null;for(var i=0;i<app.documents.length;i++)if(app.documents[i].name==='V62_preserved_work.psb')src=app.documents[i];if(!src||!src.saved)throw new Error('Expected saved owned V62');
var d=src.duplicate('V62_AA_PILOT_B',false);own.push(d);get(d,30).visible=false;var f=app.open(new File(root+'C3_Moon_pixel_integrated.psb'));own.push(f);f.layers[0].duplicate(d,ElementPlacement.PLACEATBEGINNING);f.close(SaveOptions.DONOTSAVECHANGES);own.pop();app.activeDocument=d;var ll=d.layers[0];maskEnabled(ll,false);log('UNMASKED BEFORE '+ll.bounds.toString());ll.translate(UnitValue(4677-ll.bounds[0].as('px'),'px'),UnitValue(3077-ll.bounds[1].as('px'),'px'));log('UNMASKED AFTER '+ll.bounds.toString());maskEnabled(ll,true);exp(d,'V62_AA_pilot_B',[4377,2777,6377,4777]);d.close(SaveOptions.DONOTSAVECHANGES);own.pop();
var d=src.duplicate('V62_CLIP_PILOT_B',false);own.push(d);var states=[];for(var i=0;i<d.layers.length;i++)states.push([d.layers[i].id,d.layers[i].visible]);for(var i=0;i<d.layers.length;i++){var l=d.layers[i];if(l.id>=41&&l.id<=56)l.grouped=true;}for(var i=0;i<d.layers.length;i++){log('CLIP '+d.layers[i].id+' BEFORE '+states[i][1]+' AFTER '+d.layers[i].visible);d.layers[i].visible=states[i][1];}exp(d,'V62_clip_pilot_B',[4377,2777,6377,4777]);log('COMPLETE');
}catch(e){log('ERROR '+e);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}app.displayDialogs=old;}
