"""Test a fixed4px intermediate scatter proxy after the frozen12px inverse.
No narrow-core sharpening or eclipse source edit. Native samples are only
aggregated into fixed5px diagnostic cells; geometric core guard is6px.
"""
from intermediate_common import *
from scipy.ndimage import gaussian_filter,map_coordinates
import time
step=5;nc=N//step;aa=P12/(1-P12);coeff=np.array([aa,-aa**2,aa**3,-aa**4]);edge=np.load(ROOT/'research/tools/v44_earthshine_20260910/cau/vixen_optical_edge.npy');epochs=json.loads((ROOT/'output/v45_earthshine_20260910/4-rebuts/F2_temporal.json').read_text())['epochs'];metadata={s:dict(epoch=k,time_C2=t) for k,v in epochs.items() for s,t in zip(v['frames'],v['times'])}
save('PLAN.json',dict(method=__doc__,hypothesis='A fixed additional4px component remains after the previously qualified12px mixture; estimate only its nonnegative temporal witness amplitude.',frozen_p12=P12,training=TRAIN,retrospective_validation=RETRO,new_witness=FRESH,model='Z=H12_inverse(Y); test Z = common lunar-cell nuisance + frame plane + f*G4(Z), f in[0,0.1]. First-order witness only, not a physical PSF fraction.',sigma_intermediate=4,geometry='native r415-449px and at least6px inside inherited observed lunar edge; no new pose correction',support_minimum=.995,native_cell_step=5,nuisance_calibration_radius=[415,423],score_radius=[426,449],gates=dict(minimum_epoch_improvement_percent=5,epochs=6,no_worse_sector_fraction=.75,no_worse_ratio=1.02,epochs_prefer_actual_over_rotated=5),controls='Refitted zero-intermediate model,90deg rotated predictor, angular halves, exact linear-design coefficient injection',limitations=['p12 inherited and conditional on its earlier model; new component is not automatically an optical PSF','Original calibration and contour shared;8fresh witnesses are new to this temporal fit, not untouched throughout the whole project','6px core guard mitigates but does not prove absence of seeing/core contamination','Variance uses frozen conditional calibration and omits shared covariance; temporal/angle checks required','No completed or generated pixel may enter a scientific source'],sources=[dict(title='Norton et al., Stray Light Correction for the Helioseismic and Magnetic Imager',url='https://arxiv.org/abs/2511.13348',relevance='Occultation data can test a PSF; the HMI instrument model is not imported into Vixen.'),dict(title='Courrier et al., An on Orbit Determination of Point Spread Functions for IRIS',url='https://link.springer.com/article/10.1007/s11207-018-1347-9',relevance='Transit-based instrument-response estimation; no numerical parameters transferred.')]))
rows=[]
for stem in TRAIN+RETRO+FRESH:
    start=time.time();z=np.load(SRC/f'A0_quincunx_{stem}.npz');native=np.load(SRC/f'A0_native_samples_{stem}.npz');good=np.isfinite(z['g'])&(z['q']>0);x=native['x'];y=native['y'];radius=np.hypot(x-CX,y-CY);angle=np.arctan2(y-CY,x-CX)%(2*np.pi);er=np.interp(angle,np.arange(len(edge))*2*np.pi/len(edge),edge,period=2*np.pi);distance=radius-er;selection=(radius>=415)&(radius<449)&(distance<=-6)&native['valid']&(native['q']>0)&np.isfinite(native['g'])&np.isfinite(native['variance'])&(native['variance']>0);xr=CX-(y-CY);yr=CY+(x-CX);available=np.ones(len(x));Z=native['g'].copy();true=np.zeros(len(x));null=true.copy();raw=np.where(good,z['g'],0).astype(float)
    for kind,k,sigma,multiplier in [('wide',k,12*np.sqrt(k),-coeff[k-1]) for k in range(1,5)]+[('intermediate',k,np.sqrt(16+144*k),1 if k==0 else -coeff[k-1]) for k in range(5)]:
        den=gaussian_filter(good.astype(float),sigma,truncate=5);field=gaussian_filter(raw,sigma,truncate=5)/np.maximum(den,1e-30);values=map_coordinates(field,[y,x],order=1,mode='nearest',prefilter=False);support=map_coordinates(den,[y,x],order=1,mode='nearest',prefilter=False);available=np.minimum(available,support)
        if kind=='wide':Z+=multiplier*values
        else:
            true+=multiplier*values;null+=multiplier*map_coordinates(field,[yr,xr],order=1,mode='nearest',prefilter=False);available=np.minimum(available,map_coordinates(den,[yr,xr],order=1,mode='nearest',prefilter=False))
    Z/=1-P12;true/=1-P12;null/=1-P12;before=int(selection.sum());selection &= available>=.995;ids=np.floor(y/step).astype(int)*nc+np.floor(x/step).astype(int);count=np.bincount(ids[selection],minlength=nc*nc);cells=np.flatnonzero(count>=5);cnt=count[cells];values={}
    for key,array in [('g',Z),('raw_g',native['g']),('t',true),('q',null),('x',x),('y',y),('distance',distance)]:values[key]=np.bincount(ids[selection],weights=array[selection],minlength=nc*nc)[cells]/cnt
    vm=float(np.median(native['variance'][selection]))/(1-P12)**2;values['weight_variance']=vm/cnt;values['count']=cnt;values['cell']=cells;values['cell_x']=(cells%nc+.5)*step;values['cell_y']=(cells//nc+.5)*step;values['radius']=np.hypot(values['cell_x']-CX,values['cell_y']-CY);values['angle']=np.arctan2(values['cell_y']-CY,values['cell_x']-CX)%(2*np.pi)
    np.savez_compressed(OUT/f'A0_cells_{stem}.npz',**values);rows.append(dict(stem=stem,role='training' if stem in TRAIN else 'retrospective' if stem in RETRO else 'new_witness',**metadata[stem],native_before_support=before,native_after_support=int(selection.sum()),cells=len(cells),seconds=time.time()-start));save('A0_inputs.json',dict(method=__doc__,frames=rows));print(stem,rows[-1]['role'],len(cells),'cells',round(time.time()-start,2),'seconds',flush=True)
print('DONE',len(rows),flush=True)
