"""Recreate full calibrated native green fields without resampling their radiance.
The frozen V49 native annulus must be reproduced exactly at every stored sample.
Only new diagnostic caches are written; no source PSB or original array changes.
"""
from intermediate_common import *
import sys,time,argparse
sys.path.insert(0,str(ROOT/'research/tools/v45_earthshine_20260910'))
from b1_native import f2,comu,RUNS,COMMON_TO_FINAL,CAU36,B,MC,rawpy,cv2
parser=argparse.ArgumentParser();parser.add_argument('--stems',nargs='+');args=parser.parse_args();stems=args.stems or TRAIN+RETRO+FRESH
inventory={r['stem']:r for r in json.loads((ROOT/'output/v45_earthshine_20260910/4-rebuts/B1_inputs.json').read_text())['frames']};frozen={r['stem']:r for r in json.loads((SRC/'A2_all_native.json').read_text())['frames']};ctx=f2.Ctx(comu.Run.obre(str(RUNS['vixen'])));pos=json.loads((RUNS['vixen']/'4-rebuts/F1.3_registre.json').read_text())['fotogrames'];kq=json.loads((RUNS['vixen']/'4-rebuts/F2.2_coherencia.json').read_text())['k'];meta=json.loads((CAU36/'vixen_meta.json').read_text())['frames'];fcorr,frep=B.flat_ripple_correction(ctx,'vixen');phis=np.load(CAU36/'vixen_G_phi.npy',mmap_mode='r');inv=cv2.invertAffineTransform(COMMON_TO_FINAL);D=np.array([[ctx.ca,ctx.sa],[-ctx.sa,ctx.ca]])@inv[:2,:2]*ctx.k;J=np.linalg.inv(D);assert np.max(abs(J.T@J-np.eye(2)))<1e-8;X0,Y0=4677,3077
receipt=OUT/'D0_native_fields.json';rows=json.loads(receipt.read_text())['frames'] if receipt.exists() else [];done={r['stem'] for r in rows};save('D0_native_plan.json',dict(method=__doc__,calibration='Exact inherited V49 dark/flat/FPN/scale/offset/phi; recover the same native green measurements, then allow convolution directly on their regular lattice.',validity='Same native raw-relative<0.85 and sensor validity; no brightness floor on radiance',lattice='u=(nx+ny-1)/2,v=(nx-ny-1)/2; physical pitchsqrt2; no spatial interpolation of observed radiance',identity_gate='Every g,variance,q,valid sample at frozen native annulus must match exactly; same RAW SHA256',requested_stems=TRAIN+RETRO+FRESH,source_or_PSB_edit=False))
for stem in stems:
    if stem in done:
        assert (OUT/f'D0_native_field_{stem}.npz').exists();print(stem,'existing verified checkpoint',flush=True);continue
    start=time.time();m=inventory[stem];nom=m['nom'];v=pos[nom];j=next(i for i,a in enumerate(meta) if a['name']==nom);mm=meta[j];sx,sy=m['native']['shift'];nxc=v['sol_x']+v['lluna_dx'];nyc=v['sol_y']+v['lluna_dy'];corners=np.array([[X0,Y0],[X0+N-1,Y0],[X0,Y0+N-1],[X0+N-1,Y0+N-1]],float);nn=(corners-np.array([MC[0]+sx,MC[1]+sy]))@D.T+np.array([nxc,nyc]);u=(nn[:,0]+nn[:,1]-1)/2;vv=(nn[:,0]-nn[:,1]-1)/2;u0=int(np.floor(u.min()))-4;u1=int(np.ceil(u.max()))+4;v0=int(np.floor(vv.min()))-4;v1=int(np.ceil(vv.max()))+4;V,U=np.mgrid[v0:v1+1,u0:u1+1];nx=1+U+V;ny=U-V
    with Path(ctx.ruta[nom]).open('rb') as file:sha=hashlib.file_digest(file,'sha256').hexdigest()
    assert sha==frozen[stem]['raw_sha256'],stem
    with rawpy.imread(ctx.ruta[nom]) as rawfile:raw=rawfile.raw_image.astype(np.float32)
    inside=(nx>=0)&(ny>=0)&(nx<raw.shape[1])&(ny<raw.shape[0]);plans=ctx.plans(nom,v['exp']);g=np.zeros(U.shape);quality=g.copy();var=g.copy();rn=np.ones(U.shape);bad=np.ones(U.shape,bool);assigned=np.zeros(U.shape,bool)
    for i in ctx.orig:
        if comu.IDX_CANAL[i]!=1:continue
        oy,ox=ctx.orig[i];sel=inside&((ny-oy)%2==0)&((nx-ox)%2==0);iy=(ny[sel]-oy)//2;ix=(nx[sel]-ox)//2;rp=raw[oy::2,ox::2];pl=plans[i][0];corr=fcorr[i][iy,ix] if fcorr is not None else 1.;cal=pl[iy,ix]*corr;k=kq.get(nom,1.);g[sel]=cal*k;rn[sel]=(rp[iy,ix]-ctx.cfg['pedestal_dn'])/(ctx.cfg['saturacio_dn']-ctx.cfg['pedestal_dn']);z=np.clip((rn[sel]-.35)/.5,0,1);quality[sel]=1-z*z*(3-2*z);bad[sel]=(rn[sel]>=.85)|(ctx.valid[oy::2,ox::2][iy,ix]<=0)|~np.isfinite(cal);assigned[sel]=True;read=1.05 if v['exp']>=1 else 2.72;noise=np.maximum(rp[iy,ix]-ctx.cfg['pedestal_dn'],0)/5.08+2*read*read;scale=k/(np.maximum(ctx.flat[oy::2,ox::2][iy,ix],1e-12)*v['exp'])*corr;var[sel]=noise*scale*scale
    assert np.array_equal(assigned,inside);wx=MC[0]+sx+J[0,0]*(nx-nxc)+J[0,1]*(ny-nyc);wy=MC[1]+sy+J[1,0]*(nx-nxc)+J[1,1]*(ny-nyc);phi_full=B.upsample(phis[j]);fx=(wx-sx).astype(np.float32).ravel();fy=(wy-sy).astype(np.float32).ravel();field=np.concatenate([np.exp(-cv2.remap(phi_full,fx[a:a+16000][None,:],fy[a:a+16000][None,:],cv2.INTER_LINEAR,borderMode=cv2.BORDER_REPLICATE))[0] for a in range(0,len(fx),16000)]).reshape(U.shape);g=(g+mm['offset_RGB'][1])*field;var=var*field**2;q=np.where(~bad,quality,0);old=np.load(SRC/f'A0_native_samples_{stem}.npz');ou=((old['native_x']+old['native_y']-1)//2-u0).astype(int);ov=((old['native_x']-old['native_y']-1)//2-v0).astype(int)
    # v=(nx-ny-1)/2, as in original U/V definitions nx=1+U+V,ny=U-V.
    checks={key:bool(np.array_equal(value[ov,ou],old[key],equal_nan=True)) for key,value in [('g',g),('variance',var),('q',q),('valid',~bad)]};checks['x']=bool(np.array_equal(wx[ov,ou]-X0,old['x']));checks['y']=bool(np.array_equal(wy[ov,ou]-Y0,old['y']));assert all(checks.values()),(stem,checks)
    out=OUT/f'D0_native_field_{stem}.npz';assert not out.exists();np.savez_compressed(out,g=g,variance=var,q=q,valid=~bad,u0=u0,v0=v0,native_to_world=J,world_origin=np.array([MC[0]+sx,MC[1]+sy])-J@np.array([nxc,nyc])-np.array([X0,Y0]));row=dict(stem=stem,raw_sha256=sha,file=str(out),shape=list(g.shape),native_annulus_samples=len(old['g']),exact_identity=checks,valid_fraction=float((~bad).mean()),seconds=time.time()-start);rows.append(row);save('D0_native_fields.json',dict(method=__doc__,frames=rows));print(stem,'EXACT',len(old['g']),'native samples',round(time.time()-start,2),'seconds',flush=True)
    del raw,plans,g,var,q,bad,quality,rn,phi_full,field,U,V,nx,ny,wx,wy,old,fx,fy
print('DONE',len(rows),'native fields',flush=True)
