"""Cross-green native convolution: each measured green uses the opposite plane.
Keep two separate observation rows per lunar cell, never average the two before
scoring; averaging would reintroduce target-photon noise into its predictor.
"""
from intermediate_common import *
from scipy.ndimage import gaussian_filter,map_coordinates
import time
aa=P12/(1-P12);cw=np.array([aa,-aa**2,aa**3,-aa**4]);step=5;nc=N//step;edge=np.load(ROOT/'research/tools/v44_earthshine_20260910/cau/vixen_optical_edge.npy');rows=[];meta={r['stem']:r for r in json.loads((OUT/'A1_inputs.json').read_text())['frames']}
save('D1_crossgreen_plan.json',dict(method=__doc__,hypothesis='Same-pixel noise in an observed Gaussian predictor may reduce prediction error spuriously. Use opposite green samples for every optical term and score target greens separately.',model='Same positive H12/H4 cascade, same6px core guard, same temporal partitions and gates. p12 stays frozen; p4 refit only on8training captures.',source='Exact full native fields D0; isotropic Gaussian uses sigma/sqrt2 on native quincunx coordinates. Opposite-plane Gaussian denominator normalized by density0.5 for physical support.',independence='Photons and read noise of the two raw green pixels are disjoint. Flat/phi/dark/FPN calibration is still shared. Subtracting a noisy frozen wide term can cause conservative errors-in-variables bias; this is not complete sensor independence.',nuisance='Common latent lunar-cell value and per-frame plane; two green observations are kept as separate rows with their own conditional variance.',numeric='Actual-angle terms sampled directly at native indices;90deg control uses cubic evaluation of already smoothed native fields. No resampled eclipse source.',gates='Unchanged >=5percent improvement in each6epochs;>=75percent sectors no worse than2percent; actual beats rotated in>=5epochs; numerical bound<=0.1G.'))
specs=[(0,j,144*j,-cw[j-1]) for j in range(1,5)]+[(k,j,16*k+144*j,1 if j==0 else -cw[j-1]) for k in range(1,6) for j in range(5)]
for stem in TRAIN+RETRO+FRESH:
    start=time.time();z=np.load(OUT/f'D0_native_field_{stem}.npz');n=np.load(SRC/f'A0_native_samples_{stem}.npz');g=z['g'];v0=int(z['v0']);u0=int(z['u0']);vv,uu=np.mgrid[:g.shape[0],:g.shape[1]];nx=1+(uu+u0)+(vv+v0);parity=nx%2;tu=((n['native_x']+n['native_y']-1)//2-u0).astype(int);tv=((n['native_x']-n['native_y']-1)//2-v0).astype(int);target_parity=n['native_x']%2;x=n['x'];y=n['y'];rad=np.hypot(x-CX,y-CY);ang=np.arctan2(y-CY,x-CX)%(2*np.pi);distance=rad-np.interp(ang,np.arange(len(edge))*2*np.pi/len(edge),edge,period=2*np.pi);selection=(rad>=415)&(rad<449)&(distance<=-6)&n['valid']&(n['q']>0)&np.isfinite(n['g'])&np.isfinite(n['variance'])&(n['variance']>0);worldrot=np.stack([CX-(y-CY),CY+(x-CX)],1);native_rot=(worldrot-z['world_origin'])@np.linalg.inv(z['native_to_world']).T;ur=(native_rot[:,0]+native_rot[:,1]-1)/2-u0;vr=(native_rot[:,0]-native_rot[:,1]-1)/2-v0;Z=n['g'].copy();T=np.zeros((5,len(x)));Q=T.copy();available=np.ones(len(x));base_valid=z['valid']&(z['q']>0)&np.isfinite(g)
    for source_parity in [0,1]:
        valid=base_valid&(parity==source_parity);raw=np.where(valid,g,0);target=target_parity!=source_parity;ix=tu[target];iy=tv[target];rru=ur[target];rrv=vr[target]
        for k,j,sigma2,coef in specs:
            sigma=np.sqrt(sigma2/2);den=gaussian_filter(valid.astype(float),sigma,truncate=5);field=gaussian_filter(raw,sigma,truncate=5)/np.maximum(den,1e-30);values=field[iy,ix];available[target]=np.minimum(available[target],2*den[iy,ix])
            if k==0:Z[target]+=coef*values
            else:
                T[k-1,target]+=coef*values;Q[k-1,target]+=coef*map_coordinates(field,[rrv,rru],order=3,mode='nearest',prefilter=True);available[target]=np.minimum(available[target],2*map_coordinates(den,[rrv,rru],order=1,mode='nearest',prefilter=False))
    Z/=1-P12;T/=1-P12;Q/=1-P12;selection &= available>=.995;ids=np.floor(y/step).astype(int)*nc+np.floor(x/step).astype(int);groups=[]
    for p in [0,1]:
        use=selection&(target_parity==p);cnt=np.bincount(ids[use],minlength=nc*nc);cells=np.flatnonzero(cnt>=3);count=cnt[cells];value={};arrays=[('g',Z),('raw_g',n['g']),('distance',distance)]+[(f't{k+1}',T[k]) for k in range(5)]+[(f'q{k+1}',Q[k]) for k in range(5)]
        for key,array in arrays:value[key]=np.bincount(ids[use],weights=array[use],minlength=nc*nc)[cells]/count
        vm=float(np.median(n['variance'][use]))/(1-P12)**2;value['weight_variance']=vm/count;value['cell']=cells;value['count']=count;value['target_green_parity']=np.full(len(cells),p);value['cell_x']=(cells%nc+.5)*step;value['cell_y']=(cells//nc+.5)*step;value['radius']=np.hypot(value['cell_x']-CX,value['cell_y']-CY);value['angle']=np.arctan2(value['cell_y']-CY,value['cell_x']-CX)%(2*np.pi);groups.append(value)
    values={key:np.concatenate([r[key] for r in groups]) for key in groups[0]};values['t']=values['t1'];values['q']=values['q1'];np.savez_compressed(OUT/f'D1_cells_{stem}.npz',**values);r=meta[stem];rows.append(dict(**{k:r[k] for k in ['stem','role','epoch','time_C2','maximum_abs_observed_G']},rows=len(values['g']),unique_cells=len(np.unique(values['cell'])),native_samples=int(selection.sum()),seconds=time.time()-start));save('D1_inputs.json',dict(method=__doc__,frames=rows));print(stem,'separate green rows',len(values['g']),round(time.time()-start,2),'seconds',flush=True)
print('DONE',len(rows),flush=True)
