"""Solar registration reference uses only short training exposures.
All sixteen short targets and all long targets are excluded from the template.
"""
from geometry_common import *
import cv2,time
from scipy.ndimage import gaussian_filter
frames=json.loads((PREV/'D2_training_sources.json').read_text())['frames'];inventory={r['stem']:r for r in json.loads((ROOT/'output/v45_earthshine_20260910/4-rebuts/B1_inputs.json').read_text())['frames']};yy,xx=np.mgrid[:N,:N].astype(np.float32);rr=np.hypot(xx-CX,yy-CY);theta=np.arctan2(yy-CY,xx-CX)%(2*np.pi);edge=np.load(ROOT/'research/tools/v44_earthshine_20260910/cau/vixen_optical_edge.npy');d=rr-np.interp(theta,np.arange(len(edge))*2*np.pi/len(edge),edge,period=2*np.pi);num=np.zeros((N,N));den=num.copy();included=[]
save('PLAN.json',dict(hypothesis='Residual bright-rim discrepancies reflect a mismatch of lunar and solar references, tested separately from outer-corona gain',frozen_wide_p=P_WIDE,calibration_short=CAL,heldout_short=TEST,long_targets=LONG,solar_reference='Only non-target Vixen exposures<=1/15s; originals unchanged',solar_fit='Observed outer corona470-650px, full-field2px smoothing before aperture; translation,gain,offset; check angular halves',lunar_fit='Native pixel aperture, fixed broad mixture; core profiles only r>=450px to leave435-449 disjoint; fit per-sector phase then rigid centre and mean radial offset',reference_test='Calibrate lunar-minus-solar reference difference onCAL and predictTEST phases; do not copy per-angle fitted contours into a PSB',limits=['Registration metadata only; no source geometry correction promoted','Targets share inherited calibration and earlier diagnostic history; not independent of the entire project','Do not infer a censored maximum is the physical limb']))
for r in frames:
    if r['stem'] in CAL+TEST or r['exp']>1/15+1e-8:continue
    stem=r['stem'];z=np.load(SRC/f'A0_quincunx_{stem}.npz');valid=np.isfinite(z['g'])&np.isfinite(z['variance'])&(z['q']>0)&(z['variance']>0);vden=gaussian_filter(valid.astype(float),4);variance=gaussian_filter(np.where(valid,z['variance'],0).astype(float),4)/np.maximum(vden,1e-30);w=np.where(valid,z['q']/np.maximum(variance*14.826313721285086,1e-30),0);selected=valid&(d>3.5);center=r['solar_center'];mx=xx+np.float32(center[0]-CX);my=yy+np.float32(center[1]-CY);support=cv2.remap(selected.astype(np.float32),mx,my,cv2.INTER_LINEAR);g=cv2.remap(np.where(valid,z['g'],0).astype(np.float32),mx,my,cv2.INTER_LINEAR);ww=cv2.remap((w*selected).astype(np.float32),mx,my,cv2.INTER_LINEAR);ww*=support>=1-1e-6;num+=g*ww;den+=ww;included.append(stem)
valid=den>0;field=np.where(valid,num/np.maximum(den,1e-30),0);mass=gaussian_filter(valid.astype(float),2,truncate=5);smoothed=gaussian_filter(field,2,truncate=5)/np.maximum(mass,1e-30);np.savez_compressed(OUT/'A0_solar_reference.npz',radiance=field,weight=den,valid=valid,smoothed=smoothed,mass=mass);save('A0_solar_reference.json',dict(method=__doc__,included=included,excluded=CAL+TEST+LONG,frames=frames));print('SOLAR REFERENCE',len(included),'shorts',flush=True)
