var root='/Users/USUARI/Downloads/Eclipse 2026/output/v61_interiors_limbe_20260913/';var old=app.displayDialogs,own=[];var target=null;
function log(s){var f=new File(root+'D3_smart_rigid.log');f.open('a');f.writeln(s);f.close();}
function corners(l){var r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);var q=executeActionGet(r).getObjectValue(stringIDToTypeID('smartObjectMore')).getList(stringIDToTypeID('transform'));var a=[];for(var i=0;i<q.count;i++)a.push(q.getDouble(i));return a;}
function exp(d,n,crop){var f=new File(root+n+'.tif');if(f.exists)throw new Error('no-clobber');var t=d.duplicate('V61_QA_'+n,true);own.push(t);if(crop)t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
try{app.displayDialogs=DialogModes.NO;var d=app.open(new File(root+'V61_work.psb'));target=d;var g=d.layerSets.getByName('Interiors 06–12 · encaix original V57');var dup=g.duplicate();dup.visible=true;d.activeLayer=dup;executeAction(stringIDToTypeID('newPlacedLayer'),undefined,DialogModes.NO);var l=d.activeLayer;l.name='Interiors 06–12 · alineades amb la base · V61';var pre=corners(l);log('BEFORE '+pre.join(','));var deg=0.14123717735844263,dx=-0.15087452179526661,dy=-0.43907973751130386,cx=5361.768111973117,cy=3775.747534140857,th=deg*Math.PI/180,cs=Math.cos(th),sn=Math.sin(th),expected=[];
for(var i=0;i<pre.length;i+=2){var x=pre[i]-cx,y=pre[i+1]-cy;expected.push(cx+cs*x-sn*y+dx);expected.push(cy+sn*x+cs*y+dy);}
l.rotate(deg,AnchorPosition.MIDDLECENTER);var mid=corners(l),tx=0,ty=0;for(var i=0;i<mid.length;i+=2){tx+=expected[i]-mid[i];ty+=expected[i+1]-mid[i+1];}tx/=4;ty/=4;l.translate(UnitValue(tx,'px'),UnitValue(ty,'px'));var post=corners(l),err=0;for(var i=0;i<post.length;i++)err=Math.max(err,Math.abs(post[i]-expected[i]));log('AFTER '+post.join(','));log('EXPECTED '+expected.join(','));log('MAX_CORNER_ERROR '+err);if(err>.01)throw new Error('Transform does not match measured matrix');
var vis=[];for(var i=0;i<d.layers.length;i++)vis.push(d.layers[i].visible);for(var i=0;i<d.layers.length;i++)d.layers[i].visible=false;l.visible=true;exp(d,'V61_aligned_interiors',true);
for(var i=0;i<d.layers.length;i++)d.layers[i].visible=vis[i];l.visible=false;g.visible=false;g.name='Interiors 06–12 · referència original V57';app.refresh();exp(d,'V61_smart_default',false);d.activeLayer=l;log('READY_FOR_SAVE_AS '+d.name+' '+d.layers.length+' top levels; original group preserved and smart object embedded');
}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}app.displayDialogs=old;}'V61_NATIVE_SMART_OBJECT_READY';
