from common61 import *
import datetime,os
claim();pub=json.loads((O/'E0_publish.json').read_text());qa=json.loads((O/'D5_final_integrity.json').read_text());rb=json.loads((O/'E2_final_readback.json').read_text());assert qa['PASS'] and rb['PASS'];opened=(O/'E1_final_open.log').read_text();assert 'saved=true' in opened and 'FINAL_OPEN_COMPLETE' in opened
now=datetime.datetime.now(datetime.timezone.utc).isoformat();handoff=R/'.coordination/HANDOFF_2026-09-13_CODEX_CAPES_TOTALS_V61.md';report=O/'RESULTAT.md';manifest=T/'delivery_manifest.json';IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');gate=(O/'D6_photoshop_gate.txt').read_text().strip();reader=(O/'D6_second_reader.txt').read_text().strip()
body=(T/'RESULTAT_template.md').read_text()
for k,v in {'PRODUCT':pub['path'],'SHA':pub['sha256'],'BYTES':str(pub['bytes']),'GATE':gate,'READER':reader,'READBACK':str(rb['max_DN16'])}.items():body=body.replace('@'+k+'@',v)
for p in [report,handoff]:assert not p.exists();p.write_text(body)
m={**pub,'canvas':[10551,7506],'depth':16,'profile':'Adobe RGB (1998)','report':str(report),'handoff':str(handoff),'manifest':str(manifest),'qa':str(O/'D5_final_integrity.json'),'readback':rb,'open_document':opened,'artifact_free':False,'status':'V61_ALIGNMENT_DELIVERED_BLUE_LIMB_PENDING','top_level_items':27,'restored_pixel_layers':32,'embedded_editable_interiors':7,'rigid_transform':json.loads((O/'C2_common_rigid.json').read_text()),'reference_native_match_outside_opaque_moon_DN16':0,'protected_components_retained':10,'presentation':'Aligned smart object and original reference group hidden, above filters and below Moon; no additional common blend mask applied','limits':['Blue limb not fully corrected','Common blend of interiors pending user choice','No new astronomical resolution or independent absolute limb recovery claim'],'preview':str(O/'vistes/V61_default.png')};assert not manifest.exists();manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
prefix=f'> **13-09-2026 · Capes Totals V61: interiors restaurades i alineades; blau pendent.** V60 desada per Pere amb32capes preservada (SHA48a1f0b3…). Retorn dels7originals06–12 deV57; només retirada la taca antiga de màscara11 dins la Lluna opaca. Compost07–12 nadiu coincideix0DN16 ambVista_V57_correcte fora del disc opac. Objecte intel·ligent amb les7capes editables, gir COMÚ+0,1412371774° i desplaçament(−0,15087452;−0,43907974)px al centre solar; escala1. Superior reservada0,788→0,860;10estructures retingudes; originals directes també conservats. Objecte alineat i grup de referència ocults, preparats damunt dels filtres; mescla pendent de Pere. Sis màscaresNRGF/RHEF amb transparència de base aplicada una sola vegada; RGBdelsfiltres/base/Llunai geometries exactes. Això NO resol tot el filet blau.192comprovacionsdecanals; PhotoshopOBRE26capesd’art+1grup; readback{rb["max_DN16"]}DN16. Producte `{pub["path"]}`, SHA `{pub["sha256"]}`. Represa `{handoff}`; informe `{report}`. Cap absència global d’artefactes declarada. Les entrades següents són història.\n\n'
history={r['path']:r['after_sha256'] for r in json.loads((R/'output/v60_marques_v59_20260913/E3_authorities.json').read_text())['rows']};receipts=[]
for i,p in enumerate([R/'AGENTS.md',R/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md']):
 old=p.read_bytes();assert hashlib.sha256(old).hexdigest()==history[str(p)],p;snap=O/'receipts'/f'E3_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(old);tmp=p.with_name(p.name+'.V61.tmp');assert not tmp.exists();tmp.write_bytes(prefix.encode()+old);assert p.read_bytes()==old;os.replace(tmp,p);receipts.append({'path':str(p),'snapshot':str(snap),'before_sha256':hashlib.sha256(old).hexdigest(),'after_sha256':sha(p),'old_content_exact_suffix':p.read_bytes().endswith(old)})
p=IA/'ACTIVE.json';old=p.read_bytes();assert hashlib.sha256(old).hexdigest()==history[str(p)];snap=O/'receipts/E3_before_ACTIVE.json';assert not snap.exists();snap.write_bytes(old);a=json.loads(old);earth=json.dumps(a['current_earthshine_product'],sort_keys=True);a['previous_general_product_V60']=a['current_product'];a['current_product']=m;a['updated']=now;a['phase']='post-eclipse-general-V61-interiors-aligned-blue-limb-pending';a['formal_worktree_handoff']=str(handoff);a['paths']['current_technical_editable']=pub['path'];a['paths']['current_delivery_manifest']=str(manifest);a['paths']['current_visual_output']=str(O/'vistes');a['general_integration_task']={'status':'V61_ALIGNMENT_DELIVERED_BLUE_LIMB_PENDING','handoff':str(handoff),'report':str(report),'pending':'Blue limb and user choice of common blend for the aligned interiors'};assert json.dumps(a['current_earthshine_product'],sort_keys=True)==earth;tmp=p.with_name(p.name+'.V61.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==old;os.replace(tmp,p);receipts.append({'path':str(p),'snapshot':str(snap),'before_sha256':hashlib.sha256(old).hexdigest(),'after_sha256':sha(p)})
save('E3_authorities.json',{'time':now,'rows':receipts,'CLAUDE_STATUS_untouched':True,'independent_earthshine_authority_unchanged':True})
with (R/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f'\n## {now} · V61 ALIGNMENT DELIVERED · CLAIM HELD\nV61 restauració06–12, referènciaV57nativa0DNforaLlunaopaca, objecteintel·ligenteditable ambgircomú0,1412371774graus i escala1.10estructures retingudes,192canals comprovats,readback{rb["max_DN16"]}DN16. Sis màscares amb transparència única; blau NO resolt completament. Objectealineat i grupreferència ocults, sense màscara de mescla nova; pregunta de preferència pendent. Producte {pub["path"]}. Handoff {handoff}.\n')
print('DOCUMENTED',handoff)
