"""Promote V56 pointers with snapshots and compare-before-write preservation."""
from common import *
import os
claim();pub=json.loads((OUT/'E4_publish.json').read_text());q=json.loads((OUT/'E3_readback.json').read_text());docs=json.loads((OUT/'F1_documentation.json').read_text());assert q['PASS'] and sha(pub['path'])==pub['sha256'];freeze=json.loads((OUT/'A0_freeze.json').read_text());prior=json.loads((OLD/'F2_authorities.json').read_text())
for a in freeze['authorities']:
 if a['path'].endswith(('AGENTS.md','CLAUDE.md','CLAUDE_STATUS.md','ACTIVE.json')):assert sha(a['path'])==a['sha256'],a['path']
for a in prior['rows']:assert sha(a['path'])==a['after_sha256'],a['path']
IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');now=datetime.datetime.now(datetime.timezone.utc).isoformat();prefix=f"> **13-09-2026 · Earthshine V56 lliurada: tres vies provades.** Fusió Fourier per nitidesa i reconstrucció CFA natives assajades, sense guany suficient; no promogudes. Vermell: patró repetible de 67 Vixen i confiança R/G per reforçar la textura fotogràfica existent de 24–40 px, aproximadament +2,4–2,9% dins r435; no percentatge de resolució ni nova informació. Productor R4 → R5 + R8. Retenció 93/93; injeccions condicionals i control acumulat passen. Photoshop 26 capes, readback màxim {q['max_full_DN16']} DN16. V55/V54/V53 i 88 RAW exactes; 25 capes, alfa/màscares/geometria preservades. R1 vermell directe rebutjat per 149 píxels fora de rang. Detectors absoluts antics del limbe continuen qualificats com a fallits també a les versions anteriors; no redefinits. Producte `{pub['path']}`, SHA `{pub['sha256']}`. Represa `{docs['handoff']}`; informe `{docs['report']}`. Aquesta entrada és vigent; les següents conserven la història. Judici visual de Pere, nova resolució, detall de tot l'últim limbe i DHS no declarats resolts.\n\n"
paths=[ROOT/'AGENTS.md',ROOT/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md'];rows=[]
for i,p in enumerate(paths):
 assert not p.is_symlink();old=p.read_bytes();snap=OUT/'receipts'/f'F2_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(old);new=prefix.encode()+old;tmp=p.with_name(p.name+'.V56.tmp');assert not tmp.exists();tmp.write_bytes(new);assert p.read_bytes()==old;os.replace(tmp,p);assert p.read_bytes().endswith(old);rows.append(dict(path=str(p),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=sha(p),snapshot=str(snap),old_content_exact_suffix=True))
p=IA/'ACTIVE.json';old=p.read_bytes();snap=OUT/'receipts/F2_before_ACTIVE.json';assert not snap.exists();snap.write_bytes(old);a=json.loads(old);a['previous_earthshine_product_V55']=a['current_earthshine_product'];a['historical_earthshine_task_preV56']=a['earthshine_task'];a['updated']=now;a['phase']='post-eclipse-earthshine-V56-three-routes-delivered-DHS-open';a['formal_worktree_handoff']=docs['handoff'];a['current_earthshine_product']=dict(path=pub['path'],sha256=pub['sha256'],bytes=pub['bytes'],version=56,layers=26,canvas=[10551,7506],depth=16,source=str(V55),PASS='File/layer preservation; red-source corroboration; conditional differential injections; 93/93 photographic retention; native Photoshop. No new spatial resolution or absolute limb-detector PASS.',report=docs['report'],handoff=docs['handoff'],user_feedback='Pere visual review of V56 pending; previous V55 positively received',open_goal='No full last-limb detail or DHS equivalence claim; current three-route work delivered')
a['earthshine_task']=dict(status='AUTHORIZED_THREE_ROUTES_EXECUTED; QUALIFIED_V56_DELIVERED; PERE_VISUAL_REVIEW_PENDING',completed='Fourier sharpness fusion, additional red and native CFA reconstruction tested. Red detector/colour corroboration supports small 24-40px photographic promotion while preserving V55 and 93 claims.',next_action='Review V56 at same brightness as V55. Further gain requires a new source/optical constraint or a better causal separation of scattered solar light. Preserve all negative variants and judge definitions.',handoff=docs['handoff'])
a['earthshine_v56_validation']=dict(source_judge=str(OUT/'R7_red_external.json'),source_injection=str(OUT/'R9_repeatable_injections.json'),photographic_injection=str(OUT/'R11_photo_injections.json'),photographic_retention=str(OUT/'R8_exact_retention.json'),injection_conditional=True,photographic_independence=False,retained_claims=93,readback_max_DN16=q['max_full_DN16'],new_mask=False,new_resolution_claim=False,limb_profiles=str(OUT/'R10_profiles.json'),native_visual_review=str(OUT/'E3_visual_review.json'),negative_results=docs['report']);a['paths']['current_earthshine_editable']=pub['path'];a['paths']['current_earthshine_manifest']=docs['manifest'];a['paths']['current_earthshine_visual_output']=str(OUT)
tmp=p.with_name(p.name+'.V56.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==old;os.replace(tmp,p);rows.append(dict(path=str(p),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=sha(p),snapshot=str(snap)))
with (ROOT/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f"\n\n## {now} · EARTHSHINE V56 LLIURADA · CLAIM ENCARA HELD\n\nTres vies provades. V56 SHA {pub['sha256']}; R4 → R5 + R8, detall fotogràfic 24–40 +2,4–2,9% dins r435. Retenció 93/93; 360 injeccions de font, 6 controls de detector i 288+48 de transport passen, amb límit condicional explícit. Photoshop 26 capes/readback {q['max_full_DN16']} DN16; inspecció nativa al llenç i 1:1. V55/V54/V53 i 88 RAW exactes, 25 capes/alfa/màscares/geometria exactes. Fourier i CFA natiu negatius, R1 vermell directe clipeja i no es publica. No nova resolució ni recuperació de tot l'últim limbe/DHS. Informe {docs['report']}; handoff {docs['handoff']}. Autoritats actualitzades amb contingut anterior íntegre; alliberament pendent de verificació final i zero workers.\n")
save('F2_authorities.json',dict(time=now,rows=rows,CLAUDE_STATUS_untouched=True));print('AUTHORITIES UPDATED',flush=True)
