"""Photographic colour increment weighted by measured uncertainty at source.
R2 counted smooth frame colour offsets as detail uncertainty. Separate a six-term polynomial nuisance from temporal variance, trained only even sectors60-435; preserve the common source contrast.
Use the actual covariance between V55 green and paired colour difference,
and the larger of conditional photon variance or temporal mean variance.
Weights follow observed radiometric validity/uncertainty, no geometric taper.
"""
from common import *
from scipy.ndimage import gaussian_filter
claim();model=json.loads((OLD/'A5_color_model.json').read_text());a=model['slopes']['R'];o=model['offsets']['R'];z0=np.load(OUT/'arrays/R0_paired_red.npz');contrast=z0['contrast'];den=z0['weight'];physical=np.load(OUT/'arrays/A1_sources.npz')['physical'];fs=[m for m in frames() if m['tren']=='vixen'];des=json.loads((OLD/'B3_G67_robust_hetero_full_safe_design.json').read_text());sh=des['shifts'];Dg=np.load(OLD/'arrays/B11_repeatable_all.npz')['detector'];Dr=np.load(OLD/'arrays/B3_R67_robust_hetero_full_safe_all.npz')['detector'];WG=np.load(OUT/'arrays/W_frames.npy',mmap_mode='r');dg=np.load(OUT/'arrays/A1_sources.npz')['weight'];cov=np.zeros((N,N));vp=cov.copy();sum2=cov.copy();scatter=cov.copy()
save('R3_protocol.json',dict(method=__doc__,formula='f=Cov(Gbase,Gpaired)/max(Var(Rpaired-Gpaired),temporal_variance_of_mean), clipped only to probability interval[0,1]. Empirical second moments smoothed32 using valid support. Candidate=Gbase+f*(Rpaired-Gpaired).',temporal='Weighted unbiased sample variance divided by effective count. Photon floor. If fewer than two effective observations, no measured temporal qualification and f=0; no artificial valid pixels.',training='Native Vixen data and frozen calibration only; no Sony, LROC, photographic clipping locations or painted masks.',limits=['Shared detector/calibration errors not captured by temporal variance','Red detector repeatability must qualify separately','Zero weight for unqualified temporal variance is a radiometric statistical criterion, not a crop or mask change']))
r,t=geometry();yy,xx=np.mgrid[:N,:N];xx=(xx-CX)/500;yy=(yy-CY)/500;Q=np.stack([np.ones_like(xx),xx,yy,xx*xx,xx*yy,yy*yy],-1);training=(r>=60)&(r<435)&((t//(np.pi/6)).astype(int)%2==0);fits=[]
for i,m in enumerate(fs):
 z=np.load(m['file']);qg=(z['G1_q']+z['G2_q'])/2;g=(np.nan_to_num(z['G1'])*z['G1_q']+np.nan_to_num(z['G2'])*z['G2_q'])/np.maximum(2*qg,1e-30);vg=(np.nan_to_num(z['G1_var'])*z['G1_q']**2+np.nan_to_num(z['G2_var'])*z['G2_q']**2)/np.maximum((2*qg)**2,1e-30);vr=z['R_var']/a**2;rr=z['R']/a+o;qr=z['R_q'];ok=physical&(qg>0)&(qr>0)&np.isfinite(rr)&np.isfinite(vr)&np.isfinite(vg);v=gaussian_filter(np.where(ok,vr+vg,0),4)/np.maximum(gaussian_filter(ok.astype(float),4),1e-30);w=np.where(ok,np.minimum(qg,qr)/np.maximum(v,1e-12),0);c=rr-pull(Dr,sh[i])/a-g+pull(Dg,sh[i]);pn=w/np.maximum(den,1e-30);gn=WG[i]/np.maximum(dg,1e-30);cov+=pn*gn*vg;vp+=pn*pn*np.nan_to_num(vr+vg);sum2+=pn*pn;residual=np.nan_to_num(c-contrast);tr=training&ok;cf=np.linalg.lstsq(Q[tr]*np.sqrt(w[tr,None]),residual[tr]*np.sqrt(w[tr]),rcond=None)[0];e=residual-Q@cf;scatter+=pn*e**2;fits.append(dict(stem=m['stem'],nuisance=cf))
 if (i+1)%15==0:print('RED VAR',i+1,flush=True)
valid=(den>0)&physical;neff=np.divide(1,sum2,out=np.zeros_like(sum2),where=sum2>0);unbiased=np.divide(scatter,1-sum2,out=np.full_like(scatter,np.nan),where=sum2<1-1e-6);temporal=unbiased*sum2
def smooth(a):return gaussian_filter(np.where(valid,np.nan_to_num(a),0),32)/np.maximum(gaussian_filter(valid.astype(float),32),1e-30)
formal=smooth(vp);emp=smooth(temporal);cc=smooth(cov);fraction=np.clip(np.divide(cc,np.maximum(formal,emp),out=np.zeros_like(cc),where=np.maximum(formal,emp)>0),0,1);fraction[~valid|(neff<1.01)]=0;increment=fraction*np.nan_to_num(contrast);base=np.load(OLD/'arrays/B11_repeatable_all.npz')['source'];np.savez_compressed(OUT/'arrays/R3_red_source.npz',baseline=base,candidate=base+increment,contrast=increment,fraction=fraction,formal_variance=formal,temporal_variance=emp,covariance=cc,effective_count=neff)
r,t=geometry();stats=[]
for lo,hi in [(60,250),(250,350),(350,410),(410,435),(435,449),(449,458)]:
 m=valid&(r>=lo)&(r<hi);stats.append(dict(radius=[lo,hi],fraction_percentiles=np.percentile(fraction[m],[0,10,50,90,100]),increment_percentiles=np.percentile(increment[m],[0,10,50,90,100]),effective_count_percentiles=np.percentile(neff[m],[0,10,50,90,100])))
save('R3_red_covariance.json',dict(rows=stats,nuisance_fits=fits,source_sha256=sha(OUT/'arrays/R3_red_source.npz'),common_scene_invariance='R and G receive same latent addition after scale; contrast and temporal variance unchanged, Gbase carries it. Conditional on frozen covariance/calibration, requires actual injection verification.'));print('RED COVARIANCE',stats,flush=True)
