"""Small photographic promotion of already corroborated24-40px detail.
Direct red mixing fails the limb; repeated red detector removal alone is tiny.
Use newly calibrated/cleaned R-G agreement as conservative confidence for the
existing pre-CameraRaw photographic source. No external pixels, no replacement
by a noisier red image, no new lunar feature or resolution claim.
"""
from common import *
from scipy.ndimage import map_coordinates,gaussian_filter
claim();r,t=geometry();alpha=np.load(OLD54/'arrays/V53_lunar_alpha.npy');mask=np.load(OLD54/'arrays/V53_lunar_mask.npy');visible=(alpha>0)&(mask>0);domain=float(r[visible].max());nt=2880;rr=np.arange(0,domain+2,.5);th=np.arange(nt)*2*np.pi/nt;co=[CY+rr[:,None]*np.sin(th),CX+rr[:,None]*np.cos(th)];freq=np.fft.rfftfreq(nt)[None,:]*nt/(2*np.pi*np.maximum(rr[:,None],.25));u=np.clip((freq-1/48)/(1/40-1/48),0,1);v=np.clip((freq-1/24)/(1/20-1/24),0,1);H=(.5-.5*np.cos(np.pi*u))*(.5+.5*np.cos(np.pi*v));strength=.04
save('R8_protocol.json',dict(method=__doc__,band=[24,40],skirts=[20,48],strength=strength,confidence='positive smoothed Rclean*Gclean cross power/(cross power+(Rclean-Gclean)^2/4), both scaled by frozenA5. Smooth variance sigma(32 radial samples,nt/36 angular samples). Shared calibration limit; exact Sony source and93 photographic claims stay judges.',transfer='Single beta from saved V55 versus original preCR24-40 band, even30degree sectors r100-435. Fixed saved appearance, no CameraRaw replay. Preserve additive R5 red detector correction.',support='Use only inherited V53 layer mask as in qualifiedV54 source-band method. No new contour, crop or spatial selection by marks.',gates='No clipping; all93 inherited photographic claims; conditional differential blind injection0.90-1.10 including oldV54 overlap; exact limb/anisotropy comparisons; source cross nulls unchanged; real Photoshop before PSB.',claim='Photographic contrast promotion of existing corroborated texture, not4percent new information or resolution.'))
def pol(a):return map_coordinates(a,co,order=3,mode='nearest')
def band(a):return np.fft.irfft(np.fft.rfft(a,axis=1)*H,n=nt,axis=1)
def cart(p):
 pad=np.c_[p[:,-2:],p,p[:,:2]];return map_coordinates(pad,[np.minimum(r/.5,len(rr)-1),t*nt/(2*np.pi)+2],order=3,mode='nearest')
z=np.load(OUT/'arrays/R5_sources.npz');R=band(pol(z['red_repeatable']));G=band(pol(z['Gclean']));smooth=lambda a:gaussian_filter(a,(32,nt/36),mode=('nearest','wrap'));cross=np.maximum(smooth(R*G),0);disagreement=smooth((R-G)**2/4);confidence=cross/np.maximum(cross+disagreement,1e-30);pre=np.load(ROOT/'output/earthshine_native_psf_20260911/full_sampler_delta/C0_pre_camera_raw_rgb.npy');old=np.load(OLD/'arrays/D10_candidate_rgb.npy').astype(np.int32);P=pol(pre.mean(-1));Q=pol(old.mean(-1));A=band(P);B=band(Q);train=np.broadcast_to((rr[:,None]>=100)&(rr[:,None]<435),(len(rr),nt))&((np.arange(nt)[None,:]//240)%2==0);hold=np.broadcast_to((rr[:,None]>=100)&(rr[:,None]<435),(len(rr),nt))&~train;beta=float(A[train]@B[train]/(A[train]@A[train]));assert 0<beta<2;pm=np.clip(pol(mask/65535),0,1);banddelta=cart(strength*confidence*A*pm);increment=np.rint(beta*banddelta).astype(np.int32);increment[~visible]=0;detdelta=np.load(OUT/'arrays/R5_delta.npy');delta=detdelta+increment;new=old+delta[...,None];clip=(new.min(-1)<0)|(new.max(-1)>65535)
np.savez_compressed(OUT/'arrays/R8_operator.npz',confidence=confidence,mask_polar=pm,H=H,beta=beta,strength=strength,rr=rr,band_delta=banddelta,detector_delta=detdelta);np.savez_compressed(OUT/'arrays/R8_photo_unclipped.npz',candidate=new,delta=delta)
if not clip.any():np.save(OUT/'arrays/R8_candidate_rgb.npy',new.astype(np.uint16));np.save(OUT/'arrays/R8_delta.npy',delta)
rows=[]
for lo,hi in [(100,300),(300,370),(370,435),(435,449)]:
 sel=np.broadcast_to((rr[:,None]>=lo)&(rr[:,None]<hi),confidence.shape);rows.append(dict(radius=[lo,hi],confidence_percentiles=np.percentile(confidence[sel],[0,10,50,90,100])))
save('R8_photo_band.json',dict(beta=beta,heldout_response_r=corr(A,B,hold),clipped_pixels=int(clip.sum()),minmax=[int(new.min()),int(new.max())],delta_percentiles=np.percentile(delta[visible],[0,1,10,50,90,99,100]),rows=rows,status='Photographic candidate only; exact retention/injection/limb/native verification pending.'));print('RED SUPPORTED BAND',beta,'clip',clip.sum(),'delta',np.percentile(delta[visible],[0,1,50,99,100]),flush=True)
