"""Training-only HDR sources for broad-predictor completion of censored frames.
Solar registration applies only to an auxiliary coronal radiance field. The
original lunar source pixels stay untouched. Reserved RAWs do not train either
the solar field or the lunar nuisance field.
"""
from scatter_common import *
import cv2,time
from scipy.ndimage import gaussian_filter
plan=json.loads((OUT/'PLAN.json').read_text());reserved=set(plan['reserved_stems']);inventory=json.loads((ROOT/'output/v45_earthshine_20260910/4-rebuts/B1_inputs.json').read_text())['frames'];fr=[r for r in inventory if r['tren']=='vixen'];pos=json.loads(Path('/Users/USUARI/Desktop/Eclipse determinista/1-RUNS/019_VIXEN_CIENCIA_20260827T212404Z/4-rebuts/F1.3_registre.json').read_text())['fotogrames'];J=np.load(SRC/'A0_native_samples_572A2976.npz')['native_to_world'];yy,xx=np.mgrid[:N,:N].astype(np.float32);radius=np.hypot(xx-CX,yy-CY);theta=np.arctan2(yy-CY,xx-CX)%(2*np.pi);edge=np.load(ROOT/'research/tools/v44_earthshine_20260910/cau/vixen_optical_edge.npy');distance=radius-np.interp(theta,np.arange(len(edge))*2*np.pi/len(edge),edge,period=2*np.pi);solar_n=np.zeros((N,N));solar_d=solar_n.copy();moon_n=solar_n.copy();moon_d=solar_n.copy();rows=[]
save('D0_completion_plan.json',dict(method=__doc__,excluded_RAW_stems=sorted(reserved),corona_selection='Observed source pixels at least3.5px outside measured common lunar contour; valid four-contributor solar remap; no values from hidden solar scene',lunar_selection='Observed valid pixels within measured contour+2px, all nonreserved exposures weighted by frozen noise factors',weights='Conditional variance smoothed4px for precision only; observed radiance never normalized by brightness during remap',solar_origin=[CX,CY],completion_usage='Only to predict broad scatter where target is censored; never treated as measured lunar texture',validation='Artificial masks at1000,5000,20000G on reserved real short exposures; compare broad correction with their actually observed field before any source promotion',completion_gate='For every qualified reserved epoch/radius/mask combination: median absolute correction error<=5G and95th percentile<=25G, with at least80percent support of valid reference cells. Native solar/lunar source pixels remain immutable.'))
for r in fr:
    p=pos[r['nom']];center=np.array([CX,CY])-J@np.array([p['lluna_dx'],p['lluna_dy']])+np.array(r['native']['shift']);rows.append(dict(stem=r['stem'],exp=r['exp'],solar_center=center.tolist(),training=r['stem'] not in reserved,shift=r['native']['shift']))
    if r['stem'] in reserved:continue
    start=time.time();z=np.load(SRC/f'A0_quincunx_{r["stem"]}.npz');g=z['g'];valid=np.isfinite(g)&np.isfinite(z['variance'])&(z['q']>0)&(z['variance']>0);den=gaussian_filter(valid.astype(float),4);variance=gaussian_filter(np.where(valid,z['variance'],0).astype(float),4)/np.maximum(den,1e-30);alpha=35.54865158040903 if r['exp']>=8 else 32.940404784734135 if r['exp']>=2 else 14.826313721285086;w=np.where(valid,z['q']/np.maximum(variance*alpha,1e-30),0);inside=valid&(distance<2);moon_n+=np.where(inside,g,0)*w;moon_d+=w*inside
    sv=valid&(distance>3.5);mx=xx+np.float32(center[0]-CX);my=yy+np.float32(center[1]-CY);coverage=cv2.remap(sv.astype(np.float32),mx,my,cv2.INTER_LINEAR,borderMode=cv2.BORDER_CONSTANT);mapped=cv2.remap(np.where(valid,g,0).astype(np.float32),mx,my,cv2.INTER_LINEAR,borderMode=cv2.BORDER_CONSTANT);ww=cv2.remap((w*sv).astype(np.float32),mx,my,cv2.INTER_LINEAR,borderMode=cv2.BORDER_CONSTANT);ww*=coverage>=1-1e-6;solar_n+=mapped*ww;solar_d+=ww
    print(r['stem'],'training source',round(time.time()-start,2),flush=True)
np.savez_compressed(OUT/'D0_completion_sources.npz',solar=np.where(solar_d>0,solar_n/np.maximum(solar_d,1e-30),np.nan),solar_weight=solar_d,lunar=np.where(moon_d>0,moon_n/np.maximum(moon_d,1e-30),np.nan),lunar_weight=moon_d,source_lunar_distance=distance);save('D0_completion_sources.json',dict(method=__doc__,frames=rows,training_frames=sum(r['training'] for r in rows),excluded_frames=len(reserved),solar_valid=int((solar_d>0).sum()),lunar_valid=int((moon_d>0).sum())))
print('DONE',sum(r['training'] for r in rows),'training sources',flush=True)
