from pathlib import Path
R=Path('/Users/USUARI/Downloads/Eclipse 2026');O=R/'output/earthshine_broad_lroc_20260914'
sources=[
 ('NASA Scientific Visualization Studio, CGI Moon Kit, versió original de2019; pàgina actualitzada9-01-2026.','https://svs.gsfc.nasa.gov/4720/'),
 ('LROC, WAC Hapke Normalized Mosaic: definició i geometria fotomètrica del producte.','https://data.lroc.im-ldi.com/lroc/view_rdr/WAC_HAPKE'),
 ('Qiu et al. (2003), Earthshine and the Earth’s albedo: 1. Earthshine observations and measurements of the lunar phase function.','https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2003JD003610'),
 ('Miloslav Druckmüller, TSE2026 Trigaza, producte400mm DHS. Fitxa de captura i processament.','http://www.zam.fme.vutbr.cz/~druck/eclipse/Ecl2026s/Trigaza/TSE_2026_400mm_DHS/0-info.htm'),
 ('Miloslav Druckmüller, TSE2026 Trigaza, producte530mm DHS. Fitxa de captura i processament.','http://www.zam.fme.vutbr.cz/~druck/eclipse/Ecl2026s/Trigaza/TSE_2026_530mm_DHS/0-info.htm'),
 ('Miloslav Druckmüller, TSE2026 Trigaza, producte200mm DHS. Captures compartides amb400mm.','http://www.zam.fme.vutbr.cz/~druck/eclipse/Ecl2026s/Trigaza/TSE_2026_200mm_DHS/0-info.htm'),
 ('Rebuts numèrics d’aquesta investigació: A2radis, A3models directes, A4S8, A5corba de to, A6DHS i B1ales amples.',str(O)),
 ('Fonts i diagnòstic V68: capa LROC62 exacta, història, registre de referència i sis fotogrames calibrats.',str(R/'output/v68_lroc_revisio_20260914/RESULTAT.md')),
]
pages=[
 dict(title='La taca fosca de l’earthshine',paras=[
  'La depressió ampla assenyalada a la V67 i conservada a la V68 és més intensa que a la referència LROC i que a les fotografies finals de Druckmüller. La nova comparació reforça que hi ha una distorsió de contrast per resoldre. No permet, però, determinar quina correcció de brillantor representa fidelment la superfície lunar.',
  'La investigació identifica tres elements diferents: una referència LROC que no és fotomètricament equivalent a l’earthshine; un estimador antic del vel que modifica senyals amples; i una contribució de llum dispersa que les proves temporals actuals no separen prou bé del senyal lunar.',
  '<b>No s’ha validat cap correcció nova ni s’ha creat una V69.</b> La correcció de l’error angular de S8 resulta insuficient. Retirar tot el vel recupera el problema del contorn. L’ajust d’ales òptiques amples no determina una amplitud estable. Els resultats negatius es conserven, sense modificar la fotografia per acostar-la a una referència externa.',
  'La V68, l’encaix manual, les perles, les estrelles i els documents oberts amb canvis no desats es preserven. Aquest informe qualifica la discrepància ampla; no retira les correccions de punts blancs i patró fi que sí es van verificar a la V68.'
 ],image=str(R/'output/v68_lroc_revisio_20260914/vistes/COMPARACIO_TACA_LROC.png'),caption='Comparació diagnòstica anterior: earthshine a l’esquerra i capa LROC62 exacta a la dreta. Estiraments locals declarats per inspecció; no constitueixen una comparació de radiància absoluta.',refs=[7,8]),
 dict(title='La referència LROC',paras=[
  'La capa «Compara LROC · alineada V58» deriva del TIFF de4.096×2.048 píxels i8bits per canal del CGI Moon Kit de2019. La seva metadada interna identifica l’arxiu lroc_color_poles_4k.tif. La NASA descriu aquestes textures com a productes preparats per visualització, amb gamma, balanç de blancs i rang ajustats.[1]',
  'El mosaic científic de partida està normalitzat a incidència60°, fase60° i emissió0°. El nostre codi converteix la textura codificada a gris, la projecta ortogràficament, la suavitza a2píxels i hi aplica una finestra tonal pròpia. No calcula una il·luminació de la Lluna per la Terra.[2]',
  'L’earthshine es veu en un règim pròxim a la retroreflexió. La funció de fase lunar i l’efecte d’oposició són rellevants per interpretar-ne la brillantor. Per això una textura normalitzada a60° no defineix, amb una única corba de contrast, el to correcte de tots els materials lunars en aquesta fotografia.[3]',
  'La traçabilitat local és forta: el cache de la capa deV39 coincideix amb el producte original deV22 dins d’1DN16. Les versions següents hi incorporen ancoratges geomètrics. La comparació actual utilitza la capa62 del PSB real, amb aquestes transformacions ja incorporades.',
  '<b>Conseqüència:</b> LROC és útil per localitzar estructures i detectar discrepàncies. La diferència amb LROC, per si sola, no justifica aclarir una regió fins que s’hi assembli. Tampoc justifica donar per bona la taca de la fotografia.'
 ],table=[['Element','Valor o operació'],['Font','CGI Moon Kit2019, RGB8'],['Projector','Ortogràfic; efemèride i orientació'],['To de la capa','Percentils propis i suavitzatσ2'],['Il·luminació d’earthshine','No modelada'],['Ús admissible','Referència estructural, amb límit fotomètric']],refs=[1,2,3]),
 dict(title='Comparació amb fotografies externes',paras=[
  'Les fotografies DHS de400mm i530mm permeten contrastar la discrepància amb altres captures de l’eclipsi. S’han registrat numèricament les referències, excloent la marca i una guarda de50píxels; l’encaix del projecte no s’ha mogut. La correlació de textura en sectors reservats és0,948 per400mm i0,897 per530mm.',
  'La taula mesura una banda ampla com la diferència entre dos suavitzats normalitzats al suport lunar. Només s’ajusten un guany i un offset fora de la marca. El residual s’expressa en desviacions de la banda LROC de referència: <b>no és significació estadística ni error d’albedo.</b>',
  'La depressió deV68 és més pronunciada en les dues escales. A escales encara més grans, també els DHS difereixen fortament deLROC; aquestes diferències no permeten una equivalència fotomètrica global.',
  'Les fitxes documenten208exposicions al400mm i225al530mm, amb calibració i processament fotogràfic. El producte200mm incorpora les mateixes208preses del400mm: no compta com una tercera confirmació independent. El tractament particular de la superfície lunar no queda detallat en aquestes fitxes.[4-6]'
 ],table=[['Imatge','Residualσ8-32','Residualσ16-64'],['V68','−0,461','−1,099'],['DHS400mm','−0,038','−0,203'],['DHS530mm','−0,092','−0,307']],image=str(O/'vistes/A6_DHS_band_comparison.png'),caption='Bandaσ16-64. Dalt: V68, DHS400 i DHS530. Baix: LROC, prova de sector centrat i V49 senseS8. La fila inferior mostra contrafactuals de diagnòstic, no versions aprovades.',refs=[4,5,6,7]),
 dict(title='Història del senyal i Camera Raw',paras=[
  'La zona de diagnòstic ocupa el rectangle del llenç(5228,3979)-(5401,4125), dins la capa lunar30. Als25.258píxels del rectangle, alfa i màscara són totalment opacs. La discrepància existeix en el RGB de la capa abans de barrejar-lo amb la corona: no és una ombra provocada per la màscara.',
  'L’ajust diagnòstic de la referència LROC deixa un residual de l’ordre d’1píxel. Aquesta magnitud no explica una forma d’uns150píxels. No s’ha aplicat cap transformació al projecte ni es presenta aquest resultat com una validació astromètrica absoluta.',
  'Una corba global monòtona explica gairebé exactament el pas del revelat V49 anterior al revelat dePere. S’ajusta fora de la marca i la guarda, amb sectors alterns reservats. A escala ampla, el pas des de la font anterior aCamera Raw també deixa un residu modest a la marca. Per tant, el nou ajust dePere no explica una alteració local específica.',
  'La depressió ja apareix en fonts calibrades individuals deSony iVixen. En sis preses comprovades, el camp multiplicatiuφ val1 a tota la marca. Això descarta aquest camp concret com a creador local en aquestes sis preses, però no separa el vel òptic: les fonts encara contenen llum solar dispersa.',
  'Una comparació rectangular simple confon distàncies diferents al limbe. Els assaigs amb controls de radi equivalent i amb fons radials/angulars mostren que aquest camp ample pesa molt en les correlacions. Per això no s’atribueix tota la depressió nativa a l’albedo.'
 ],table=[['Resposta global','RMS reservatDN16','Mediana a la marca'],['V49 anterior→Pere','6,04','0,00'],['PreCR→Pere, σ16','43,18','−15,02'],['PreCR→V49 anterior, σ16','20,13','−7,51']],refs=[7,8]),
 dict(title='Auditoria de l’estimador del vel',paras=[
  'S8 estima perfils radials de mediana en72sectors de5°. Pren com a nivell de cada sector una franja interior; suavitza l’excés, en propaga els màxims cap al limbe i resta el camp als tres canals. Tot això s’aplica sobre el RGB ja revelat. Un camp suau pot contenir estructures lunars amples: la suavitat no demostra que sigui només llum dispersa.',
  '<b>Error concret:</b> les medianes representen el centre de cada sector, però es van interpolar com si representessin el seu inici. La coordenada correcta és sector−0,5, amb tancament circular. La implementació d’auditoria reprodueix el canal G històric de V53 exactament a0DN16 i després prova aquesta correcció, sense moure la imatge.',
  'A la marca, corregir l’origen angular modifica el nivell entre−101,5 i+62,0DN16, amb mediana−10,8. El residual ampli davantLROC passa de−1,099 a−1,095unitats. La taca pràcticament no millora; en una banda més ampla la discrepància augmenta. No es promou aquest candidat com a solució.',
  'Les injeccions següents reestimen tot el camp; no són una prova amb pesos congelats. Un senyal gaussià ample a la marca s’amplifica aproximadament un17-20%. En altres posicions, la mateixa classe de senyal es redueix. Això prova una resposta espacial irregular deS8, sense identificar automàticament quina part de la taca real és falsa.',
  'No hi ha retall a negre: el canalG de la marca després deS8 té mínim6.712 i mediana7.428DN16. La foscor observada és relativa al contrast del revelat.'
 ],table=[['Centre / amplada','AmplitudDN16','Transferència'],['Marca; σ50','−200 / +200','1,168 /1,199'],['Marca; σ90','−200 / +200','1,145 /1,152'],['(1000,680); σ50','−200 / +200','0,557 /0,598'],['(500,440); σ50','−200 / +200','0,451 /0,428']],refs=[7]),
 dict(title='Prova física de les ales amples',paras=[
  'S’ha provat una explicació alternativa basada en la llum que es dispersa des de la corona exterior. El pilot usa21camps natius observats deVixen, amb nuclis de dispersió de64,128 i256píxels. L’ajust utilitza els cinc fotogrames d’entrenament històrics, fora de la marca i la guarda, a radis260-390.',
  'El model conserva un senyal lunar comú per cel·la i un pla de nivell per fotograma. Després d’eliminar aquests termes de confusió, queda molt poca variació que identifiqui l’amplitud de l’ala ampla. El nucli de256píxels conserva només el0,531% de la norma del predictor.',
  'La millora de l’error d’entrenament és de només0,0074%. Separant les dues èpoques, el coeficient de l’ala256 canvia de0,0877 a0,00559, amb gran incertesa condicional. El control amb la corona girada90° selecciona una contribució nul·la.',
  '<b>Resultat:</b> aquestes dades i aquest model no determinen una amplitud prou estable per restar-la de la Lluna. No s’ha demostrat que el vel ample sigui absent, ni que cap altre model el pugui identificar. La conclusió afecta aquest pilot concret.',
  'Els16fotogrames reservats s’han processat per construir predictors i comprovar-ne el suport. No s’ha executat una validació predictiva completa sobre aquests16: la prova s’ha aturat per manca d’identificabilitat. A més, el pla de centrat dels donants hereta r<350 i inclou part de la marca; l’exclusió s’aplica a l’ajust dels coeficients, no a totes les operacions prèvies. És un pilot exploratori, no un PASS extern ni una recuperació d’albedo.'
 ],table=[['Nucliσ','Norma que queda','Coeficient','Error condicional'],['64','5,52%','0','0,00453'],['128','1,99%','0','0,00692'],['256','0,531%','0,02244','0,01627']],refs=[7]),
 dict(title='Decisió i continuïtat',paras=[
  'La discrepància ampla continua oberta. La comparació ambDHS reforça que el resultat actual exagera una depressió; la cadena històrica i les injeccions mostren una contribució plausible del processament. Encara no es pot repartir de manera fiable aquesta contribució entre vel residual, resposta ampla heretada i contrast lunar real.',
  'No s’aplica cap resta òptica d’amplitud indeterminada. Tampoc s’importen píxels deLROC oDHS a la fotografia. Retirar totS8 és un contrafactual útil però recupera la gran contaminació del contorn. Centrar els sectors és una correcció de codi demostrable, però no resol la marca i no justifica una versió presentada com a curada.',
  'Una continuació útil ha de determinar el component ample amb informació independent del patró lunar comú, o proposar un productor que conservi aquest patró sota injeccions amb reestimació. Caldrà comprovar la marca reservada, altres sectors, Sony com a testimoni extern i la preservació del limbe. Repetir només controls de detall fi no respon a aquesta pregunta.',
  'La reproducció queda limitada als intermedis congelats: els scripts d’auditoria no són una reconstrucció integral des deRAW. Les fonts originals, les seves geometries i les màscares es mantenen. El candidat de sector centrat queda en un fitxer numèric de diagnòstic; no és un PSB lliurat.',
  '<b>Estat del producte:</b> V68.psb continua vigent amb la taca ampla pendent. No s’ha creat capV69 ni s’ha executat una portaPhotoshop per una versió inexistent. Les comprovacions de fitxer i de l’estat dels documents es registren separadament al rebut final.'
 ],table=[['Via provada','Decisió'],['Copiar el to deLROC','Descartada: referència no equivalent'],['Corba global dePere','No és la causa local nova'],['Centrar els sectorsS8','Error real; cura insuficient'],['Retirar totS8','Recupera contaminació del contorn'],['Ales amples temporals','Amplitud no identificada']],refs=[7,8]),
 dict(title='Fonts i reproducció',paras=[
  'Les referències externes s’han consultat el14-09-2026. Les pàgines deDHS s’han conservat com a rebutsHTML ambSHA-256. Les imatges de comparació provenen dels fitxers locals ja disponibles; cap píxel d’aquestes referències s’ha incorporat al projecte.',
  'El paquet de recerca conté el pla previ, les taulesJSON, els camps numèrics dels candidats i els scripts de reproducció. Els noms A2-A6 i B1 identifiquen els rebuts locals. La nova comprovació de fonts de la capa62 substitueix qualsevol interpretació que es basava només en el cache LROC anterior aV58.',
  'Per executar els diagnòstics des de l’arrel canònica, s’utilitza Python3.12 de l’entorn eines-ia-py312, amb NumPy, SciPy iPillow. Primer A2 iA3; després A4, que genera el candidat de sector centrat; finalment A5 iA6. B1 conserva el pilot d’identificabilitat. Aquests càlculs no obren ni modifiquen Photoshop.'
 ],sources=True,refs=[])
]
