"""Replay the known native CameraRaw recipe in the original full document.
Historical slider identity is not established. C2 applies the already frozen
global tone calibration to approximate Pere's saved photographic appearance.
"""
from photoshop_api import *
src=OUT/'C0_pre_camera_raw_full.psd';dst=OUT/'C1_camera_raw.psd';assert not dst.exists()
name='V45 font G · dos trens · preferència temporal · vel present'
js='''var prev=app.activeDocument;var ids=[];for(var i=0;i<app.documents.length;i++)ids.push(app.documents[i].id);var temp=null;try{temp=app.open(new File(__SRC__));for(var j=0;j<ids.length;j++)if(temp.id===ids[j])throw new Error("Expected own newly opened archived source");var layer=null;for(var i=0;i<temp.layers.length;i++)if(temp.layers[i].name===__NAME__)layer=temp.layers[i];if(!layer)throw new Error("Target layer absent");temp.activeLayer=layer;var f=new File(__STREAM__);f.encoding="BINARY";f.open("r");var raw=f.read();f.close();var cr=new ActionDescriptor();cr.fromStream(raw);cr.putString(charIDToTypeID("CMod"),"Filter");cr.putBoolean(charIDToTypeID("CtoG"),true);cr.putString(charIDToTypeID("CamP"),"Embedded");cr.putDouble(charIDToTypeID("Ex12"),-2.1);cr.putInteger(charIDToTypeID("Cr12"),0);cr.putInteger(charIDToTypeID("Hi12"),0);cr.putInteger(charIDToTypeID("Sh12"),-100);cr.putInteger(charIDToTypeID("Wh12"),16);cr.putInteger(charIDToTypeID("Bk12"),40);cr.putInteger(charIDToTypeID("CrTx"),100);cr.putInteger(charIDToTypeID("Cl12"),40);cr.putInteger(charIDToTypeID("Dhze"),0);cr.putInteger(charIDToTypeID("Shrp"),0);cr.putInteger(charIDToTypeID("LNR "),69);var gm=["GM_R","GM_O","GM_Y","GM_G","GM_A","GM_B","GM_P","GM_M"];for(var k=0;k<gm.length;k++)cr.putInteger(charIDToTypeID(gm[k]),0);var fi=new File(__INPUT__);fi.encoding="BINARY";fi.open("w");fi.write(cr.toStream());fi.close();var returned=executeAction(stringIDToTypeID("Adobe Camera Raw Filter"),cr,DialogModes.NO);var fo=new File(__RETURNED__);fo.encoding="BINARY";fo.open("w");fo.write(returned.toStream());fo.close();var opt=new PhotoshopSaveOptions();opt.layers=true;opt.alphaChannels=true;opt.embedColorProfile=true;temp.saveAs(new File(__DST__),opt,true,Extension.LOWERCASE);}finally{if(temp){var own=true;for(var j=0;j<ids.length;j++)if(temp.id===ids[j])own=false;if(own)temp.close(SaveOptions.DONOTSAVECHANGES);}app.activeDocument=prev;}"FULL_CONTEXT_REPLAY_DONE";'''
for key,value in [('__INPUT__',OUT/'C1_input_descriptor.bin'),('__RETURNED__',OUT/'C1_returned_descriptor.bin'),('__SRC__',src),('__STREAM__',ROOT/'output/earthshine_reconstruction_20260911/A1_camera_raw_descriptor.bin'),('__DST__',dst),('__NAME__',name)]:js=js.replace(key,json.dumps(str(value)))
print(jsx(js),flush=True)
