var root='/Users/USUARI/Downloads/Eclipse 2026/output/v65_pere_estrelles_20260914/',old=app.displayDialogs,own=[],oldDoc=app.activeDocument;
function log(s){var f=new File(root+'A2_native.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function L(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id===id)return d.layers[i];throw new Error('missing '+id);}
function only(d,ids){for(var i=0;i<d.layers.length;i++){var on=false;for(var j=0;j<ids.length;j++)if(d.layers[i].id===ids[j])on=true;d.layers[i].visible=on;}}
function mask(l,on){app.activeDocument.activeLayer=l;var d=new ActionDescriptor(),r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);d.putReference(charIDToTypeID('null'),r);var x=new ActionDescriptor();x.putBoolean(stringIDToTypeID('userMaskEnabled'),on);d.putObject(charIDToTypeID('T   '),charIDToTypeID('Lyr '),x);executeAction(charIDToTypeID('setd'),d,DialogModes.NO);}
function exp(d,n,full){var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber '+n);var t=d.duplicate('V65_QA_'+n,true);own.push(t);if(!full)t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
try{app.displayDialogs=DialogModes.NO;var src=null;for(var i=0;i<app.documents.length;i++)if(app.documents[i].id===5536)src=app.documents[i];if(!src||src.name!=='V64_Artefactes.psb'||!src.saved||src.layers.length!==27)throw new Error('source changed');var d=src.duplicate('V65_SOURCE_DIAGNOSTIC',false);own.push(d);exp(d,'A2_marked_full',true);exp(d,'A2_marked_ROI',false);L(d,97).visible=false;L(d,87).visible=false;exp(d,'A2_clean_full',true);exp(d,'A2_clean_ROI',false);
var ids=[3];only(d,ids);exp(d,'A2_c00_base');ids=[3,41,42,43,44,45,46,47];only(d,ids);exp(d,'A2_c01_filters');ids.push(30);only(d,ids);exp(d,'A2_c02_Moon');ids.push(76);only(d,ids);exp(d,'A2_c03_interiors');ids.push(83);only(d,ids);exp(d,'A2_c04_copy12');ids.push(96);only(d,ids);exp(d,'A2_c05_Pere_detail');
var sources=[3,30,76,83,96];for(var i=0;i<sources.length;i++){var id=sources[i];only(d,[id]);exp(d,'A2_L'+id+'_masked');mask(L(d,id),false);exp(d,'A2_L'+id+'_unmasked');mask(L(d,id),true);}only(d,[97]);exp(d,'A2_annotations');log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}try{app.activeDocument=oldDoc;}catch(e){}app.displayDialogs=old;}
