from pathlib import Path
import json,hashlib,datetime,os,re,subprocess
R=Path.cwd();T=R/'research/tools/v65_pere_estrelles_20260914';O=R/'output/v65_pere_estrelles_20260914';IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');claim='CODEX_V65_PERE_GEOMETRY_STARS_20260914'
def sha(p):
 with open(p,'rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def new(p,v):
 assert not p.exists(),p;p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
assert json.loads((R/'.coordination/claim.lock/owner.json').read_text())['claim_id']==claim
pub=json.loads((O/'E0_publish.json').read_text());qa=json.loads((O/'D14_integrity.json').read_text());rb=json.loads((O/'E3_final_readback.json').read_text());ca=json.loads((O/'D12_native_candidate_check.json').read_text());sources=json.loads((O/'S26_evidence_summary.json').read_text());assets=json.loads((O/'E3_assets.json').read_text());gate=(O/'E1_photoshop_gate.txt').read_text().strip();reader=(O/'E1_second_reader.txt').read_text().strip();opened=(O/'E2_final_open.log').read_text();assert qa['PASS'] and rb['PASS'] and ca['PASS'] and gate.startswith('OBRE ') and '10551x7506' in reader and 'FINAL_OPEN_COMPLETE' in opened and 'name=V65.psb saved=true' in opened
assert sha(pub['path'])==pub['sha256'];now=datetime.datetime.now(datetime.timezone.utc).isoformat();handoff=R/'.coordination/HANDOFF_2026-09-14_CODEX_CAPES_TOTALS_V65.md';report=O/'RESULTAT.md';manifest=T/'delivery_manifest.json';ui=dict(time=now,native_document_state_confirmed=True,native_evidence=str(O/'E2_final_open.log'),CUA_result='Mac locked; automatic unlock unavailable. No user interruption requested during explicitly unattended work. Native Photoshop open/save/layer state and forced full-canvas readback verified; exported image and crops reviewed.',UI_screenshot_available=False);new(O/'E4_UI.json',ui)
body=(T/'RESULTAT_template.md').read_text();fields=dict(PRODUCT=pub['path'],SHA=pub['sha256'],ASSETS=assets['folder'],GATE=gate,READER=reader,READBACK=str(rb['max_DN16']),UI='Observació GUI no disponible perquè el Mac és bloquejat; estat de document natiu i exports complets verificats.');
for k,v in fields.items():body=body.replace('@'+k+'@',v)
assert not re.search(r'@[A-Z]+@',body)
for p in [report,handoff,Path(assets['folder'])/'LLEGEIX-ME_V65.md']:assert not p.exists();p.write_text(body)
status='V65_COMPLETE_PHOTOGRAPHIC_MANUAL_GEOMETRY_60_STARS';m={**pub,'status':status,'artifact_free':False,'absolute_registration_resolved':False,'geometry_change_promoted':False,'manual_Pere_geometry_preserved_exact':True,'canvas':[10551,7506],'depth':16,'profile':'Adobe RGB (1998)','top_level_items':31,'report':str(report),'handoff':str(handoff),'manifest':str(manifest),'assets':assets,'qa':str(O/'D14_integrity.json'),'readback':rb,'all_original_masks_exact':True,'all_original_alpha_exact':True,'Earthshine_RGB_exact':True,'Pere_photo96_all_channels_exact':True,'modified_RGB_layers':[3,76],'normalization_pixels':763,'stars_distinct':60,'stellar_identifications':62,'unresolved_pairs':2,'star_PSF_sigma_final_px':1.5,'stars_are_photographic_point_regularization':True,'external_originals':sources,'source_V64_Pere_sha256':qa['source_sha256'],'source_V64_native_snapshot':str(O/'V64_Pere_input.psb'),'open_document':opened,'UI_observation':ui,'preview':str(Path(assets['folder'])/'V65_previsualitzacio.png'),'limits':['Residual dark limb relief not identified as craters; no synthetic contour smoothing.','No claim of absolute all-layer subpixel astronomical alignment; manual geometry is authoritative and untouched.','Point-source Gaussian regularization does not recover stellar surfaces or prove new optical resolution.','Natural-source photometry has PSF and extinction systematics; universal10% accuracy not claimed.','No exhaustive catalogue completeness or universal absence of artifacts claimed.']};new(manifest,m)
prefix=f'> **14-09-2026 · V65 acabada: encaix manual de Pere intacte, color del limbe i 60 estrelles.** Font real V64_Artefactes.psb (anomenada V64_CanvisPere),27 capes,SHA4ead6376… **No moure ni reaplicar matrius a aquest encaix manual.** Totes les geometries,màscares i alfa originals exactes; Earthshine30 i foto96 de perles RGB exactes. Blanc: productor de llums altes conserva color;5zones milloren davantSony. Taronja superior:601píxels de color de76,referència11 corroborada10; cap warp del projecte. Cobertura normalitzada en763píxels damunt del compost,sense radi nou; relleu fosc restant no identificat com cràters.60fonts puntuals/62identificacions(2parelles no resoltes),15RAW,0de1219controls; capaPSFgaussiana i capa de mapa oculta; resta de traces mesurades16fonts.31capes,148comprovacions de canals,PhotoshopOBRE,readback complet0DN16. PSF i flux de pantalla són regularització fotogràfica; no nova resolució ni precisió fotomètrica universal10%. Producte `{pub["path"]}`,SHA `{pub["sha256"]}`; dades `{assets["folder"]}`. Represa `{handoff}`; informe `{report}`. V64/V57 de Pere obertes i desades intactes; V65 oberta/desada,GUI no observable per Mac bloquejat. Les entrades següents són història.\n\n'
paths=[R/'AGENTS.md',R/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md',IA/'ACTIVE.json'];history={r['path']:r['after_sha256'] for r in json.loads((R/'output/v64_geometria_20260914/E5_authorities.json').read_text())['rows']};old={str(p):p.read_bytes() for p in paths}
for p in paths:assert hashlib.sha256(old[str(p)]).hexdigest()==history[str(p)],p
(O/'receipts').mkdir(exist_ok=True);rows=[];claude_sha=sha(R/'.coordination/CLAUDE_STATUS.md')
for i,p in enumerate(paths[:-1]):
 b=old[str(p)];snap=O/'receipts'/f'E5_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(b);tmp=p.with_name(p.name+'.V65.tmp');assert not tmp.exists();tmp.write_bytes(prefix.encode()+b);assert p.read_bytes()==b;os.replace(tmp,p);rows.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(b).hexdigest(),after_sha256=sha(p),old_content_exact_suffix=p.read_bytes().endswith(b)))
p=paths[-1];b=old[str(p)];snap=O/'receipts/E5_before_ACTIVE.json';snap.write_bytes(b);a=json.loads(b);earth_keys=[k for k in a if 'earthshine' in k and k!='general_earthshine_mask_override'];earth={k:json.dumps(a[k],sort_keys=True) for k in earth_keys};a['previous_general_product_V64_delivery']=a['current_product'];a['current_product']=m;a['updated']=now;a['phase']='post-eclipse-general-V65-Pere-manual-geometry-stars';a['formal_worktree_handoff']=str(handoff);a['paths']['current_technical_editable']=pub['path'];a['paths']['current_delivery_manifest']=str(manifest);a['paths']['current_visual_output']=assets['folder'];a['general_integration_task']=dict(status=status,handoff=str(handoff),report=str(report),pending='Pere visual review when he returns; no required production step remains. Manual alignment must remain unchanged.');a['historical_visual_task_before_V65']=a['visual_task'];a['visual_task']=dict(status=status,target=pub['path'],next_action='Review V65 and optional hidden star map; preserve manual V64_Artefactes geometry, existing source masks and bead photo96. Do not reapply prior automatic transformations.');a['general_earthshine_mask_override']=dict(product=pub['path'],method='Earthshine RGB, alpha, mask and geometry from Pere V64_Artefactes all exact. New composed-coverage normalization is a separate layer.',independent_Earthshine_V56_unchanged=True);assert all(json.dumps(a[k],sort_keys=True)==v for k,v in earth.items());tmp=p.with_name(p.name+'.V65.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==b;os.replace(tmp,p);rows.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(b).hexdigest(),after_sha256=sha(p)));assert sha(R/'.coordination/CLAUDE_STATUS.md')==claude_sha;new(O/'E5_authorities.json',dict(time=now,rows=rows,CLAUDE_STATUS_sha256=claude_sha,CLAUDE_STATUS_untouched=True,independent_earthshine_authority_unchanged=True))
with (R/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f'\n## {now} · V65 COMPLETE PHOTOGRAPHIC · CLAIM HELD\nManual Pere alignment, all original masks/alpha, Earthshine30 and bead photo96 exact. RGB corrections only3/76;763 existing-coverage pixels normalized in separate layer.60 stars/62 identifiers,2unresolved pairs,15RAW;0of1219nulls. PSF sigma1.5finalpx; native flux uncertainty and mismatch failures disclosed.31layers,148channel checks,full native reopen readback0DN16. Photoshop V65 saved and open; original V64_Artefactes/V57 saved states intact. Mac locked prevents CUA screenshot, native states/exports verified. Product {pub["path"]}; SHA {pub["sha256"]}. Handoff {handoff}.\n')
print('DOCUMENTED',handoff,flush=True)
