from pathlib import Path
import sys,json,numpy as np,tifffile as tf,gc
from scipy.special import erf
from PIL import Image,ImageDraw,ImageFont,ImageCms
from psd_tools.constants import BlendMode,Compression,Tag
R=Path.cwd();O=R/'output/v65_pere_estrelles_20260914';sys.path.insert(0,str(R/'research/tools/encaix_sony'));from psb_utils import new_psb,add_pixel_layer,finalize_lr16,set_merged
assert json.loads((R/'.coordination/claim.lock/owner.json').read_text())['claim_id']=='CODEX_V65_PERE_GEOMETRY_STARS_20260914';cat=json.loads((O/'S22_final_catalog.json').read_text());H,W=7506,10551;stars=np.zeros((H,W,3),np.uint16);sub=np.zeros_like(stars);psf_checks=[]
for r in cat['stars']:
 x,y=int(round(r['x'])),int(round(r['y']));yy,xx=np.mgrid[-12:13,-12:13];sx=r['x']-x;sy=r['y']-y;s=r['sigma_final_px'];g=(erf((xx+.5-sx)/(np.sqrt(2)*s))-erf((xx-.5-sx)/(np.sqrt(2)*s)))*(erf((yy+.5-sy)/(np.sqrt(2)*s))-erf((yy-.5-sy)/(np.sqrt(2)*s)))/4;g*=2*np.pi*s*s;rgb=np.rint(g[...,None]*np.array(r['display_RGB_peak'])*65535).astype('uint16');stars[y-12:y+13,x-12:x+13]=rgb;z=np.load(O/f'S23_trace_{r["id"]}.npz');a,b=z['xy'];sub[b-24:b+25,a-24:a+25]=np.maximum(sub[b-24:b+25,a-24:a+25],z['component']);lum=rgb[...,0].astype(float);norm=lum.sum();cx=(lum*xx).sum()/norm;cy=(lum*yy).sum()/norm;cov=np.array([[(lum*(xx-cx)**2).sum(),(lum*(xx-cx)*(yy-cy)).sum()],[(lum*(xx-cx)*(yy-cy)).sum(),(lum*(yy-cy)**2).sum()]])/norm;psf_checks.append(dict(id=r['id'],centroid_error=float(np.hypot(cx-sx,cy-sy)),sigma_eigen=np.sqrt(np.linalg.eigvalsh(cov)).tolist(),integrated_flux=float(norm),no_clipping=int(rgb.max())<65535))
# Annotation layer, separate from all science and photographic pixels.
im=Image.new('RGBA',(W,H));draw=ImageDraw.Draw(im);font=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',30);head=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial Bold.ttf',48);small=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',31);placed=[]
for r in cat['stars']:
 x,y=r['x'],r['y'];col=(255,221,68,255) if r['HIP'] else (104,245,155,255);txt=r['id']+(' · HIP '+str(r['HIP']) if r['HIP'] else '')+(' · doble no resolta' if r['unresolved_blend'] else '');box=draw.textbbox((0,0),txt,font=font);tw,th=box[2],box[3];best=None
 for dx,dy in [(22,-36),(22,14),(-tw-22,-36),(-tw-22,14),(22,46),(-tw-22,-70)]:
  xx,yy=x+dx,y+dy;bb=[xx-3,yy-3,xx+tw+3,yy+th+3];over=sum(max(0,min(bb[2],b[2])-max(bb[0],b[0]))*max(0,min(bb[3],b[3])-max(bb[1],b[1])) for b in placed);bad=1000000 if min(bb[:2])<0 or bb[2]>W or bb[3]>H else 0;score=over+bad
  if best is None or score<best[0]:best=(score,xx,yy,bb)
 _,xx,yy,bb=best;placed.append(bb);draw.ellipse((x-14,y-14,x+14,y+14),outline=(0,0,0,200),width=6);draw.ellipse((x-14,y-14,x+14,y+14),outline=col,width=3);draw.text((xx,yy),txt,font=font,fill=col,stroke_width=2,stroke_fill=(0,0,0,230))
# Legend occupies an existing dark corner of the annotated view, not the photograph.
draw.rounded_rectangle((180,6630,1940,7245),radius=28,fill=(10,17,20,225),outline=(180,192,188,220),width=2);draw.text((225,6675),'V65 · Estrelles recuperades',font=head,fill=(238,242,239,255));lines=['60 fonts puntuals corroborades en RAW','62 identificacions · 2 parelles no resoltes','Sony A/C + Vixen · PSF gaussiana 3,53 px','Groc: HIP · Verd: identificació TYC al catàleg','S01–S60: V65_estrelles.csv','La mida és fotogràfica; el flux lineal és al catàleg.']
for i,line in enumerate(lines):draw.text((225,6760+63*i),line,font=small,fill=(225,231,225,255))
ann=np.asarray(im);im.save(O/'V65_estrelles_anotacions.png');p=new_psb(W,H,(O/'AdobeRGB.icc').read_bytes());layers=[]
for lid,name,rgb,mask,blend,vis in [(201,'Estrelles · retirada de traces mesurades V65',sub,np.any(sub,axis=2).astype('uint8')*255,BlendMode.SUBTRACT,True),(202,'Estrelles · 60 fonts · PSF gaussiana V65',stars,np.any(stars,axis=2).astype('uint8')*255,BlendMode.LINEAR_DODGE,True),(203,'Mapa de 60 estrelles · HIP i TYC · V65',ann[...,:3].astype('uint16')*257,ann[...,3],BlendMode.NORMAL,False)]:
 l=add_pixel_layer(p,rgb,name,mask8=mask,blend=blend,visible=vis);l._record.tagged_blocks.set_data(Tag.LAYER_ID,lid);layers.append(dict(id=lid,name=name,blend=str(blend),visible=vis,support_pixels=int(np.count_nonzero(mask))));print(name,flush=True)
finalize_lr16(p);set_merged(p,stars,Compression.ZIP);dst=O/'S24_estrelles_capes.psb';assert not dst.exists();p.save(dst);del p;gc.collect();np.save(O/'arrays/S24_stars_RGB16.npy',stars);np.save(O/'arrays/S24_subtract_RGB16.npy',sub)
scene=tf.imread(O/'D8_artifacts_full.tif');scene[2777:4777,4377:6377]=tf.imread(O/'D10_normalized_ROI.tif');expected=scene.copy();expected[...,:3]=np.clip(scene[...,:3].astype('int32')-sub.astype('int32')+stars.astype('int32'),0,65535).astype('uint16');tf.imwrite(O/'S24_expected.tif',expected,photometric='rgb',extrasamples=['ASSOCALPHA'],compression='zlib',iccprofile=(O/'AdobeRGB.icc').read_bytes());icc=ImageCms.ImageCmsProfile(str(O/'AdobeRGB.icc'));srgb=ImageCms.createProfile('sRGB');out=ImageCms.profileToProfile(Image.fromarray((expected[...,:3]/257).astype('uint8')),icc,srgb,outputMode='RGB');out.resize((3165,2252),Image.Resampling.LANCZOS).save(O/'vistes/V65_previsualitzacio.png');out=out.convert('RGBA');out.alpha_composite(im);out.convert('RGB').save(O/'V65_estrelles_marcades.png');out.resize((4220,3002),Image.Resampling.LANCZOS).save(O/'vistes/V65_estrelles_marcades_4220.png');rep=dict(layers=layers,psf_checks=psf_checks,no_clipped_new_pixels=int(np.sum(np.any(scene[...,:3].astype('int32')-sub.astype('int32')+stars.astype('int32')>65535,-1))),changed_star_pixels=int(np.count_nonzero(np.any(stars|sub,axis=2))),geometry='All new layer coordinates are in the original unchanged 10551x7506 canvas.');(O/'S24_package.json').write_text(json.dumps(rep,indent=2));print('COMPLETE',dst.stat().st_size,rep['no_clipped_new_pixels'],flush=True)
