var root='/Users/USUARI/Downloads/Eclipse 2026/output/v64_geometria_20260914/',old=app.displayDialogs,own=[],work=null,keep=false;
function log(s){var f=new File(root+'D1_native.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function layer(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id==id)return d.layers[i];throw new Error('missing '+id);}
function corners(l){var r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);var q=executeActionGet(r).getObjectValue(stringIDToTypeID('smartObjectMore')).getList(stringIDToTypeID('transform'));var a=[];for(var i=0;i<q.count;i++)a.push(q.getDouble(i));return a;}
function maskEnabled(l,on){app.activeDocument.activeLayer=l;var d=new ActionDescriptor(),r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);d.putReference(charIDToTypeID('null'),r);var x=new ActionDescriptor();x.putBoolean(stringIDToTypeID('userMaskEnabled'),on);d.putObject(charIDToTypeID('T   '),charIDToTypeID('Lyr '),x);executeAction(charIDToTypeID('setd'),d,DialogModes.NO);}
function exp(d,n){var t=d.duplicate('V64_QA_'+n,true);own.push(t);t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber');var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
try{app.displayDialogs=DialogModes.NO;var e=app.open(new File(root+'Interiors_V64_exposure_monotone.psb'));own.push(e);e.layerSets[0].visible=false;e.layerSets[0].visible=true;e.save();e.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EMBEDDED SAVED');
work=app.open(new File(root+'V63_Pere_input.psb'));app.activeDocument=work;if(work.layers.length!==25)throw new Error('Source count');var so=layer(work,76),before=corners(so);work.activeLayer=so;var q=new ActionDescriptor();q.putPath(charIDToTypeID('null'),new File(root+'Interiors_V64_exposure_monotone.psb'));executeAction(stringIDToTypeID('placedLayerReplaceContents'),q,DialogModes.NO);var after=corners(layer(work,76));for(var i=0;i<8;i++)if(Math.abs(before[i]-after[i])>1e-7)throw new Error('Geometry changed');
layer(work,87).visible=false;layer(work,76).name='Interiors 06–12 · cobertura per exposició · V64';exp(work,'D1_candidate_with83');layer(work,83).visible=false;exp(work,'D1_candidate_without83');layer(work,83).visible=true;
var states=[];for(var i=0;i<work.layers.length;i++){states.push(work.layers[i].visible);work.layers[i].visible=false;}layer(work,76).visible=true;maskEnabled(layer(work,76),false);exp(work,'D1_foreground_unmasked');maskEnabled(layer(work,76),true);for(var i=0;i<work.layers.length;i++)work.layers[i].visible=states[i];work.activeLayer=layer(work,76);keep=true;log('WORK_ID '+work.id);log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}if(work&&!keep)try{work.close(SaveOptions.DONOTSAVECHANGES);}catch(e){}app.displayDialogs=old;}
