var root='/Users/USUARI/Downloads/Eclipse 2026/output/v64_geometria_20260914/',old=app.displayDialogs,own=[];
function log(s){var f=new File(root+'D4_align_copy.log');f.encoding='UTF8';f.open('a');f.writeln(s);f.close();}
function layer(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id==id)return d.layers[i];throw new Error('missing '+id);}
function corners(l){var r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);var q=executeActionGet(r).getObjectValue(stringIDToTypeID('smartObjectMore')).getList(stringIDToTypeID('transform'));var a=[];for(var i=0;i<q.count;i++)a.push(q.getDouble(i));return a;}
function exp(d,n){var t=d.duplicate('V64_QA_'+n,true);own.push(t);t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var f=new File(root+n+'.tif');if(f.exists)throw new Error('no clobber');var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(f,o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);own.pop();log('EXPORTED '+n);}
try{app.displayDialogs=DialogModes.NO;var d=null;for(var i=0;i<app.documents.length;i++)if(app.documents[i].id===5459)d=app.documents[i];if(!d||d.name!=='V63_Pere_input.psb')throw new Error('Working copy missing');app.activeDocument=d;d.activeLayer=layer(d,83);
var f=new File(root+'D4_copy_transform.json');f.open('r');var cfg=eval('('+f.read()+')');f.close();
executeAction(stringIDToTypeID('newPlacedLayer'),undefined,DialogModes.NO);var l=d.activeLayer;l.name='12 1/3200 perles · mateixa geometria que interiors · V64';var pre=corners(l),expected=[];
for(var i=0;i<8;i+=2){expected.push(cfg.matrix[0][0]*pre[i]+cfg.matrix[0][1]*pre[i+1]+cfg.matrix[0][2]);expected.push(cfg.matrix[1][0]*pre[i]+cfg.matrix[1][1]*pre[i+1]+cfg.matrix[1][2]);}
l.resize(cfg.scale*100,cfg.scale*100,AnchorPosition.MIDDLECENTER);l.rotate(cfg.degrees,AnchorPosition.MIDDLECENTER);var mid=corners(l),dx=0,dy=0;for(var i=0;i<8;i+=2){dx+=expected[i]-mid[i];dy+=expected[i+1]-mid[i+1];}l.translate(UnitValue(dx/4,'px'),UnitValue(dy/4,'px'));var after=corners(l),err=0;for(var i=0;i<8;i++)err=Math.max(err,Math.abs(after[i]-expected[i]));if(err>.01)throw new Error('Corner mismatch '+err);
log('COPY_ID '+l.id);log('PRE '+pre.join(','));log('AFTER '+after.join(','));log('EXPECTED '+expected.join(','));log('CORNER_ERROR '+err);exp(d,'D4_candidate');var states=[];for(var i=0;i<d.layers.length;i++){states.push(d.layers[i].visible);d.layers[i].visible=false;}l.visible=true;exp(d,'D4_copy_only');for(var i=0;i<d.layers.length;i++)d.layers[i].visible=states[i];d.activeLayer=layer(d,76);log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{while(own.length){try{own.pop().close(SaveOptions.DONOTSAVECHANGES);}catch(e){}}app.displayDialogs=old;}
