var root='/Users/USUARI/Downloads/Eclipse 2026/output/v64_geometria_20260914/',old=app.displayDialogs;
function log(s){var f=new File(root+'D4c_native_copy.log');f.open('a');f.writeln(s);f.close();}
function layer(d,id){for(var i=0;i<d.layers.length;i++)if(d.layers[i].id==id)return d.layers[i];throw new Error('missing '+id);}
function corners(l){var r=new ActionReference();r.putIdentifier(stringIDToTypeID('layer'),l.id);var q=executeActionGet(r).getObjectValue(stringIDToTypeID('smartObjectMore')).getList(stringIDToTypeID('transform')),a=[];for(var i=0;i<q.count;i++)a.push(q.getDouble(i));return a;}
function exp(d,n){var t=d.duplicate('V64_QA_'+n,true);t.crop([UnitValue(4377,'px'),UnitValue(2777,'px'),UnitValue(6377,'px'),UnitValue(4777,'px')]);var o=new TiffSaveOptions();o.imageCompression=TIFFEncoding.TIFFZIP;o.layers=false;o.alphaChannels=true;o.transparency=true;o.embedColorProfile=true;t.saveAs(new File(root+n+'.tif'),o,true,Extension.LOWERCASE);t.close(SaveOptions.DONOTSAVECHANGES);log('EXPORTED '+n);}
try {app.displayDialogs=DialogModes.NO;for(var i=0;i<app.documents.length;i++)if(app.documents[i].id==5498){app.documents[i].close(SaveOptions.DONOTSAVECHANGES);break;}
var e=app.open(new File(root+'Copy12_V64_original_editable.psb'));log('SOURCE '+e.layers[0].bounds);e.layers[0].visible=false;e.layers[0].visible=true;e.save();e.close(SaveOptions.DONOTSAVECHANGES);
var d=null;for(var i=0;i<app.documents.length;i++)if(app.documents[i].id==5459)d=app.documents[i];if(!d)throw new Error('missing owned work');app.activeDocument=d;var l=layer(d,90);d.activeLayer=l;var pre=corners(l);var q=new ActionDescriptor();q.putPath(charIDToTypeID('null'),new File(root+'Copy12_V64_original_editable.psb'));executeAction(stringIDToTypeID('placedLayerReplaceContents'),q,DialogModes.NO);l=d.activeLayer;log('REPLACED '+l.bounds);l.name='12 1/3200 perles · mateixa geometria que interiors · V64';
var f=new File(root+'D4_copy_transform.json');f.open('r');var cfg=eval('('+f.read()+')');f.close();var expected=[];for(var i=0;i<8;i+=2){expected.push(cfg.matrix[0][0]*pre[i]+cfg.matrix[0][1]*pre[i+1]+cfg.matrix[0][2]);expected.push(cfg.matrix[1][0]*pre[i]+cfg.matrix[1][1]*pre[i+1]+cfg.matrix[1][2]);}
l.resize(cfg.scale*100,cfg.scale*100,AnchorPosition.MIDDLECENTER);l.rotate(cfg.degrees,AnchorPosition.MIDDLECENTER);var mid=corners(l),dx=0,dy=0;for(var i=0;i<8;i+=2){dx+=expected[i]-mid[i];dy+=expected[i+1]-mid[i+1];}l.translate(UnitValue(dx/4,'px'),UnitValue(dy/4,'px'));var after=corners(l),err=0;for(var i=0;i<8;i++)err=Math.max(err,Math.abs(after[i]-expected[i]));log('CORNER_ERROR '+err);if(err>.01)throw new Error('corner mismatch');log('COPY_ID '+l.id);log('AFTER '+after.join(','));log('EXPECTED '+expected.join(','));
layer(d,87).visible=false;exp(d,'D4_candidate');var states=[];for(var i=0;i<d.layers.length;i++){states.push(d.layers[i].visible);d.layers[i].visible=false;}l.visible=true;exp(d,'D4_copy_only');for(var i=0;i<d.layers.length;i++)d.layers[i].visible=states[i];d.activeLayer=layer(d,76);log('COMPLETE');
}catch(e){log('ERROR '+e+' line '+e.line);throw e;}finally{app.displayDialogs=old;}
