from pathlib import Path
import json,hashlib,datetime,os,re
R=Path.cwd();T=R/'research/tools/v64_geometria_20260914';O=R/'output/v64_geometria_20260914';P=R/'output/v63_encaix_contorn_20260913';IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA')
def sha(p):
 with open(p,'rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def new(p,x):
 assert not p.exists(),p;p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
assert json.loads((R/'.coordination/claim.lock/owner.json').read_text())['claim_id']=='CODEX_V64_V63_GREEN_GEOMETRY_20260914'
pub=json.loads((O/'E0_publish.json').read_text());qa=json.loads((O/'D6_integrity.json').read_text());rb=json.loads((O/'E3_final_readback.json').read_text());originals=json.loads((O/'E4_external_originals.json').read_text());assert all(x['exact'] for x in originals)
gate=(O/'E1_photoshop_gate.txt').read_text().strip();reader=(O/'E1_second_reader.txt').read_text().strip();opened=(O/'E2_final_open.log').read_text();assert qa['PASS'] and rb['PASS'] and gate.startswith('OBRE ') and '10551x7506' in reader and 'FINAL_OPEN_COMPLETE' in opened and 'saved=true' in opened
now=datetime.datetime.now(datetime.timezone.utc).isoformat();handoff=R/'.coordination/HANDOFF_2026-09-14_CODEX_CAPES_TOTALS_V64.md';report=O/'RESULTAT.md';manifest=T/'delivery_manifest.json'
ui=dict(time=now,verified=True,native_document_state_confirmed=True,native_evidence=str(O/'E2_final_open.log'),CUA_result='Final AX and screenshot confirmed V64.psb at 100%, Interiors V64 selected, green annotation hidden; original V62, V63 and the unsaved Interiors document remain open.',first_attempt='Computer Use server error -10005: timeoutReached; final retry succeeded after native work completed.',scope='Actual Photoshop foreground window observed through CUA; native exports additionally reviewed at full canvas, three green marks and full contour.')
new(O/'E4_UI.json',ui)
body=(T/'RESULTAT_template.md').read_text();fields=dict(PRODUCT=pub['path'],SHA=pub['sha256'],BYTES=str(pub['bytes']),CHECKS=str(len(qa['channel_checks'])),GATE=gate,READER=reader,READBACK=str(rb['max_DN16']),UI=ui['CUA_result'])
for k,v in fields.items():body=body.replace('@'+k+'@',v)
assert not re.search(r'@[A-Z]+@',body)
for p in [report,handoff]:assert not p.exists();p.write_text(body)
status='V64_REVIEWABLE_EXPOSURE_COVERAGE_ABSOLUTE_REGISTRATION_PENDING'
m={**pub,'status':status,'artifact_free':False,'absolute_registration_resolved':False,'canvas':[10551,7506],'depth':16,'profile':'Adobe RGB (1998)','top_level_items':25,'report':str(report),'handoff':str(handoff),'manifest':str(manifest),'qa':str(O/'D6_integrity.json'),'readback':rb,'original_RGB_exact':True,'original_source_alpha_exact':True,'all_Pere_root_masks_exact':True,'source_transform_exact':qa['source_transform'],'geometry_change_promoted':False,'embedded_editable_original_interiors':7,'embedded_correction_layers':1,'embedded_group_mask_changed_pixels':40797,'embedded_mask_expected_decreases':0,'native_mask_max_DN16':qa['embedded_mask_max_DN16'],'copy12_original_exact':True,'copy12_native_effect_DN16':0,'copy12_transform_promoted':False,'source_V63_Pere_sha256':originals[0]['sha256'],'source_V63_native_snapshot':str(O/'V63_Pere_input.psb'),'source_V63_disk_snapshot':str(O/'V63_disk_input.psb'),'accepted_V62_colour_exact':True,'nonopaque_ROI_pixels_preserved':qa['nonopaque_ROI_after'],'native_alpha_max_difference':qa['alpha_ROI_max_difference_DN16'],'external_originals':originals,'UI_observation':ui,'open_document':opened,'preview':str(O/'vistes/V64_full_canvas.png'),'limits':['All seven exposures are not proven registered within 1 pixel everywhere.','Exposure-dependent opacity correction is photographic compositing, not new physical radiance or resolution.','No new external astronomical judge PASS for the final temporal limb.','Fine bright bead structure retained; Pere visual review remains open.','The original unsaved Interiors_V63_validity document remains untouched.']}
new(manifest,m)
prefix=f'> **14-09-2026 · Capes Totals V64 revisable: contacte per exposició; registre absolut pendent.** Font V63 marcada de Pere,25 capes,SHA f3dc9afb… La màscara interior estimava el continu després de barrejar exposicions: retard superior4,666px del llindar50%; ara continu per exposició i senyal corroborat en2de12/11/10. Peu superior connectat i blanc difús reduït als3verds.40.797píxels de cobertura augmentada; cap radi nou.159comprovacions: RGB/alfa originals,set interiors+divisor,totes les màscares arrel de Pere i matriu exactes. Còpia83 amagada per la màscara: amb/sense0DN16, cap transformació promoguda; el diagnòstic inicial de conversió Photoshop queda retirat. Transparència lleu11916píxels ja existent,alfa compost varia−12…+118DN16 per interpolació;cap forat nou. Photoshop25capes, readback complet{rb["max_DN16"]}DN16. Encaix absolut≤1px de totes les exposicions i últim contacte temporal NO demostrats; no PASS astronòmic extern nou. Producte `{pub["path"]}`, SHA `{pub["sha256"]}`. Represa `{handoff}`; informe `{report}`. Originals i document intern no desat de Pere intactes. Les entrades següents són història.\n\n'
history={r['path']:r['after_sha256'] for r in json.loads((P/'E5_authorities.json').read_text())['rows']}
paths=[R/'AGENTS.md',R/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md',IA/'ACTIVE.json'];old_bytes={str(p):p.read_bytes() for p in paths}
for p in paths:assert hashlib.sha256(old_bytes[str(p)]).hexdigest()==history[str(p)],p
(O/'receipts').mkdir(exist_ok=True);receipts=[]
for i,p in enumerate(paths[:-1]):
 old=old_bytes[str(p)];snap=O/'receipts'/f'E5_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(old);tmp=p.with_name(p.name+'.V64.tmp');assert not tmp.exists();tmp.write_bytes(prefix.encode()+old);assert p.read_bytes()==old;os.replace(tmp,p);receipts.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=sha(p),old_content_exact_suffix=p.read_bytes().endswith(old)))
p=paths[-1];old=old_bytes[str(p)];snap=O/'receipts/E5_before_ACTIVE.json';assert not snap.exists();snap.write_bytes(old);a=json.loads(old);earth_keys=[k for k in a if 'earthshine' in k and k!='general_earthshine_mask_override'];earth={k:json.dumps(a[k],sort_keys=True) for k in earth_keys}
a['previous_general_product_V63_delivery']=a['current_product'];a['current_product']=m;a['updated']=now;a['phase']='post-eclipse-general-V64-exposure-coverage-absolute-registration-pending';a['formal_worktree_handoff']=str(handoff)
a['paths']['current_technical_editable']=pub['path'];a['paths']['current_delivery_manifest']=str(manifest);a['paths']['current_visual_output']=str(O/'vistes')
a['general_integration_task']=dict(status=status,handoff=str(handoff),report=str(report),pending='Pere visual review of V64; absolute temporal/astronomical registration of all seven exposures remains unproven. No additional blend decision requested.')
a['historical_visual_task_before_V64']=a['visual_task'];a['visual_task']=dict(status=status,target=pub['path'],next_action='Review three green marks and whole lunar contour. If further geometry work is required, measure reserved external source features per exposure and temporal compatibility. Do not infer radius/rotation from a brightness threshold or reactivate discarded D4 copy transforms.')
a['general_earthshine_mask_override']=dict(product=pub['path'],method='Earthshine mask from Pere V63 preserved exactly, including current user edits. V64 modifies only the embedded Interiors group opacity.',independent_Earthshine_V56_unchanged=True)
assert all(json.dumps(a[k],sort_keys=True)==v for k,v in earth.items());tmp=p.with_name(p.name+'.V64.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==old;os.replace(tmp,p);receipts.append(dict(path=str(p),snapshot=str(snap),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=sha(p)))
new(O/'E5_authorities.json',dict(time=now,rows=receipts,CLAUDE_STATUS_untouched=True,independent_earthshine_authority_unchanged=True))
with (R/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f'\n## {now} · V64 REVIEWABLE COVERAGE · CLAIM HELD\nThree green marks reviewed; exposure-specific continuum improves top contact and diffuse white fringe.159channel checks: originals,all root masks,transform exact; native readback{rb["max_DN16"]}DN16. Copy83 contributes0DN16; all D4 transforms abandoned, original preserved. Correction of earlier inference: empty conversion was masked content, not a proven native conversion defect. No all-exposure≤1px claim; no new external astronomical PASS. Product {pub["path"]}. Handoff {handoff}.\n')
print('DOCUMENTED',handoff,flush=True)
