from common60 import *
import datetime,os
claim();IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');pub=json.loads((O/'E0_publish.json').read_text());qa=json.loads((O/'D6_final_QA.json').read_text());sources=json.loads((O/'E2_sources_unchanged.json').read_text());opened=(O/'E1_open.txt').read_text().strip();assert 'V60.psb | 31 layers | saved=true' in opened;now=datetime.datetime.now(datetime.timezone.utc).isoformat();handoff=R/'.coordination/HANDOFF_2026-09-13_CODEX_CAPES_TOTALS_V60.md';report=O/'RESULTAT.md';manifest=T/'delivery_manifest.json'
body=(T/'RESULTAT_template.md').read_text();repl={'PRODUCT':pub['path'],'SHA':pub['sha256'],'BYTES':str(pub['bytes']),'GATE':qa['Photoshop'],'READER':qa['independent_reader'],'READBACK':str(qa['native_readback_max_DN16']),'MANIFEST':str(manifest),'HANDOFF':str(handoff)}
for k,v in repl.items():body=body.replace('@'+k+'@',v)
for p in [report,handoff]:assert not p.exists();p.write_text(body)
m={**pub,'canvas':[10551,7506],'depth':16,'profile':'Adobe RGB (1998)','original_count':31,'output_count':31,'report':str(report),'handoff':str(handoff),'manifest':str(manifest),'qa':str(O/'D6_final_QA.json'),'source_files_unchanged':sources,'source_V59_Pere':{k:v for k,v in json.loads((O/'A0_freeze.json').read_text()).items() if k!='layers'},'open_document':opened,'artifact_free':False,'PASS_scope':'Photographic filter DC boundary correction and lunar opacity correction; 25 edited channels verified,128 compressed channels exact, native Photoshop/readback. Blue artifact not corrected. No new measured detail or resolution claim.','green':'C2 mean continuation through lunar protection, same prominence protection','lilac':'B4 opaque lunar interior; actual edge and original lunar RGB/alpha unchanged','blue':'Unchanged; no easy validated source correction identified','lunar_source_RGB_alpha_geometry_exact':True,'lunar_mask_changed_pixels':622471,'minimum_mask_edit_distance_from_support_edge_px':9.055385138137417,'native_readback_max_DN16':qa['native_readback_max_DN16'],'preview':str(O/'vistes/V60_luna_1a1.png'),'limits':['Blue artifact remains','Independent Earthshine_V56 retains old mask; correction only in general V60','Earlier ambiguous stellar candidate and absolute limb/detail limits remain','Pere visual review pending']};assert not manifest.exists();manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
prefix=f"> **13-09-2026 · Capes Totals V60: marques de la V59 de Pere.** V59 preservada; nova V60 de31capes,10551×7506RGB16AdobeRGB. Anell verd: separats nivell multiplicatiu i protecció del detall als2NRGF+4RHEF; protecció de protuberàncies preservada. Cremallera lila: pes fotogràfic V44 reutilitzat com alfaNORMAL, conservat a l'interior des deV53; interior opac ara, contorn iRGB/alfa lunar exactes.622.471píxels de màscara corregits a≥9,055px endins.25canals editats verificats,128canals exactes; PhotoshopOBRE31capes, readback{qa['native_readback_max_DN16']}DN16. Blau sense correcció simple validada:0DN16 de canvi, pendent. V59/V58/EarthshineV56 exactes. El projecte lunar independent continuaV56 amb màscara antiga; la correcció és aV60general. No nova resolució ni absència global d'artefactes. Producte `{pub['path']}`, SHA `{pub['sha256']}`. Represa `{handoff}`; informe `{report}`. Les entrades següents són història.\n\n"
rec=O/'receipts';rec.mkdir(exist_ok=True);history={q['path']:q['after_sha256'] for q in json.loads((PREV/'J2_authorities.json').read_text())['rows']};rr=[]
for i,p in enumerate([R/'AGENTS.md',R/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md']):
 assert not p.is_symlink();old=p.read_bytes();assert hashlib.sha256(old).hexdigest()==history[str(p)],('authority changed',str(p));snap=rec/f'E3_before_{i}_{p.name}';assert not snap.exists();snap.write_bytes(old);tmp=p.with_name(p.name+'.V60.tmp');assert not tmp.exists();tmp.write_bytes(prefix.encode()+old);assert p.read_bytes()==old;os.replace(tmp,p);assert p.read_bytes().endswith(old);rr.append({'path':str(p),'snapshot':str(snap),'before_sha256':hashlib.sha256(old).hexdigest(),'after_sha256':sha(p),'old_content_exact_suffix':True})
p=IA/'ACTIVE.json';old=p.read_bytes();assert hashlib.sha256(old).hexdigest()==history[str(p)];snap=rec/'E3_before_ACTIVE.json';assert not snap.exists();snap.write_bytes(old);a=json.loads(old);earth=json.dumps(a['current_earthshine_product'],sort_keys=True);a['previous_general_product_V58']=a['current_product'];a['current_product']=m;a['updated']=now;a['phase']='post-eclipse-general-V60-two-marks-corrected-blue-pending';a['formal_worktree_handoff']=str(handoff);a['paths']['current_technical_editable']=pub['path'];a['paths']['current_delivery_manifest']=str(manifest);a['paths']['current_visual_output']=str(O/'vistes');a['general_integration_task']={'status':'V60_DELIVERED_OPEN_IN_PHOTOSHOP','handoff':str(handoff),'report':str(report),'pending':'Blue artifact unchanged; Pere visual review'};a['general_earthshine_mask_override']={'product':pub['path'],'source_RGB':'Earthshine V56 exact','mask':'Interior opaque, inherited last3px/exterior exact; no new geometry','independent_Earthshine_V56':'Unmodified, legacy interior mask remains; explicit backport needed if resuming separate lunar project'};assert json.dumps(a['current_earthshine_product'],sort_keys=True)==earth
tmp=p.with_name(p.name+'.V60.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==old;os.replace(tmp,p);rr.append({'path':str(p),'snapshot':str(snap),'before_sha256':hashlib.sha256(old).hexdigest(),'after_sha256':sha(p)})
save('E3_authorities.json',{'time':now,'rows':rr,'CLAUDE_STATUS_untouched':True,'independent_earthshine_authority_unchanged':True})
with (R/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f'\n\n## {now} · V60 LLIURADA · CLAIM HELD\n\nV59 de Pere preservada;31capes. Verd: nivell continu als6NRGF/RHEF amb protecció de protuberàncies exacta. Lila: opacitat interior corregida;622.471píxels de màscara,RGB/alfa/contorn lunar exactes. Blau: sense correcció simple validada,0DN16 de canvi. Photoshop/readback{qa["native_readback_max_DN16"]}DN16;25canals editats verificats,128exactes. FontsV59/V58/V56 exactes. {opened}. Informe {report}; handoff {handoff}. Resta comprovació de processos i alliberament del claim.\n')
print('DOCUMENTED',handoff,flush=True)
