"""Promote qualified V55 pointers while preserving preceding document content."""
from common import *
import os
claim();pub=json.loads((OUT/'E4_publish.json').read_text());q=json.loads((OUT/'E3_readback.json').read_text());docs=json.loads((OUT/'F1_documentation.json').read_text());assert q['PASS'] and sha(pub['path'])==pub['sha256'];freeze=json.loads((OUT/'A0_freeze.json').read_text())
for a in freeze['authorities']:
    if a['path'].endswith(('AGENTS.md','CLAUDE.md','CLAUDE_STATUS.md','ACTIVE.json')):assert sha(a['path'])==a['sha256'],a['path']
IA=Path('/Users/USUARI/Desktop/Eclipse 2026/IA');now=datetime.datetime.now(datetime.timezone.utc).isoformat();prefix=f"> **13-09-2026 · V55 Earthshine lliurada: patró del sensor i detall.** Autorització desatesa executada en quatre vies.67Vixen, detector global contrastat en dues meitats, resposta fotogràfica espacial mesurada; retenció92/92, sense nova màscara ni nova resolució declarada. Font independent Sony16–24:0,2872→0,3463;24–40:0,4148→0,5032. Foto Sony és retenció. Injeccions condicionals360de font+360de transport; Photoshop26capes, readbackmàxim{q['max_full_DN16']}DN16. V54/V53 i88RAW exactes. D0/D6constants iD3vermell rebutjats; PSF d'estrelles no extrapolable. Producte `{pub['path']}`, SHA `{pub['sha256']}`. Represa `{docs['handoff']}`; informe `{docs['report']}`. Aquesta entrada és vigent; les notes datades següents són història. Judici visual de Pere i límits DHS/últimlimbe oberts.\n\n"
paths=[ROOT/'AGENTS.md',ROOT/'CLAUDE.md',IA/'README.md',IA/'ESTAT_ACTUAL.md',IA/'MAPA_RUTES_I_OUTPUTS.md',IA/'Coordinació/HANDOFF_VIGENT.md'];rows=[]
for i,p in enumerate(paths):
    assert not p.is_symlink();old=p.read_bytes();snapshot=OUT/'receipts'/f'F2_before_{i}_{p.name}';snapshot.write_bytes(old);new=prefix.encode()+old;tmp=p.with_name(p.name+'.V55.tmp');assert not tmp.exists();tmp.write_bytes(new);assert p.read_bytes()==old;os.replace(tmp,p);assert p.read_bytes().endswith(old);rows.append(dict(path=str(p),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=sha(p),old_content_exact_suffix=True,snapshot=str(snapshot)))
p=IA/'ACTIVE.json';old=p.read_bytes();snap=OUT/'receipts/F2_before_ACTIVE.json';snap.write_bytes(old);a=json.loads(old);a['previous_earthshine_product_V54']=a['current_earthshine_product'];a['historical_earthshine_task_preV55']=a['earthshine_task'];a['updated']=now;a['phase']='post-eclipse-earthshine-V55-sensor-pattern-reduction-delivered-DHS-open';a['formal_worktree_handoff']=docs['handoff']
a['current_earthshine_product']=dict(path=pub['path'],sha256=pub['sha256'],bytes=pub['bytes'],version=55,layers=26,canvas=[10551,7506],depth=16,source=str(CI/'Earthshine_V54.psb'),PASS='File/layer preservation; source corroboration; conditional differential injections;92/92 photographic retention; native Photoshop. Not absolute limb detector or new resolution claim.',report=docs['report'],handoff=docs['handoff'],user_feedback='Pere visual review pending',open_goal='Full last-limb scientific recovery and DHS equivalence remain open')
a['earthshine_task']=dict(status='AUTHORIZED_FOUR_ROUTES_EXECUTED; QUALIFIED_V55_DELIVERED; PERE_VISUAL_REVIEW_PENDING',completed='RGB/FPN/2D scales/star PSF investigated; best qualified detector correction delivered preserving V54 appearance, masks and92 prior texture claims.',next_action='Review V55 at same brightness as V54. Further improvement needs new constraints on train mixture/photometric response or local optical information; no repetition of rejected constant-response D0/D6 or clipped red D3.',handoff=docs['handoff'])
a['earthshine_v55_validation']=dict(source_judge=str(OUT/'B12_repeatable_external.json'),source_injection=str(OUT/'B14_repeatable_injections.json'),photographic_injection=str(OUT/'D14_differential_injection.json'),photographic_retention=str(OUT/'D11_exact_retention.json'),injection_conditional=True,photographic_independence=False,retained_claims=92,readback_max_DN16=q['max_full_DN16'],new_mask=False,new_resolution_claim=False,limb_profiles=str(OUT/'D12_profiles.json'),negative_results=docs['report'])
a['paths']['current_earthshine_editable']=pub['path'];a['paths']['current_earthshine_manifest']=docs['manifest'];a['paths']['current_earthshine_visual_output']=str(OUT)
tmp=p.with_name(p.name+'.V55.tmp');assert not tmp.exists();tmp.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');assert p.read_bytes()==old;os.replace(tmp,p);rows.append(dict(path=str(p),before_sha256=hashlib.sha256(old).hexdigest(),after_sha256=sha(p),snapshot=str(snap)))
with (ROOT/'.coordination/CODEX_STATUS.md').open('a') as f:f.write(f"\n\n## {now} · EARTHSHINE V55 LLIURADA · CLAIM ENCARA HELD\n\nQuatre vies executades. V55 SHA{pub['sha256']}; patró detector repetible i resposta espacialD10;92/92retenció,360+360injeccions condicionals, Photoshop26capes/readback{q['max_full_DN16']}DN16.25capes/màscares/alfa/cromatisme preservats; V54/V53 i88RAWexactes. D0/D6perdenunclaim iD3clipeja: rebutjats. NoPSFlunar d'estrelles ni8–16/últimlimbe/DHSnous. Informe {docs['report']}. Handoff {docs['handoff']}. Autoritats actualitzades conservant contingut anterior. Alliberament pendent de verificació final i zero workers.\n")
save('F2_authorities.json',dict(time=now,rows=rows,CLAUDE_STATUS_untouched=True));print('AUTHORITIES UPDATED',flush=True)
