"""C5 (V42) · Rebut al costat del PSB (V42_REBUT.md), RESULTAT.md, manifest i còpia IA. Després de c4 publish i e3."""
from comu42 import *
import shutil
CT = Path('/Users/USUARI/Desktop/Eclipse 2026/Projecte photoshop/1-Unint Capes/Capes Totals')


def main():
    pub = json.loads((REB42 / 'C4_publish.json').read_text()); ver = json.loads((REB42 / 'C4_verification.json').read_text()); gate = json.loads((REB42 / 'C4_photoshop_gate.json').read_text()); pk = json.loads((REB42 / 'C4_packaging.json').read_text())
    e2o = json.loads((REB42 / 'E2_AB_v36.json').read_text()); e2f = json.loads((REB42 / 'E2_AB_final.json').read_text()); b2c = json.loads((REB42 / 'B2c_correccions.json').read_text()); p2 = json.loads((REB42 / 'P2_powaaah.json').read_text()); p2b = json.loads((REB42 / 'P2b_rotacio.json').read_text())
    b3b = json.loads((REB42 / 'B3b_sense_estrelles.json').read_text()); b4f = json.loads((REB42 / 'B4f_rhef_variants.json').read_text()); e3 = json.loads((REB42 / 'E3_alineament.json').read_text()); b3 = json.loads((REB42 / 'B3_fusio.json').read_text()) if (REB42 / 'B3_fusio.json').exists() else {}
    L = ['# V42 — apuntament B de la Sony recompost (rotació +8,1′ + registre dels llargs), filtres sense estrelles, capa d\'estrelles, quatre RHEF, POWAAAH3 i LROC · research/160', '',
         f"Lliurada el {pub['published_utc']} per ordre de Pere (10-09: «fes la V42 aplicant les correccions suggerides, treu les estrelles dels filtres i deixa-les en una capa de llum mesurada»; «posa'n algun més de RHEF»; «posa'm el POWAAAH3 com a capa i alinea'l»; «torna a incloure la cara de la Lluna de la NASA»; «repassa l'alineament de totes les capes»).", '',
         f"- Fitxer: `{pub['path']}` · 10551 × 7506 · RGB16 · {pub['layers']} capes · {pub['bytes']:,} bytes · SHA-256 `{pub['sha256']}`.", f"- Photoshop real: **{gate['result']}**. Verificació capa a capa: {sum(1 for r in ver['rows'] if r['exact'])} de {len(ver['rows'])} exactes (copiades byte a byte de `V39.psb`, o iguals a les matrius u16 generades; modes, opacitats i visibilitats de la teva `V41.psb`).", '',
         '## 1. La Sony B, corregida a l\'origen', '',
         f"- Abans (V36–V41): a les estrelles, l'apuntament B queia a {e2o['rms_brut']:.1f} px rms de l'A (mediana {10.2:.1f} px), amb una rotació de {e2o['rotacio']['theta_arcmin']:+.2f}′ i les estrelles de B allargades (elongació {e2o['elongB_mediana']:.2f}).",
         f"- Ara: rotació de +8,10′ al voltant del Sol aplicada a tots els fotogrames de B, i correccions de translació mesurades a les estrelles per als tres fotogrames llargs (DSC06993 8 s: " + ', '.join(f"{k} ({v['desplacament_llenc_px'][0]:+.1f}, {v['desplacament_llenc_px'][1]:+.1f}) px al llenç" for k, v in b2c['correccions'].items()) + f"). Resultat: A→B {e2f['rms_brut']:.2f} px rms (mediana {2.0:.1f} px), rotació residual {e2f['rotacio']['theta_arcmin']:+.2f}′, elongació de B {e2f['elongB_mediana']:.2f}.",
         f"- Fusió: la porta A+B contra la Vixen s'accepta ({b3.get('pointings', {}).get('porta', {}).get('acceptada_A+B', 'n/d')}); la resta de la recepta és la de la V38.", '',
         '## 2. Estrelles fora dels filtres, dins d\'una capa', '',
         f"- {b3b['n']} estrelles (catàleg HIP/Tycho, pic real a la fusió V42) substituïdes per fons local (pla + gra de l'anell) a la fusió, la Vixen i la Sony ABANS de calcular cap filtre (r 10 px). Els filtres (ACHF, NRGF, RHEF, MGN, WOW) ja no les inflen ni les converteixen en rang.",
         "- `Estrelles (llum mesurada) · V42` (Linear Dodge 100 %): corba(fusió) − corba(fusió sense estrelles), en l'espai de pantalla; sumada a la base reconstrueix exactament la fusió amb estrelles. Cap PSF dibuixada. Les bases de pantalla V42 són sense estrelles: apaga la capa i no hi ha estrelles.", '',
         '## 3. Quatre RHEF', '', "- `P02 RHEF · V42`: la recepta V38 (rang en radi continu) sobre la base sense estrelles. `P02b υ 0,35`: la funció upsilon de sunkit-image (més suau pertot, contrast local a les cues).",
         f"- `P02c RHEF local 60°` i `P02d RHEF local 30°` (NOVES, ocultes): rang LOCAL — cada píxel es compara amb la seva banda radial de 8 px dins d'un sector de 60° o 30° centrat en ell (equalització d'histograma local en polars, sectors solapats, interpolació bilineal: cap costura). On l'anell sencer és dominat per un streamer, el rang local reparteix el contrast dins de cada sector. Quantils 1/10/50/90/99: " + ' · '.join(f"{k}: {' '.join(f'{v:.2f}' for v in d['quantils_1_10_50_90_99'])}" for k, d in b4f.items()) + '.',
         '- Totes en Multiplicar (com vas triar): la P02 al 37 %, la υ al 22 %, les locals al 37 % ocultes.', '',
         '## 4. POWAAAH3 i la cara de la Lluna', '',
         f"- `POWAAAH3 (HDR de Pere 16-08) · earthshine · V42`: el teu TIFF (15904×10608) remostrejat al llenç amb escala {p2['escala_pow_per_llenc']:.4f} (POWAAAH3→llenç, pels mars contra la LROC; el quocient de discs {p2['disc']['R']:.1f}/455,5 = 1,3066 va ser la primera estimació i es va descartar) i rotació {p2['rotacio_deg']:+.2f}°; el disc va clavat al forat V38 (Lluna a l'inici). Rotació confirmada pels mars contra la LROC (pic {p2b['mars']['pic']:.3f}, nul mirallat {p2b['mars']['nul_mirallat_max']:.3f}) i per la corona (correlació de fase a 1,2–2 R☉: ({p2['desplacament_sol_corona_px'][0]:+.1f}, {p2['desplacament_sol_corona_px'][1]:+.1f}) px, resposta {p2['resposta']:.2f}). Màscara de disc (R + 6 px, ploma 8) perquè només se'n vegi l'earthshine; edita-la si vols més o menys limbe.",
         "- `Compara LROC` (oculta): la cara de la Lluna de la NASA (LROC WAC) amb la libració i l'orientació de l'eclipsi, byte a byte de la V39 (alineada al forat).", '',
         '## 5. Alineament de totes les capes (E3 sobre el PSB publicat, amb les teves capes ja mogudes; E3b/E4 sobre les capes sense moure)', '', 'Nota: hi ha hagut tres publicacions de la V42 el 10-09 (02:15, SHA 28529bef…, capes de Pere sense moure; 12:18, SHA 3bda188b…, les set mogudes (+12, +2); 12:50, SHA c33804ad…, la vigent: 12 (+15, +2), 06–11 (+11, +2)); les seccions 1–4 i 6 es van escriure per a la primera i valen per a les tres (res més no ha canviat). La taula de sota és l’E3 reexecutat sobre la tercera (la publicada): a les teves capes 06–12 la correlació de fase amb màscara comuna dona −0,5…−1,5 px (mètode cec a translacions, vegeu més avall); la mesura bona d’després és l’E6 de la secció 7.', '', '| capa | mesura | resultat |', '|---|---|---|']
    for nom, d in e3['capes'].items():
        if 'translacio_px' in d: L.append(f"| {nom} | translació / rotació vs base (1,05–1,6 R☉) | ({d['translacio_px'][0]:+.2f}, {d['translacio_px'][1]:+.2f}) px · {d['rotacio_deg']:+.2f}° (resp {d['resposta']:.2f}) |")
        elif 'translacio_px_vs_01' in d: L.append(f"| {nom} | translació vs 01 (banda 8–32) | ({d['translacio_px_vs_01'][0]:+.2f}, {d['translacio_px_vs_01'][1]:+.2f}) px |")
        elif 'disc_mascara' in d: dm = d['disc_mascara']; L.append(f"| {nom} | disc de la màscara vs forat V38 | ({dm['desplacament_vs_forat_px'][0]:+.1f}, {dm['desplacament_vs_forat_px'][1]:+.1f}) px, R {dm['R']:.1f}" + (f" · mars vs LROC: rotació {d['mars_vs_LROC']['rotacio_residual_deg']:+.2f}°, translació ({d['mars_vs_LROC']['translacio_px'][0]:+.1f}, {d['mars_vs_LROC']['translacio_px'][1]:+.1f}) px" if 'mars_vs_LROC' in d else '') + ' |')
        elif 'desplacament_pic_px_mediana' in d: L.append(f"| {nom} | pics de la capa vs pics de la base | {d['n']} estrelles, desplaçament mediana {d['desplacament_pic_px_mediana']} px |")
        else: L.append(f"| {nom} | — | {d.get('nota', '')} |")
    e3b = json.loads((REB42 / 'E3b_rotacio_fina.json').read_text()); e4 = json.loads((REB42 / 'E4_radi_lunar_llenc.json').read_text()); f1 = json.loads((REB42 / 'F1_earthshine.json').read_text()); f1c = json.loads((REB42 / 'F1c_punt_brillant.json').read_text())
    rots = [v['rotacio_deg'] for k, v in e3b.items() if not k.startswith('control')]; ctrl = e3b['control_base_girada_+0.30']['rotacio_mesurada_deg']
    e3f = json.loads((REB42 / 'E3f_translacio_sectors.json').read_text()); e3d = json.loads((REB42 / 'E3d_rotacio_per_radi.json').read_text())
    def dsec(nom): return ' '.join(f"{o[0]}°:({o[1]:+d},{o[2]:+d})" for o in e3f[nom]['per_sector_[az,Dx,Dy,r,r0]'] if o[1] is not None)
    L += ['', f"⛔ **Les teves capes 06–12 ANAVEN desplaçades (a la V42 del matí, SHA 28529bef…, i a la V38–V41) respecte de la base i de tots els filtres, corona i Lluna alhora** (`E3f_translacio_sectors.json`, mesurat sobre la V39 = les capes sense moure: Pearson per força bruta, ln G passa-banda 4–16, anell 1,25–1,6 R☉, vuit sectors, només contingut vàlid; control base +10 px → ({e3f['control_base_+10x']['mediana_px'][0]:+.0f}, {e3f['control_base_+10x']['mediana_px'][1]:+.0f})). D = capa − base, mediana dels sectors: " + ' · '.join(f"{k.split()[0]} ({v['mediana_px'][0]:+.0f}, {v['mediana_px'][1]:+.0f})" for k, v in e3f.items() if not k.startswith('control') and k != 'metode' and v['mediana_px']) + f" px; la capa 10 per sectors: {dsec('10 1/125')}. La Lluna de les teves capes 12/11/10 (E4: cercle a ({e4['12 1/3200 perles']['cx']:.1f}–{e4['10 1/125']['cx']:.1f}, {e4['10 1/125']['cy']:.1f}–{e4['12 1/3200 perles']['cy']:.1f}), R 453,5) és 14,2–15,4 px a l'est del forat V38: el mateix vector. La vista 1:1 `E4b_limbe_est_oest_1a1.png` ho ensenya: les perles i la vora fosca de la Lluna cauen sobre el cercle GROC (E4), no sobre el cian (forat), i a l'oest les capes tenen corona dins del forat.",
          f"⛔ La taula de sota diu «≤ 0,05 px» per a les teves capes perquè l'E3 feia correlació de fase amb la MATEIXA màscara als dos costats: queda clavada a zero (control de 10 px → 0,1 px; research/125 ja ho deia). I la «rotació» de +0,26…+0,49° (E3b) que depenia del radi (E3d: +0,85° a 1,07–1,17 R☉, 0° a 1,45) NO és rotació: per sectors és un dipol (+0,9…+1,1° al S–SE, −1,1…−1,25° al N–NO), la signatura de la translació; el control de 3 px (0,06°) no tenia l'amplitud sospitada (15 px → −1,45°). Conseqüència, abans de moure-les: el forat, la LROC, el POWAAAH3, l'earthshine i les teves capes visibles (12, 07, 06) no compartien la Lluna ni la corona (~12–15 px). La cadena és la que va sobre l'efemèride (el forat = Lluna de C2, R☾ − R☉ = 14,9 px a l'oest del Sol; la teva capa 12 de C2 té la Lluna al centre del Sol). ⏭️ FET en aquesta mateixa V42 per ordre teva: secció 7.",
          '', '## 6. Earthshine V42: l\'apilat nou (F1)', '',
          f"- 8 fotogrames registrats sobre la Lluna amb la geometria viva (sense la guarda de 8 px al limbe): Sony DSC06987/06993 (8 s), DSC06984/06996/06999 (2 s), Vixen 572A2982/83/84 (10 s). Registre entre tessel·les mesurat als mars: tots < 0,2 px, cap aplicat.",
          f"- ⛔ Apuntament B EXCLÒS (declarat): EXCÉS COMPACTE DE LLUM de {min(f1c[k]['amplitud_pct'] for k in ('DSC06993', 'DSC06996', 'DSC06999')):+.0f} a {max(f1c[k]['amplitud_pct'] for k in ('DSC06993', 'DSC06996', 'DSC06999')):+.0f} % dins del disc a ({min(f1c[k]['x_llenc'] for k in ('DSC06993', 'DSC06996', 'DSC06999'))}–{max(f1c[k]['x_llenc'] for k in ('DSC06993', 'DSC06996', 'DSC06999'))}, {min(f1c[k]['y_llenc'] for k in ('DSC06993', 'DSC06996', 'DSC06999'))}–{max(f1c[k]['y_llenc'] for k in ('DSC06993', 'DSC06996', 'DSC06999'))}) del llenç als tres fotogrames B (16 σ; cap A ni Vixen el té; escala amb l'exposició: és llum; origen no identificat, candidat reflex intern de l'apuntament B); el 78–82 % de la variància dels B és aquest punt (sense ell, 1,3–1,9× més sorollosos que els A). Pesaven el 2,4 % (log de la passada amb B, no conservada en JSON).",
          "- Notes: la V41 de referència per als modes és la V41.psb re-desada per tu (SHA 0c6d953a…), no la lliurada; la P01b torna al nom de la V38 (mateixa recepta); F1b veu un punt de 5 σ (1,9 %) al 572A2984 a (5399, 4195), només en aquest fotograma (no és la mota fixa), fora de la zona de relleu.",
          "- Pesos per variància inversa mesurada (estimador entre sensors, research/127 §8): " + ' · '.join(f"{k} {v:.1f} %" for k, v in f1['pes_efectiu_pct'].items() if v > 0) + f"; cobertura del disc 100 %. Vel: perfil radial per anells fins a 0,975 R + polinomi grau 4 ajustat a r ≤ 0,85 R; residu {f1['vel']['contrast_residu_pct']:.2f} % del vel.",
          f"- Jutge LROC (orientació d'efemèride): r {f1['jutge_lroc']['banda_2_12']['r']:+.3f} a 2–12 px (nuls ≤ {max(abs(x) for x in f1['jutge_lroc']['banda_2_12']['nuls_90_180_270']):.3f}), {f1['jutge_lroc']['banda_4_16']['r']:+.3f} a 4–16 px (nuls ≤ {max(abs(x) for x in f1['jutge_lroc']['banda_4_16']['nuls_90_180_270']):.3f}). Dins de r < 0,70 R la correlació és +0,549 amb qualsevol radi del perfil (verificador); els nuls són tres girs. Les maria hi són.",
          f"- Capes (ocultes, Normal 100 %, màscara 1 fins a R 453,5 i 0 a R 457,5 = vora del forat; la franja 0,975–1,0 R és el glow mesurat): `Earthshine V42 lineal (corba)` (nivell mesurat, gra inclòs) i tres `relleu`: disc pla al NIVELL del POWAAAH3 (sRGB G {f1['relleu']['nivell_srgb_G_objectiu']:.3f} = ×{f1['relleu']['factor_nivell_sobre_vel_mesurat']:.2f} el vel mesurat, declarat), COLOR mesurat (R/G/B {'/'.join(f'{c:.3f}' for c in f1['relleu']['color_relatiu_R_G_B'])}), relleu (E − vel)/vel × K NOMÉS a r ≤ 0,85 R (zona de ciència del vel; fos a 0 fins a 0,95 R): " + ' · '.join(f"{k} K {v['K']:.1f}, σ {v['suavitzat_sigma_px']} px, contrast {100 * v['contrast_p5_p95_sobre_mediana_srgb']:.0f} %" for k, v in f1['relleu']['variants'].items()) + ". El disc pla és un NIVELL i un COLOR constants declarats (el vel mesurat dins del disc s'ha tret); la dada és el relleu ×K dins de 0,85 R i el glow de 0,975 a 1,0 R. Cap PSF, cap limbe pintat, cap píxel LROC. Vista: `F1_earthshine_disc_1a1.png` (E lineal, residu, lineal, tres relleus, POWAAAH3, LROC) i `F1_llenc_base_amb_earthshine_relleu12_suau_quart.png`.",
          "- Límits: el model de vel s'emporta l'estructura més gran que ~R/4 i no val de 0,85 R enfora (per això el relleu s'hi fon: amb el perfil curt sortia un anell brillant, i sense fondre'l una mitja lluna negra del glow asimètric); amplificació ×29–×71 sobre un senyal del 0,5 %; el color és el del vel + earthshine per la cadena CIENCIA; el limbe és el glow mesurat ×2,58."]
    mvj = json.loads((CAU42 / 'moviments_capes_pere.json').read_text()); e6 = json.loads((REB42 / 'E6_alineacio_despres.json').read_text())
    L += ['', '## 7. Les teves capes 06–12, mogudes (ordre teva del 10-09: «fixa\'t amb la protuberància principal de l\'esquerra»)', '',
          f"- Vectors: **capa 12 (perles) ({mvj['moviments']['12 1/3200 perles'][0]:+d}, {mvj['moviments']['12 1/3200 perles'][1]:+d}) px; capes 06–11 ({mvj['moviments']['10 1/125'][0]:+d}, {mvj['moviments']['10 1/125'][1]:+d}) px** (cap a l'oest i avall), aplicats al rectangle de la capa i a la seva màscara: els píxels són byte a byte els de la V39 (modes de la V41), només canviats de lloc. {mvj['justificacio']}",
          "- Després (E6, mesurat sobre el PSB publicat, anell 1,25–1,6 R☉ per sectors; la 12 no hi té contingut): " + ' · '.join(f"{k.split()[0]} ({v['D_mediana_px'][0]:+.1f}, {v['D_mediana_px'][1]:+.1f})" for k, v in e6.items() if isinstance(v, dict) and v.get('D_mediana_px')) + " px; la Lluna de les capes 12/11/10 respecte del forat: " + ' · '.join(f"{k.split()[0]} ({v['lluna']['vs_forat_px'][0]:+.1f}, {v['lluna']['vs_forat_px'][1]:+.1f})" for k, v in e6.items() if isinstance(v, dict) and 'lluna' in v) + " px (R " + '/'.join(f"{v['lluna']['R']:.1f}" for k, v in e6.items() if isinstance(v, dict) and 'lluna' in v) + "; la 12 amb " + str(e6['12 1/3200 perles']['lluna']['n']) + " punts i rms " + f"{e6['12 1/3200 perles']['lluna']['rms_px']:.1f}" + " px, les altres amb 720 i 1,2). Declarat: les capes 06–11 queden GIRADES 7–8′ (0,12–0,14°) respecte de la base al voltant del Sol (verificació independent: ±1,2 px al limbe, ±1,5 px a 1,5 R☉, ~9 px a la vora de les teves capes, on van amb màscara); cap vector ho treu i qui va girat respecte del cel no es pot decidir amb aquesta comparació.",
          "- Vistes: `E6_limbe_est_oest_despres_1a1.png` (limbe amb els cercles del forat i de la teva Lluna) i `E6_protuberancia_est_escaquer_x2.png` (base | capa moguda | escaquer). La V42 anterior (SHA 28529bef…, capes sense moure) és a `research/tools/v42_20260910/staging/V42_capes_Pere_no_mogudes_20260910.psb`: esborra-la quan vulguis.",
          "- Límit declarat: la base és un compost i prop del limbe (r < 1,13 R☉) el vector mesurat variava amb el radi i amb la capa (glow, saturació, i potser el registre dels fotogrames curts de la cadena): el vector comú és el de l'anell exterior i de la Lluna; si a la vora del forat veus la protuberància encara desplaçada, digue-m'ho i ho mesurem fotograma a fotograma (V43)."]
    L += ['', '## Capes del projecte (de baix a dalt)', ''] + [f"- {c['name']} — {c['kind']} · {c['blend'].replace('BlendMode.', '')} {c['opacity'] / 255 * 100:.0f} %{' (visible)' if c.get('visible') else ''}{' · moguda (' + str(c['moviment_px'][0]) + ', ' + str(c['moviment_px'][1]) + ') px' if c.get('moviment_px') else ''}" for c in pk['capes']]
    L += ['', "Fora: la reducció de soroll (V39/V40), per ordre teva. Vistes: `output/v42_20260910/lliurables/vistes/`. Codi: `research/tools/v42_20260910/`. Informe: `research/160`. V38–V41 intactes. Judici visual de Pere obert. ⏭️ Següent: la teva tria d'earthshine (variant, nivell, color) i el teu judici de les RHEF locals, la capa d'estrelles i l'alineació de les teves capes (secció 7)."]
    txt = '\n'.join(L) + '\n'; (CT / 'V42_REBUT.md').write_text(txt); (OUT42 / 'lliurables').mkdir(parents=True, exist_ok=True); (OUT42 / 'lliurables/RESULTAT.md').write_text(txt)
    savejson(HERE42 / 'delivery_manifest.json', {'psb': pub, 'photoshop': gate, 'verification_sha256': ver['sha256'], 'layers': ver['rows'], 'report': 'research/160'})
    shutil.copytree(OUT42 / 'lliurables', IAOUT42 / 'lliurables', dirs_exist_ok=True); shutil.copytree(REB42, IAOUT42 / '4-rebuts', dirs_exist_ok=True); log('rebut i còpia IA fets')


if __name__ == '__main__':
    main()
