"""D3 · documents després de moure les capes de Pere: CLAUDE.md (bloc V42 editat AL LLOC: SHA/bytes nous + frase), HANDOFF_2026-09-10_V42.md (secció afegida), IA/ACTIVE.json
(producte), research/160 (§8 afegit), CLAUDE_STATUS (RELEASED) i claim alliberat. Còpies prèvies a REB42/abans_d3/."""
import json, re, shutil, datetime
from comu42 import *
ROOT_ = Path('/Users/USUARI/Downloads/Eclipse 2026'); IA = Path('/Users/USUARI/Desktop/Eclipse 2026/IA'); BEFORE = REB42 / 'abans_d3'; BEFORE.mkdir(exist_ok=True)
pub = json.loads((REB42 / 'C4_publish.json').read_text()); gate = json.loads((REB42 / 'C4_photoshop_gate.json').read_text()); e6 = json.loads((REB42 / 'E6_alineacio_despres.json').read_text()); mvj = json.loads((CAU42 / 'moviments_capes_pere.json').read_text())
OLD_SHA = '28529bef67932c0fcd4d1ce66f316527c78efa9006463aa717c397a5857b19f9'; NEW = pub['sha256']; assert NEW != OLD_SHA
def snap(p): d = BEFORE / p.name; shutil.copy2(p, d); return str(d)
d_despres = ' · '.join(f"{k.split()[0]} ({v['D_mediana_px'][0]:+.0f}, {v['D_mediana_px'][1]:+.0f})" for k, v in e6.items() if isinstance(v, dict) and v.get('D_mediana_px'))
lluna = ' · '.join(f"{k.split()[0]} ({v['lluna']['vs_forat_px'][0]:+.1f}, {v['lluna']['vs_forat_px'][1]:+.1f})" for k, v in e6.items() if isinstance(v, dict) and 'lluna' in v)
frase = (f" ⏭️ **Arreglada el mateix 10-09 (migdia) per ordre de Pere («les capes no-linealitzades 6-12 no estan alineades amb 00 base, fixa't amb la protuberància principal de l'esquerra»): les set capes 06–12 de Pere MOGUDES (12: ({mvj['moviments']['12 1/3200 perles'][0]:+d}, {mvj['moviments']['12 1/3200 perles'][1]:+d}); 06–11: ({mvj['moviments']['10 1/125'][0]:+d}, {mvj['moviments']['10 1/125'][1]:+d}) px; byte a byte, rectangle + màscara), el V42.psb refet (SHA-256 `{NEW}`, {pub['bytes']:,} bytes, {gate['result']}); després (E6, anell 1,25–1,6 R☉): {d_despres} px; la seva Lluna respecte del forat: {lluna} px. La V42 anterior és a `research/tools/v42_20260910/staging/V42_capes_Pere_no_mogudes_20260910.psb`.**")
snaps = []
# CLAUDE.md: bloc V42 al lloc
p = ROOT_ / 'CLAUDE.md'; snaps.append(snap(p)); s = p.read_text(); i = s.index('⏭️ **10-09-2026 (matinada) — V42 LLIURADA'); j = s.index('\n\n', i); bloc = s[i:j]
assert OLD_SHA in bloc; bloc2 = bloc.replace(OLD_SHA, NEW).replace('8,737,946,026 bytes', f"{pub['bytes']:,} bytes") + frase; s = s[:i] + bloc2 + s[j:]; p.write_text(s)
# HANDOFF
p = ROOT_ / '.coordination/HANDOFF_2026-09-10_V42.md'; snaps.append(snap(p)); s = p.read_text(); s = s.replace(OLD_SHA, NEW).replace('8,737,946,026', f"{pub['bytes']:,}")
s += f"""
## Afegit el 10-09 (migdia): les capes 06–12 de Pere, mogudes

Ordre de Pere: «arregla la V42, les capes no-linealitzades 6-12 no estan alineades amb 00 base, fixa't amb la protuberància principal de l'esquerra». Mesures (`e5_vectors_capes_pere.py`, `e5b`, `e5c`, `e3f`): a l'anell exterior (1,25–1,6 R☉) totes les capes 06–11 són a (−10,5…−12, 0…−2,5) px de la base (mitjana (−11,2, −1,6)); la Lluna de les 12/11/10 a (−14…−15, −1…−2,6) del forat; entre elles coherents a ±2,5 px; prop del limbe (< 1,13 R☉) el vector variava amb el radi i la capa (glow, saturació): no fiable. Vectors aplicats (segona passada, després de la verificació independent de la primera amb (+12, +2)): capa 12 (perles) ({mvj['moviments']['12 1/3200 perles'][0]:+d}, {mvj['moviments']['12 1/3200 perles'][1]:+d}) px (la seva protuberància era 3 px a l'est: Pere la tenia registrada per la Lluna), capes 06–11 ({mvj['moviments']['10 1/125'][0]:+d}, {mvj['moviments']['10 1/125'][1]:+d}) px (rectangle + màscara; píxels byte a byte de la V39). Queda declarat un gir de 7–8′ de les 06–11 respecte de la base (±1,5 px a 1,5 R☉). `c4_projecte_v42.py` llegeix `cau/moviments_capes_pere.json`. Producte refet: `{pub['path']}` (SHA-256 `{NEW}`, {pub['bytes']:,} bytes, {gate['result']}). Després (E6): {d_despres} px; Lluna vs forat: {lluna} px. Vistes `E6_*`. Anterior apartada a `research/tools/v42_20260910/staging/V42_capes_Pere_no_mogudes_20260910.psb`. Verificació independent: `REB42/W2_verificacio_alineacio.json`.
"""
p.write_text(s)
# research/160 §8
p = ROOT_ / 'research/160_V42_SONY_B_ROTADA_FILTRES_SENSE_ESTRELLES_RHEF_LOCAL_POWAAAH3_20260910.md'; snaps.append(snap(p)); s = p.read_text()
s += f"""
## 8. Les capes 06–12 de Pere, mogudes (10-09, migdia)

Pere: «arregla la V42, les capes no-linealitzades 6-12 no estan alineades amb 00 base, fixa't amb la protuberància principal de l'esquerra». Mesures abans de moure res: `e5_vectors_capes_pere.py` (protuberància, sector 160–200°, r 1,0–1,35: D per capa de −4,6 a −10,4 px en x, segons quina part de la protuberància és vàlida a cada exposició), `e5b` (anell 460–560 px del forat: dominat per la rampa del glow i la vora de la Lluna, no per la corona), `e5c` (vector en funció del radi: estable a (−11…−13, −1…−4) de 1,13 R☉ enfora a l'est, l'oest i el nord; inestable a menys d'1,13), `e3f` (anell 1,25–1,6 R☉: (−10,5…−12, 0…−2,5) a les sis capes amb corona, mitjana (−11,2, −1,6); control exacte), E4 (Lluna de les 12/11/10: (−14…−15, −1…−2,6) del forat, mitjana (−14,6, −2,1)), i les capes entre elles (E3f 09−10 = (+1, −1,5); E4 12−10 = (−1,3, +1,3); al log, força bruta a les perles, 12−10 = (+2, −1) i 09−10 = (−1, −1): coherents a ±2,5 px, dins del soroll de la mesura). Primera passada: un sol vector (+12, +2) per a les set (compromís entre la corona, 11, i la Lluna, 14,6); la verificació independent sobre aquell PSB va trobar el residu de la corona a (+0,9, +0,2) px (demanava 11) i que la capa 12 —les perles— és l'única diferent: la seva Lluna coincideix amb la de la 10 (Pere la va registrar per la Lluna) però la seva protuberància queda 3 px a l'est (canal R; en G la protuberància vermella és fosca i E5/E6 no la veien). Decisió final (criteri de Pere = la protuberància): **capa 12 ({mvj['moviments']['12 1/3200 perles'][0]:+d}, {mvj['moviments']['12 1/3200 perles'][1]:+d}) px; capes 06–11 ({mvj['moviments']['10 1/125'][0]:+d}, {mvj['moviments']['10 1/125'][1]:+d}) px**; amb això la Lluna de la 12 cau al forat (la Lluna de C2) i les de 10/11, preses uns segons més tard, queden 2–3 px a l'est, com toca. Queda declarat un GIR de 7–8′ (0,12–0,14°) de les capes 06–11 respecte de la base al voltant del Sol (verificador: rms 1,0 → 0,3 px en ajustar-lo; ±1,2 px al limbe, ±1,5 px a 1,5 R☉, ~9 px a la vora de les capes): cap vector el treu; qui va girat respecte del cel (les capes de Pere o la cadena) no es pot decidir amb aquesta comparació, aplicat al rectangle de la capa i a la seva màscara d'usuari (píxels byte a byte de la V39; `c4_projecte_v42.py` + `cau/moviments_capes_pere.json`). Producte refet: SHA-256 `{NEW}` ({pub['bytes']:,} bytes; {gate['result']}). Després (`e6_alineacio_despres.py`, sobre el PSB publicat): {d_despres} px a l'anell exterior (el residu de +1…+2 en x és el que separa el compromís de la corona sola); la Lluna de les 12/11/10 respecte del forat: {lluna} px (la 12 amb 313 punts i rms 3 px). L'E3 reexecutat sobre el PSB mogut (fase amb màscara comuna, cec a translacions) dona −0,5…−1,5 px i 0/−0,25°.

Límit declarat: la base és un compost; prop del limbe (r < 1,13 R☉) el vector capa − base variava amb el radi (−4,6 a la capa de les perles, −8 a la de 1/125, −10 a les llargues) i cap mesura hi era estable: si és la cadena (registre per translació dels fotogrames curts, que a 1,3–8 R☉ no tenen senyal per registrar-se), la cura és a l'origen (V43, fotograma a fotograma); si a Pere la protuberància encara li surt desplaçada a la vora del forat, aquest és el següent pas.
"""
p.write_text(s)
# IA/ACTIVE.json
p = IA / 'ACTIVE.json'; snaps.append(snap(p)); a = json.loads(p.read_text()); a['updated'] = pub['published_utc']; cp = a.get('current_product', {}); cp.update({'sha256': NEW, 'bytes': pub['bytes'], 'published_utc': pub['published_utc'], 'photoshop': gate['result'], 'note': "Pere's layers 06-12 moved (+12, +2) px byte-exact on 2026-09-10 by his order; previous file set aside in research/tools/v42_20260910/staging/"}); a['current_product'] = cp
a['visual_task'] = {'status': 'DELIVERED_V42_ALIGNED_PENDING_PERE_VISUAL_JUDGEMENT', 'target': pub['path'], 'next_action': 'Pere judges the prominence seam and chooses the earthshine variant; V43 if the inner ring of the chain needs per-frame re-registration'}
p.write_text(json.dumps(a, indent=2, ensure_ascii=False) + '\n')
# CLAUDE_STATUS: RELEASED + claim
p = ROOT_ / '.coordination/CLAUDE_STATUS.md'; s = p.read_text(); ts = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
s = s.replace("## V42 (arreglada) — les capes 06–12 de Pere mogudes perquè coincideixin amb la base — IN_PROGRESS (10-09, matinada)", "## V42 (arreglada) — les capes 06–12 de Pere mogudes perquè coincideixin amb la base — RELEASED (10-09, migdia)")
s = re.sub(r"- `status: IN_PROGRESS` · `serial_writes: CLAIMED` · `owner: claude` · `claim_id: CLAUDE_V42_ALINEA_20260910` · `acquired_utc: [^`]*`", f"- `status: RELEASED` · `serial_writes: RELEASED` · `owner: null` · `released_utc: {ts}` · claim_id que hi havia: CLAUDE_V42_ALINEA_20260910", s, count=1)
s = s.replace("- Pla: mesurar el vector enter de cada capa a la protuberància de l'est (`e5_vectors_capes_pere.py`), moure les set capes byte a byte (bbox + màscara), refer el V42.psb (c4 build/verify/gate/publish), tornar a mesurar, rebut/160/traspàs/CLAUDE.md al dia. La V42 anterior (SHA 28529bef…) queda apartada a `research/tools/v42_20260910/staging/`.",
              f"- Fet: set capes mogudes ({mvj['vector_comu_px'][0]:+d}, {mvj['vector_comu_px'][1]:+d}) px; V42.psb refet (SHA-256 `{NEW}`, {pub['bytes']:,} bytes, {gate['result']}); E6 després: {d_despres} px; Lluna vs forat {lluna} px. Anterior a `research/tools/v42_20260910/staging/V42_capes_Pere_no_mogudes_20260910.psb`.")
p.write_text(s)
cl = ROOT_ / '.coordination/claim.lock'
if cl.exists(): shutil.rmtree(cl)
savejson(REB42 / 'D3_docs_alineacio.json', {'snapshots': snaps, 'sha_nou': NEW, 'updated_utc': ts}); log('D3 fet · claim alliberat')
